### ISSUE TITLE
Consider multi-channel output in the Grid Aggregator!

### ISSUE THREAD

**Issue by surajpaib** [fepegar/torchio#100]
Problem:
The GridAggregator can only take shapes as the same size as the input. Multi-class probabilistic pixel-wise values don't currently fit into this structure.

Possible Solution:
A keyword entry to the gridaggregator with number of channels and consider channels as well while incorporating the patch aggregator

Alternatives:
I currently use binary prob. pixel wise values so 1-p works!

**Comment by surajpaib** [comment]
I can submit a PR for this by the end of the week if that works out in your roadmap @fepegar

**Comment by fepegar** [comment]
Sounds good, thanks!

**Comment by fepegar** [comment]
Is this so that you can have a 4D image with continuous probabilities for each class?

**Comment by surajpaib** [comment]
Exactly! Sorry I haven't been able to dedicate time over the past weekend. Seems like its going to be hard to take out time for now

**Comment by surajpaib** [comment]
Thanks @fepegar ! Looks good! Appreciate it!

**Comment by fepegar** [comment]
Thank you for reporting :+1:

**Comment by fepegar** [comment]
@all-contributors please add @surajpaib  for ideas
