### ISSUE TITLE
Proposal of a new way for DDP, Distributed Sampler, and Queue to work

### ISSUE THREAD

**Issue by hsyang1222** [fepegar/torchio#1013]
**🚀 Feature**

When using DDP and Distributed Sampler, Queues together, I would like to propose a new method of distributing them by subject rather than patch.

**Motivation**

If it operates in the current way, the queue of each node will first create an unused patch and then select some of them. In particular, there is an inefficiency that the subject is transformed repeatedly.

**Additional context**

Hi. I have a question about fepegar.torchio's quque and Distributed Data Parallel (DDP).

I think the code works differently from the user's intention when DDP and queue are used together.
Users will want to create queues in parallel and learn quickly using DDP and Distributed Sampler (DS).
If you set up the DS in general (the way it's in Pytorch's document), it'll look like this.

```python
queue = torchio.Queue( subject_dataset, num_workers=workers)
ds_sampler = torch.utils.data.distributed.DistributedSampler(queue)
dataloader = torch.utils.data.DataLoader(queue, batch_size=batch, num_workers=0, sampler=ds_sampler)
```

However, this code becomes inefficient. DS will distribute the patches created by queue across all nodes. But queue doesn't know where any of own patches will spread. So all queues are going to make patch from all the subjects first and then use only the patch chosen by DS (which makes it very inefficient). In particular, this method greatly increases the computational load because the same subject is transformed on all nodes. If you use four nodes in DDP, the same subject is transformed four times over and over again.
I think it's right to distribute DS to nodes by subject instead of  patch. If DS will distribute the subject by node, queue will patch only the subject it is assigned to, and all patches created in each queue will be used for learning.

I made this modified code. If you use my code, it will work as below.
```python
ds_sampler = torch.utils.data.distributed.DistributedSampler(subject_dataset) # not queue
queue = torchio.Queue( subject_dataset, num_workers=workers, subject_sampler = ds_sampler)
dataloader = torch.utils.data.DataLoader(queue, batch_size=batch, num_workers=0)
```

If you think this idea is good, I'll pull my code.

**Comment by QingYunA** [comment]
hi, I have seen your ideas, I think it is great.
another question, have you test your revised code? does it works well?

**Comment by hsyang1222** [comment]
yes @QingYunA , I test in my own environment and verifyed it make the learning speed up

if you want to use it, check my pull request : https://github.com/fepegar/torchio/pull/1021

**Comment by fepegar** [comment]
Added in `v0.18.88`. Thanks, @hsyang1222!
