### ISSUE TITLE
GridSampler without subject for validation

### ISSUE THREAD

**Issue by arthursw** [fepegar/torchio#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

I cannot reproduce the [GridSampler example](https://torchio.readthedocs.io/patches/patch_training.html#torchio.data.GridSampler) (see below) since in the current version, [subject cannot be none](https://github.com/fepegar/torchio/blob/main/src/torchio/data/sampler/grid.py#L78):

I need a regular grid sampler to always have the same patches in my validation. Using a uniform sampler is a problem because I have high class imbalance ( with 2 classes ) so the validation is sometimes almost entirely empty.

Instead I need the validation patches to be always the same, and ideally to contain all possible patches.

### Code for reproduction

```python
import torchio as tio
sampler = tio.GridSampler(patch_size=88)
colin = tio.datasets.Colin27()
for i, patch in enumerate(sampler(colin)):
    patch.t1.save(f'patch_{i}.nii.gz')
# To figure out the number of patches beforehand:
sampler = tio.GridSampler(subject=colin, patch_size=88)
len(sampler)
```

### Actual outcome

Assertion error line 78.

### Expected outcome

It should create the sampler normally.

### System info

```shell
Platform:   Linux-4.15.0-135-generic-x86_64-with-glibc2.27
TorchIO:    0.18.86
PyTorch:    1.13.1+cu117
SimpleITK:  2.2.0 (ITK 5.3)
NumPy:      1.22.3
Python:     3.8.14 (default, Sep  8 2022, 00:02:10) 
[GCC 7.5.0]
```

**Comment by hsyang1222** [comment]
How about running in the below style?

```python
import torchio as tio
colin = tio.datasets.Colin27()
colin_subjects = [colin] * 100 # let's suppose this is your dataset
for i, subject in enumerate(colin_subjects):
    sampler = tio.GridSampler(subject, patch_size=88)
    for j, patch in sampler:
        patch.t1.save(f'patch_{i}.nii.gz')
```

if you want to inference your model, then the code will be like : 
```python
import torchio as tio
colin = tio.datasets.Colin27()
colin_subjects = [colin] * 100 # let's suppose this is your dataset
for i, subject in enumerate(colin_subjects):
    sampler = tio.GridSampler(subject, patch_size=88)
    subject_loader = torch.utils.data.DataLoader(sampler, batch_size=8)
    for j, batch_patch in subject_loader :
        model(batch_patch[INPUT_NAME])
```

**Comment by arthursw** [comment]
Ok I can do that, thanks! 
But the documentation is not up-to-date ; the given example in the doc does not work.

**Comment by fepegar** [comment]
Thanks for reporting, @arthursw, and for replying, @hsyang1222.

You're both right. The docs are out of date. I've fixed the example and made `subject` mandatory in the `__init__`. I've added a fix in https://github.com/fepegar/torchio/pull/1029.

> I need a regular grid sampler to always have the same patches in my validation. Using a uniform sampler is a problem because I have high class imbalance ( with 2 classes ) so the validation is sometimes almost entirely empty.
> Instead I need the validation patches to be always the same, and ideally to contain all possible patches.

You might want to take a look at the [inference](https://torchio.readthedocs.io/patches/patch_inference.html#inference) docs.
