### ISSUE TITLE
The rotation given by Random Affine not accurate

### ISSUE THREAD

**Issue by zhilothebest** [fepegar/torchio#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

When I ask torchio to run a random affine with rotations between -5 to +5 degrees, I get a much wider degree rotation, probably something in the ~20+ degree range, and it appears more like a skew than a true rotation

### Code for reproduction

```python
img = [ CT scan] #in tio.Subject

transform = tio.RandomAffine(scales=(1,1,1,1,1,1),
                                 degrees=(0,0,0,0,-5,5), 
                                 center = 'image',
                                 image_interpolation='bspline',
                                 label_interpolation = 'bspline',
                                 default_pad_value = 'mean',
                                p=1)

formed = transform(img)
formed = np.moveaxis(formed.image.numpy(), [3,0],[0,3])

imshow(formed[slice])
```

### Actual outcome

original image
![original image](https://user-images.githubusercontent.com/21052148/224862955-e2cc986f-2bde-45aa-a81e-7d94fc9d1424.png)

transformed image
![image](https://user-images.githubusercontent.com/21052148/224863190-3dd49c61-4a4f-4298-a5b5-70928aab5559.png)

Pictures to show the outcome.

### Expected outcome

Ideally, if it was truly rotations around the Z axis's image center, the circle should maintain its shape as a circle and not be deformed.

**Comment by romainVala** [comment]
Hello

that sound weird, I do not reproduce with for instance with 
suj =tio.datasets.mni.Colin27()

I would say it comes from your image (can you share it ?)
may be the z axis is not was you think

**Comment by zhilothebest** [comment]
Sadly, I am unable to share the full data file due to agreements between the owner of the dataset and I. But would love help in how to implement in any other way. Ive tried isolating with x and y axis but , y axis rotates along the j index and x axis rotates along the I index.

**Comment by romainVala** [comment]
what is the shape of the data, can you report a print of the affine

**Comment by zhilothebest** [comment]
![image](https://user-images.githubusercontent.com/21052148/225180504-8ca14604-49fa-40bb-b0cb-7074277d2ef8.png)

**Comment by zhilothebest** [comment]
The affines were in the incorrect order. That fixed it.
