### ISSUE TITLE
The Affine matrix does not change after applying the augmentations

### ISSUE THREAD

**Issue by vasl12** [fepegar/torchio#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

The affine matrix that transforms the image to world coordinates is not changing after applying the geometric augmentations to the image. Is there a reason for that?

### Code for reproduction

```python
Affine
```

### Actual outcome

Affine

### Expected outcome

affine + transformation

**Comment by romainVala** [comment]
hello
your code for reproduction is difficult to understand ...

if I understand correctly the question: why the volume affine does not change after deformation (RandomAffine or RandomElastic)
Yes it is expected

For pure translation for instance, I can understand the question. (it has something to do with a passive or active referential choice)

If you change the affine (to account for the translation) then technically both volume are then identical ... (ie the vixek grid data will not changed ... just the header)
This is not what we want. We want  to simulate to subject translation while acquiring the same FOV, so a translation of the object within the same FOV (so the Volume affine does not change)

for non linear deformation like RandomElastic there is no other solution ... (we locally deformed the shape) but still keeping the same grid

does it make sense ?

**Comment by vasl12** [comment]
Hi @romainVala,

excuse me for the "code reproduction", I did not really know how to describe it properly with code.

Thank you very much for the answer, I see your point. 
The reason I was asking is that I would like to have both the transformed image and the transformation after applying e.g. RandomAffine to one of my images.  I was expecting that this will be somehow reflected in the header affine, but now I understand your point.
Thank you once again for your answer :)

**Comment by romainVala** [comment]
what is your use case ?
I can imagine that if you want to train a coregistration task then you want to know the Affine transform that has been applied with the RadomAffine transform

Well all information is in the subject history

```
import torchio as tio 
s=tio.datasets.Colin27()      
tr=tio.RandomAffine()    
st=tr(s)

st.history                                                                                                                                                                        
Out[13]: [Affine(scales=(1.0134488344192505, 0.9747917056083679, 0.9191530346870422), degrees=(-6.250537872314453, 9.650617599487305, -0.15413999557495117), translation=(0.0, 0.0, 0.0), center=image, default_pad_value=minimum, default_pad_label=-1, image_interpolation=linear, label_interpolation=nearest, check_shape=True)]

```
Now having this information is just half of the job, you then need to construct the corresponding Affine matrix
Unfortunately this will depend on the software used to apply it 
for instance sitk or nibabel ... since they have a different convention (on the voxel order) they have different Affine (for coding the same displacement)
Going trough this is always a lot of pain ... good luck if you need it ...
