### ISSUE TITLE
Return sampled parameters upon request

### ISSUE THREAD

**Issue by LvanderGoten** [fepegar/torchio#1117]
**Pitch**
Self-supervised learning is gaining more and more traction: It would be a nice feature if a specification of the sampled augmentation could be returned, e.g. the sampled mean/stddev for `RandomNoise`. This could be activated by a flag (e.g. `return_sampled_params`) and would then lead to a tuple being returned.

**Comment by romainVala** [comment]
Hi
If you use a torchio Subject, then after any transform, you can get the applied parameters in ` subject.history`

**Comment by fepegar** [comment]
@LvanderGoten here are some self-supervised papers using TorchIO, in case they help: https://scholar.google.com/scholar?hl=en&as_sdt=2005&sciodt=0%2C5&cites=11818021599290863762&scipsc=1&q=self-supervised&btnG=

**Comment by LvanderGoten** [comment]
Thank you so much!
