### ISSUE TITLE
bug in rotation part of tio.transforms.RandomAffine

### ISSUE THREAD

**Issue by javidsss** [fepegar/torchio#1126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

I experimented with various "degrees" values in tio.transforms.RandomAffine, and found that I randomly get empty images. Overall, due to the nature of rotation transformation, I expected some inconsistencies between different runs, but not getting completely zero images.

### Code for reproduction

```python
for i in range(20):
    transform_rotate = tio.transforms.RandomAffine(degrees=(0,0,0,0,5,5), p=1) # I experimented with degrees=(0,0,0,0,5,10), etc.
    torchio_image_rotate = transform_rotate(torchio_image)
    plt.figure()
    plt.imshow(torchio_image_rotate.data[0, :, :, 1], cmap='gray') #torchio_image_rotate shape: torch.Size([1, 224, 224, 48])
```

### Actual outcome

Out of 20 images, maybe around 13-14 of them look very similar to each other and are the correct rotated images by around 5 degrees, however, about 6-7 of the output images are just zeros

### Error messages

```python-traceback
No error, the outcome is not correct
```

### Expected outcome

I expected about 20 images relatively similar to each other. They should be about 5 degrees rotated with respect to their last axis

**Comment by romainVala** [comment]
Hi
sound weird, I suspect it comes from your images
but try with 
transform_rotate = tio.transforms.RandomAffine(degrees=(0,0,0,0,5,5), p=1, scale=0)
by default scaling factor is 0.1

**Comment by fepegar** [comment]
@javidsss, can you please share some data, a minimal working example and screenshots?

**Comment by fepegar** [comment]
By the way, you are showing the top slice, which will probably be black if you are looking, for example, at an MRI in RAS orientation:

```python
torchio_image_rotate.data[0, :, :, 1]
```

**Comment by javidsss** [comment]
Thank you all for your help. The trick with adding scales=0 solved the issue.
