### ISSUE TITLE
CropOrPad only crops Mask

### ISSUE THREAD

**Issue by nwschurink** [fepegar/torchio#117]
**TorchIO version**
0.15.0

**What I did**
Create the following sequence of transforms:

```
input_H = 160
input_W = 160
input_D = 80

transforms = [
    torchio.transforms.ToCanonical(),
    torchio.transforms.Resample(target_spacing=(1,1,1)),
    torchio.transforms.RescaleIntensity(out_min_max=(0,1),percentiles=(0.5,99.5)),
    torchio.transforms.ZNormalization(),
    torchio.transforms.CropOrPad(target_shape=(input_D,input_H,input_W),padding_mode='constant',padding_fill=0,mask_name='mask'),
]
transform = Compose(transforms)

dataset = ImagesDataset(subjects, transform=transform)
sample = dataset[0]
```
I then checked the size of one of the images in the `sample` e.g. `sample['t2']['data'].shape` which returns `torch.Size([1, 247, 345, 346])` whereas `sample['mask']['data'].shape` returns `torch.Size([1, 80, 160, 160])`

**What I expected to happen**
Both the image and mask have the same size

**What actually happened**
The sizes are different.

**Possible reason**
In the crop and pad function ([here](https://github.com/fepegar/torchio/blob/master/torchio/transforms/preprocessing/spatial/crop_or_pad.py#L224-L225)) these lines should probably be changed

```
        padding_params = tuple(padding.tolist()) if padding.any() else None
        cropping_params = tuple(cropping.tolist()) if padding.any() else None
```
should be

```
        padding_params = tuple(padding.tolist()) if padding.any() else None
        cropping_params = tuple(cropping.tolist()) if cropping.any() else None
```

**Comment by fepegar** [comment]
Hi @nwschurink. Thanks for reporting. That's obviously me pasting the previous line. I'll fix that in a sec.

**Comment by fepegar** [comment]
I haven't been able to reproduce your issue with this code:

```python
from torchio import Image, Subject, ImagesDataset, INTENSITY, LABEL, DATA
from torchio.transforms import CropOrPad

subject = Subject(
    t1=Image('/tmp/t1.nii.gz', INTENSITY),
    label=Image('/tmp/eyes.nrrd', LABEL),
)
transform = CropOrPad((79, 160, 160), mask_name='label')
dataset = ImagesDataset([subject], transform=transform)
sample = dataset[0]

for key in sample:
    print(sample[key][DATA].shape)

dataset.save_sample(
    sample,
    dict(t1='/tmp/t1_crop.nii.gz', label='/tmp/eyes_crop.nii.gz'),
)
```

Output:

```python
torch.Size([1, 80, 160, 160])
torch.Size([1, 80, 160, 160])
```

The shapes are wrong (as I have reported in #119), but consistent. Can you share a minimal working example and, if possible, some data? You can send it by email if you like.

**Comment by nwschurink** [comment]
I think the reason why this happens is related to [issue 117](https://github.com/fepegar/torchio/issues/117) and probably can be reproduced by changing the field of view of the mask to its bounding box (before loading it to Subject, e.g. your 'eyes.nrrd'). 

The reason for this is that when the field of view of the mask and image are not the same it is possible that `padding.any()` evaluates to None for the T1 image (when the new crop falls within the field of view of the T1 scan). The result of this is that in the current code `tuple(cropping.tolist())` is not assigned to `cropping_params`, whereas for the mask this line does get executed since the mask apparently needs padding and thus `padding.any()` is not empty.

I can check if i can make a minimum working example

**Comment by fepegar** [comment]
> The reason for this is that when the field of view of the mask and image are not the same

Do you mean the shapes are different? Maybe I misunderstood, but that should be checked in
https://github.com/fepegar/torchio/blob/992ab56cef58f6e5dd9480da1f9b77b6cce1ca9d/torchio/transforms/preprocessing/spatial/crop_or_pad.py#L97-L106

**Comment by nwschurink** [comment]
Ah, ok then I think there must be something going wrong in the `check_consistent_shape` check.

I just checked the input size of my images. My T2 image has size `(320,320,36)` and my mask has size `(18,22,6)` (i.e. it only contains the bounding box of the segmentation)

**Comment by nwschurink** [comment]
Hmm, it's weird when I run check_consistent_shape on my sample subject it returns a value error because of inconsistent shapes. So the test should be working

**Comment by nwschurink** [comment]
Ah ok I've found out why the check is not working. The shape check is only performed when doing a center crop (e.g  `_compute_center_crop_or_pad`) ([here](https://github.com/fepegar/torchio/blob/992ab56cef58f6e5dd9480da1f9b77b6cce1ca9d/torchio/transforms/preprocessing/spatial/crop_or_pad.py#L161)). However, the check is not performed when performing a crop on the mask's center (e.g. `_compute_mask_center_crop_or_pad`)

**Comment by fepegar** [comment]
Good catch!

@GReguig could you please look into this?

**Comment by GReguig** [comment]
Ok, I will give it a look
