### ISSUE TITLE
about the image shape

### ISSUE THREAD

**Issue by 2345678y3** [fepegar/torchio#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

when i try torchio,the dataset shape is NCHWD after dataloader, but my project is based on pytorch.  in the PyTorch documentation :the network  covn3d input shape is NCDHW，Does this have an impact on the predictions?Do I need to transpose the shapes？thanks !
![屏幕截图 2024-09-19 000303](https://github.com/user-attachments/assets/a1cba68b-5439-48e4-ae7c-bd27bfc343a0)
![屏幕截图 2024-09-19 000232](https://github.com/user-attachments/assets/1a0521f7-ed5e-4a54-9c7d-b36378ea9a4c)

### Code for reproduction

```python
no
```

### Actual outcome

no

### Expected outcome

no

**Comment by fepegar** [comment]
The axes in the docs have those names for historical reasons. You don't need to worry about transposing dimensions. I would recommend always using [ToCanonical](https://torchio.readthedocs.io/transforms/preprocessing.html#torchio.transforms.ToCanonical) for your images, though.
