### ISSUE TITLE
Option to add a coregistration matrix before resampling

### ISSUE THREAD

**Issue by GFabien** [fepegar/torchio#131]
**Is your feature request related to a problem? Please describe.**
When working with MRI volumes, we like to have one reference template image and use all the images in the MNI reference space. Therefore, before resampling one image, we need to multiply its affine by a coregistration matrix in order to end up in the MNI reference space. This could be seen as a resampling strategy and therefore we think that it would make sense to add an option in the Resample transform to handle this.

**Describe alternatives you've considered**
To implement this feature we want to add a string parameter to the Resample transform that would point to the name of a key in the images of the dataset. The value associated to this key would be a 4x4 matrix that we would multiply with the affine of the image before resampling. Default matrix would be identity to preserve current behaviour if we do not want to perform coregistration or if there is an image which do not have a coregistration matrix attached.

Usage would be:
```python
import numpy as np
import torchio
from torchio.transforms import Resample
from torchvision.transforms import Compose

coregistration = np.eye(4)
subject = torchio.Subject(
    t1=torchio.Image(img_path, torchio.INTENSITY, coregistration=coregistration),
    label=torchio.Image(mask_path, torchio.LABEL),
    ref=torchio.Image(ref_path, torchio.INTENSITY),
)
subject_list = [subject]
transforms = [
    Resample(target='ref', coregistration='coregistration'),
]
transform = Compose(transforms)
dataset = torchio.ImagesDataset(subject_list, transform=transform)
```

Are you interested in such a feature? I have the PR ready, we implemented this on @romainVala 's fork.

**Comment by fepegar** [comment]
Sure, please go on.
