### ISSUE TITLE
Subject with multiple images

### ISSUE THREAD

**Issue by hadhoryth** [fepegar/torchio#135]
Thank you for sharing great library! 
I would like to ask, is it possible create a `Subject`  with multiple images? Something like that:

> subj = Subject(t1=Image(), t2=Image(), age='45')
subj['t1'].append(Image())
subj['age'].append('46')

or

> subj = Subject(t1=[Image(), Image()], t2=[Image(),Image()], age=['45', '46'])

**Comment by fepegar** [comment]
Hi @hadhoryth,

I'm not sure what you mean, but you can certainly create a `Subject` with multiple images! Can you tell me a bit more about your application?

What about this:

```python
subject = Subject(
    t1_1=Image(path, type_, age=45),
    t1_2=Image(path, type_, age=46),
    t2_1=Image(path, type_, age=45),
    t2_2=Image(path, type_, age=46),
)
```

Replacing the `path` and `type_` variables, of course.

**Comment by hadhoryth** [comment]
@fepegar  Thank you, for so fast reply!

I have series of brain MRI images taken at different time. I'm trying to have `[subj1, subj2]` where each `subj` have multiple images. For example, `subj1` has T1 MRI at age 45 and 46 and so on. 
In the code I'm trying to do something like that:

> for patient in patients:
    subj = Subject(t1=Image(path, type_, age=45)
    for visit in visits:
         # Here I want to append another MRI's to this subject

**Comment by fepegar** [comment]
Would this work for you?

```python
for patient in patients:
    subject_dict = {'t1': Image(patient.image_path, torchio.INTENSITY, age=45)}
    for visit in visits:
        visit_id = get_visit_id_from_visit(visit)  # defined somewhere
        subject_dict[visit_id] = Image(visit.image_path, torchio.INTENSITY, age=visit.age)
    subject = Subject(subject_dict)
```

**Comment by hadhoryth** [comment]
Yes, I tried, and it works! Thank you!

```python
all_subjects = [Subject(Keys: ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'); images: 12), Subject(Keys: ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'); images: 17)]
````

Maybe you can give me the last hint. How can I inference from such a dataset? 
What I'm trying to do:
```python
dset = ImagesDataset(all_subjects) # created based on your answer.
patches_queue = torchio.Queue(subjects_dataset=dset, max_length=300, samples_per_volume=2, patch_size=16,
                                sampler_class=torchio.sampler.ImageSampler, num_workers=4, shuffle_subjects=True,
                                shuffle_patches=True)
patches_loader = DataLoader(patches_queue, batch_size=4)
num_epochs = 20
for epoch_index in range(num_epochs):
    for patches_batch in patches_loader:
        print(patches_batch)
```
but I recieve an error:
```python
File "/virtenvs/global/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/virtenvs/global/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/virtenvs/global/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/virtenvs/global/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/virtenvs/global/lib/python3.6/site-packages/torchio/data/queue.py", line 99, in __getitem__
    self.fill()
RuntimeError: received 0 items of ancdata
```

**Comment by fepegar** [comment]
You don't mean a queue for inference. Do you mean for training?

That error seems to be unrelated to TorchIO: https://discuss.pytorch.org/t/runtimeerror-received-0-items-of-ancdata/4999/4.

**Comment by hadhoryth** [comment]
Yes, you right.
Fernando, thank you for your help!

**Comment by fepegar** [comment]
No worries!
