### ISSUE TITLE
ImportError: cannot import name 'Compose'

### ISSUE THREAD

**Issue by hikmet-demir** [fepegar/torchio#136]
**TorchIO version**
'0.15.5'
<--! Can be retrieved as `torchio.__version__` -->

I'm just trying to load imports work and my code snippet is
`import torchio
from torchio import AFFINE, DATA, PATH, TYPE, STEM
from torchio.transforms import (
    RandomFlip,
    RandomAffine,
    RandomElasticDeformation,
    RandomNoise,
    RandomMotion,
    RandomBiasField,
    RescaleIntensity,
    Resample,
    ToCanonical,
    ZNormalization,
    CropOrPad,
    HistogramStandardization,
    Compose,
    OneOf,
)` 

When I try to run it, I get 
`Traceback (most recent call last):
  File "trial.py", line 3, in <module>
    from torchio.transforms import (
ImportError: cannot import name 'Compose'`

I think there is a problem with naming or function naming it's not working, also OneOf gives the same error

**Comment by hikmet-demir** [comment]
I suspect there is conflict with torchvision but not sure

**Comment by fepegar** [comment]
Can you upgrade `torchio` and try again? I think `Compose` was added in `0.16.0` and you're using `0.15.5`.

```bash
pip install --upgrade torchio
```

**Comment by hikmet-demir** [comment]
Now it works! Thank you @fepegar . Great work btw with the repo keep it up! superb software engineering and documentation compared to other scientific repos

**Comment by fepegar** [comment]
Thank you very much :)
