### ISSUE TITLE
Tensor Support for Transforms

### ISSUE THREAD

**Issue by MonsieurWave** [fepegar/torchio#137]
Hi, your library looks awesome, but as I have already implemented my own dataset class which does not respect the torchio ImagesDataset structure, I can not easily use the transforms you implemented on my data. It would be amazing if they could be simply used on pytorch tensors as well.  

In brief: applying torchio transforms and augmentation to a pytorch tensor
If I understood your code correctly, this would mainly involve rewriting the ```apply_transform``` of each transform class

Is this something you had in mind?

**Comment by fepegar** [comment]
I hadn't thought of doing this, but I'm open to suggestions. Which transforms are you interested in? Don't you care about image spacing, orientation, etc.? Could one assume that the matrix to go from voxel indices to physical space is an identity for all your images?

**Comment by MonsieurWave** [comment]
I am mostly interested in the RandomAffine, RandomElastic and RandomGhosting and just as you suggested the voxel index to physical space is an identity for all my images which is why I dropped the affines in my dataset.

**Comment by fepegar** [comment]
I suppose you don't want to save the images to disk and use TorchIO normally, is that right? What does your dataset look like? Can't it inherit from a `torchio.ImagesDataset`?

**Comment by MonsieurWave** [comment]
My dataset is composed of medical images with a lot of channels (shape: n_samples, n_x, n_y, n_z, n_channels)
- unfortunately the dataset class structure has already gotten quite complex so rewriting it to inherit from ``` torchio.ImagesDataset```would be quite a hassle
- I can imagine that a lot of other people are dealing with a similar problem, as there seems to be no other good 3D augmentation library out there that is implemented for pytorch tensors

**Comment by fepegar** [comment]
Sorry if I ask many questions, I need to understand the details to try to figure out a solution.

> My dataset is composed of medical images with a lot of channels (shape: n_samples, n_x, n_y, n_z, n_channels)

Is this the output of a `DataLoader`? If not, I don't understand why you have a `n_samples` dimension.

Do you want to apply the same transform to all channels? Are we talking about dMRI?

**Comment by MonsieurWave** [comment]
no worries, I appreciate your responsiveness
- I am actually mistaken, at the moment where transform is called, n_samples is always 1, so there is no real n_samples dimension, so it's just (n_x, n_y, n_z, n_channels) 
- the dataset is is fed to the ```DataLoader``` afterwards
- The same transformation would have to be applied to all the channels (in most cases I am working with perfusion CT data)

**Comment by MonsieurWave** [comment]
I quickly implemented this for some of the augmentation functions (ElasticTransform, Affine, Flip and noise), not totally clean but it works:
https://github.com/MonsieurWave/torchio/commit/9eb30c0a214ee8ee229a8e1862a9a9395ea264a3

**Comment by fepegar** [comment]
> For multi channel support, it simply loops through the channels and applies the same transformation (I could not find if SITK supports this natively)

I haven't looked very deeply into this, but your approach seems to be the best: https://github.com/fepegar/torchio/issues/16#issuecomment-576949538

Refactoring all transforms to work with tensors seems doable, but it'll take some work. I'll open a PR.

**Comment by fepegar** [comment]
Actually, I think this might be quickly solved by modifying only one class. I'll give it a try.

**Comment by MonsieurWave** [comment]
True, that could actually work and wouldn't be too much work to implement.

**Comment by fepegar** [comment]
Can you checkout the branch and see if that'd work for you?

**Comment by MonsieurWave** [comment]
Did a quick test run on some of my data and there seems to be an issue with the shape of data accepted. The 'transformer' neither accepts 4dims tensor (c, x, y, z), nor 5dim (i, c, x, y, z). 
I tried to replicate the issue:
`
In [33]: sample_input = torch.ones((4,30,30,30))                                                                                                                                                            

In [34]: rflip = RandomFlip()                                                                                                                                                                               

In [35]: trans_sample_input = rflip(sample_input)                                                                                                                                                           
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-b2f13d931832> in <module>
----> 1 trans_sample_input = rflip(sample_input)

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/transforms/augmentation/random_transform.py in __call__(self, sample)
     31     def __call__(self, sample: Subject):
     32         self.check_seed()
---> 33         return super().__call__(sample)
     34 
     35     @staticmethod

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/transforms/transform.py in __call__(self, data)
     43         """
     44         if isinstance(data, torch.Tensor):
---> 45             sample = self.parse_tensor(data)
     46         else:
     47             sample = data

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/transforms/transform.py in parse_tensor(self, tensor)
     85             )
     86             raise RuntimeError(message)
---> 87         return self._get_subject_from_tensor(tensor)
     88 
     89     @staticmethod

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/transforms/transform.py in _get_subject_from_tensor(tensor)
     92         for channel_index, channel_tensor in enumerate(tensor):
     93             name = f'channel_{channel_index}'
---> 94             image = Image(tensor=channel_tensor, type=INTENSITY)
     95             subject_dict[name] = image
     96         subject = Subject(subject_dict)

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/data/image.py in __init__(self, path, type, tensor, affine, **kwargs)
     46                 message = 'If a path is given, tensor and affine must be None'
     47                 raise ValueError(message)
---> 48         self.tensor = self.parse_tensor(tensor)
     49         self.affine = self.parse_affine(affine)
     50         if self.affine is None:

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/data/image.py in parse_tensor(tensor)
     82                 f' but has only {num_dimensions}: {tensor.shape}'
     83             )
---> 84             raise RuntimeError(message)
     85         return tensor
     86 

RuntimeError: The input tensor must have 4 dimensions (channels, i, j, k), but has only 3: torch.Size([30, 30, 30])

In [36]: sample_input = torch.ones((1, 4,30,30,30))                                                                                                                                                         

In [37]: rflip = RandomFlip()                                                                                                                                                                               

In [38]: trans_sample_input = rflip(sample_input)                                                                                                                                                           
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-b2f13d931832> in <module>
----> 1 trans_sample_input = rflip(sample_input)

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/transforms/augmentation/random_transform.py in __call__(self, sample)
     31     def __call__(self, sample: Subject):
     32         self.check_seed()
---> 33         return super().__call__(sample)
     34 
     35     @staticmethod

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/transforms/transform.py in __call__(self, data)
     43         """
     44         if isinstance(data, torch.Tensor):
---> 45             sample = self.parse_tensor(data)
     46         else:
     47             sample = data

~/opt/anaconda3/envs/tiotensors/lib/python3.8/site-packages/torchio/transforms/transform.py in parse_tensor(self, tensor)
     84                 f' but has only {num_dimensions}: {tensor.shape}'
     85             )
---> 86             raise RuntimeError(message)
     87         return self._get_subject_from_tensor(tensor)
     88 

RuntimeError: The input tensor must have 4 dimensions (channels, i, j, k), but has only 5: torch.Size([1, 4, 30, 30, 30])
`

**Comment by fepegar** [comment]
Should be fixed now. Let's continue the discussion in the PR please: #139
