### ISSUE TITLE
About training a classifier with TorchIO

### ISSUE THREAD

**Issue by hikmet-demir** [fepegar/torchio#138]
**TorchIO version**
0.16.4

This question can sound a bit silly sorry for it. How do I train a classifier with torchio exactly? I know it sounds weird but here me out.

I have Clean lung CT scans and infected lung CT scans. I would like to train 3D CNN on them for classification basically with torchio pipeline. I wrote the subject list class and created ImageDataset object it's all ready. I also have my rough CNN architecture but I couldn't find to where to feed labels into training ( scan is infected or not infected), you are feeding labels as mri and brain which I didn't understand exactly in this context. What is label in the example colab? and how can I feed the real labels(infected or not infected)?

I suspect we can feed it when we create subjects

`        subject_dict = {
            SCAN : torchio.Image(dir_path, torchio.INTENSITY),
            MASK : torchio.Image(str(Path(lblPath, relativePath)), torchio.LABEL),
            infected: True 
        }
`
something like this with a key in subject_dict ?

**Comment by hikmet-demir** [comment]
Sorry for labeling it as bug, should be something else

**Comment by fepegar** [comment]
Hey @hikmet-demir,

There's no such thing as a silly question.

The task in the notebook is segmentation, i.e. voxel-wise classification. The label is an image in which all voxels corresponding to the brain are 1 and the rest are 0, probably similar to your `MASK`.

Your snippet is correct (assuming you have defined the values of `SCAN`, `MASK` and `infected`. You don't need to convert the `Path` to `str`.

There are more examples in the docs for [`Subject`](https://torchio.readthedocs.io/data/dataset.html#subject).

**Comment by hikmet-demir** [comment]
Hey @fepegar,

Thank you for clarifying out, 

`SCAN` is the raw CT scans basically
`Mask` is the mask that I created somewhere else for each scan, basically same 3d structure filled with 1 or 0's, ( I'm extracting lungs with segmentation)

`infected` will be 0 or 1 depending on scan and I will feed infected data as label to torch in the training rerunning the subjects right now!

**Comment by fepegar** [comment]
Shall we mark this as resolved?

**Comment by hikmet-demir** [comment]
sure!
