### ISSUE TITLE
Add an option to shuffle the queue after filling it

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#14]

**Comment by romainVala** [comment]
Well very easy to do : one just need to add

            shuffle(self.patches_list)

at the end of the fill method. currently shuffle_dataset is only shuffeling the dataset, should we use an other parameter to decide wether or not to shuffle the patches within the queue ?

**Comment by fepegar** [comment]
I know it's very simple, I just haven't had time for it :)
I think it's nice to use a new parameter for it, yes. I'd say we rename `shuffle_dataset` to `shuffle_subjects` and we add a new `shuffle_queue`, which is `True` by default.

**Comment by romainVala** [comment]
sound goods, 
may be shuffle_patches
(to stay in line with shuffle_subjects)

**Comment by fepegar** [comment]
Good idea.
