### ISSUE TITLE
Pass random parameters to apply_transform()

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#142]
Hi
Your do save the used coarse_grid in history of the transform, but you also should add num_control_points  (to have a complete description, and the possibility to reproduce it)

Just as a side note (not sure you are interested to it) I implement, apply_given_transform where you set the transform explicitly (to reproduce, the one applied, and saved in history )

Many thanks

**Comment by fepegar** [comment]
Hi @romainVala,

> Your do save the used coarse_grid in history of the transform, but you also should add num_control_points (to have a complete description, and the possibility to reproduce it)

The number of control points is the shape of the coarse grid:
https://github.com/fepegar/torchio/blob/90516ebb54b7edab52299d717191134c2bf15a9e/torchio/transforms/augmentation/spatial/random_elastic_deformation.py#L165-L172

> Just as a side note (not sure you are interested to it) I implement, apply_given_transform where you set the transform explicitly (to reproduce, the one applied, and saved in history )

Yes! I've always thought this would be good for reproducibility, but then forget to implement it. Do you have a link so that I can take a look?

**Comment by romainVala** [comment]
Ok, great, then it is not needed

Well I did it very simply, I just copy the apply_transform, and add an argument

    def apply_given_transform(self, sample: Subject, bspline_params) -> dict:
        for image_dict in sample.get_images(intensity_only=False):
            if image_dict[TYPE] == LABEL:
                interpolation = Interpolation.NEAREST
            else:
                interpolation = self.interpolation
            image_dict[DATA] = self.apply_bspline_transform(
                image_dict[DATA],
                image_dict[AFFINE],
                bspline_params,
                interpolation,
            )
        return sample

and then I call this specific function

but I things It would be better, to stay with apply_transform, and just add an extra argument bspline_params to the constructor, and then in the init function to do something like

if bspline_params is not None:
      self.bspline_params = bspline_params
else:
        self.bspline_params = self.get_params(
            self.num_control_points,
            self.max_displacement,
            self.num_locked_borders,
        )

and then change the apply_transform to directly useself.bspline_params  (instead of the get_params call)
