### ISSUE TITLE
2D Tensor Support

### ISSUE THREAD

**Issue by jillianlee** [fepegar/torchio#143]
The transforms in your package are incredibly useful and unique, but for my project I need to apply them on 2D images.

I can likely develop a work-around using the 3D transforms, however I saw on issue #22 and issue #53 that you have previously discussed implementing 2D image support and have since closed these issues. Despite these issues being marked resolved, when using the transforms with the tensor support method (as outlined in #139 ), I get the following error:

`RuntimeError: The input tensor must have 4 dimensions (channels, i, j, k), but has 3: torch.Size([1, 120, 384])`

This was from trying to feed a tensor with shape (channels, i, j). This error makes it seem like the transforms are still only for 3D inputs? I have tried this with a variety of the transforms and get the same results. 

Is there a method I'm missing for applying your transforms with 2D images? Thanks so much in advance for any help you can offer.

**Comment by fepegar** [comment]
Hi @jillianlee,

Which transforms would you like to use?

I'm not planning to add 2D support, for now. I think there are other wonderful libraries that can be used for that, such as `albumentations`, `imgaug` or `augmentor`.

**Comment by jillianlee** [comment]
Ah, I see. Thank you for the clarification, I was just a bit confused given the previous issues.

I was most interested in the bias field, motion, and ghosting artifacts. Thank you for referring me to these packages though!

**Comment by fepegar** [comment]
No worries! I'll consider adding 2D support for those in the future.

**Comment by fepegar** [comment]
Hey @jillianlee,

I'm doing some testing. `RandomBiasField` seems to work fine in 2D. This is what I tried:

```python
import torch
import torchio
slice = nib.load('slice.nii.gz').get_data()  # shape: (176, 206)
tensor = torch.from_numpy(slice)[None, None]  # shape: (1, 1, 176, 206)
transform = torchio.RandomBiasField()
transformed = transform(tensor)
```

This is what they look like:
<img width="635" alt="Screen Shot 2020-05-23 at 08 06 13" src="https://user-images.githubusercontent.com/12688084/82724201-587bef00-9ccc-11ea-925e-6e1793bf89b8.png">


I'll check the rest.

**Comment by fepegar** [comment]
Random motion:

<img width="609" alt="Screen Shot 2020-05-23 at 08 37 39" src="https://user-images.githubusercontent.com/12688084/82724831-b9a5c180-9cd0-11ea-9ba3-57f0431feb5c.png">

**Comment by fepegar** [comment]
Random spikes:

<img width="564" alt="Screen Shot 2020-05-23 at 08 52 51" src="https://user-images.githubusercontent.com/12688084/82725143-d7742600-9cd2-11ea-863e-9653ab1a38ab.png">

**Comment by fepegar** [comment]
Random ghosting:

<img width="567" alt="Screen Shot 2020-05-23 at 09 02 20" src="https://user-images.githubusercontent.com/12688084/82725331-2cfd0280-9cd4-11ea-82d6-c32d3ae905ac.png">

**Comment by fepegar** [comment]
Would those work for you? Would you like 2D support for other transforms? Adapting the library for this seems easier than I thought it'd be.

**Comment by jillianlee** [comment]
These all work perfectly for me! Thank you so much!

I don't need any more transforms for 2D, but thank you though. This helps a lot, I really appreciate your work!

**Comment by fepegar** [comment]
That's great, let me know if you run into any issues!

**Comment by Chao86** [comment]
> Random motion:
> 
> <img alt="Screen Shot 2020-05-23 at 08 37 39" width="609" src="https://user-images.githubusercontent.com/12688084/82724831-b9a5c180-9cd0-11ea-9ba3-57f0431feb5c.png">

hi， @fepegar 
I use the  motion transform in 2D image and 3D image, the result make it seem like the motion transform dosen't work in 2D image. My code and result as follow:
`
image_info =sitk.ReadImage('/home/heng_cao/Project/UCSR_ROI/single_slice/124_801_t1_uCSR_tra_fs_p5_P_16.mhd')  #shape Z*Y*X：1*384*384
image = sitk.GetArrayFromImage(image_info)
image_nor = np.expand_dims(image, axis=-1)
image = np.tile(image_nor, (1,1,1,1)) #shape C*Z*Y*X：1*384*384*1

all_image_info =sitk.ReadImage('/home/heng_cao/Project/UCSR_ROI/mhd_data/124_801_t1_uCSR_tra_fs_p5_P.mhd')  #shape Z*Y*X：53*384*384 
all_image = sitk.GetArrayFromImage(all_image_info)
all_image = np.expand_dims(all_image, axis=0) 
all_image=all_image.transpose(0,2,3,1) #shape C*Z*Y*X：1*384*384*53

spatial_transforms={tio.RandomMotion(degrees=(-2,2), translation=(-10,10),num_transforms=5):1.0,}
transform=tio.Compose([tio.OneOf(spatial_transforms,p=1.0)])

transformed_image=transform(img1)
transformed_images=transform(all_image)

fig, axes=plt.subplots(2,2,figsize=(7, 7))
axes[0][0].imshow(image[0,:,:,0], 'gray')
axes[0][1].imshow(transformed_image[0,:,:,0],'gray')
axes[1][0].imshow(all_image[0,:,:,16],'gray')
axes[1][1].imshow(transformed_images.data[0,:,:,16],'gray')`

Plot result:
![motion](https://user-images.githubusercontent.com/44365146/131804233-89e5d212-bbed-4166-8679-93784b84b2e1.png)
Can you help me how to apply correctly the motion  transform in 2D images?

**Comment by Chao86** [comment]
> @romainVala has already replied to you in [#643 (comment)](https://github.com/fepegar/torchio/discussions/643#discussioncomment-1270113), please don't post the same here, in a closed issue. If you find something is not working as you expected, you can open a new issue and follow the instructions: https://github.com/fepegar/torchio/issues/new?assignees=&labels=&template=not_working.md&title=

Sorry , I will refresh to  browse the  coomment [https://github.com/fepegar/torchio/discussions/643#discussioncomment-1270113](url). Thank you for reminding me!
