### ISSUE TITLE
Apply affine transform to all images simultaneously

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#16]

**Comment by edgarriba** [comment]
hi @fepegar nice project! For such feature you could implement kornia since we already have an interface for a batch and differentiable affine transform

**Comment by fepegar** [comment]
Hi @edgarriba, thanks! [`kornia`](https://github.com/kornia/kornia) looks great, but I don't think a differentiable operation is needed here. I was rather thinking about using SimpleITK to create a multimodal/vector image and [resample](https://itk.org/ITKExamples/src/Filtering/ImageGrid/ResampleAVectorImage/Documentation.html) it in one go.

**Comment by edgarriba** [comment]
I see. In case you plan to implement other backends other than SimpleITK just let us know. Would love to see kornia as part of a medical image analysis framework like yours. I guess you might also have differentiable stuff in mind that could be interesting for both frameworks.

**Comment by fepegar** [comment]
I'll keep that in mind!

**Comment by fepegar** [comment]
This doesn't look like a good idea (with `SimpleITK`):

```python
In [28]: composed = sitk.Compose((im1, im3, im4, im1))

In [29]: %timeit sitk.Resample(composed, tr)
1.07 s ± 46.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [30]: %timeit [sitk.Resample(im) for im in (im1, im3, im4, im1)]
408 ms ± 30.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
