### ISSUE TITLE
Custom transformations applied to LABEL type

### ISSUE THREAD

**Issue by marcfi** [fepegar/torchio#161]
Hi @fepegar, thanks for this great tool! I've used it today for the first time, and (almost) all functionality worked as intended.

I've stumbled upon a little problem with regard to custom transformations using `torchio.transforms.Lambda`. When using the function as shown in the docs example, e.g.
`new_mask = Lambda(my_func, types_to_apply=[torchio.LABEL])`
the function is never called for `torchio.LABEL`. With `torchio.INTENSITY` it works fine.

A look at the implementation (torchio/transforms/lambda_transform.py) showed that `Lambda.apply_transfom()` goes through images via `sample.get_images()`. However, `get_images()` has a default flag `intensity_only=True`. As such, only torchio.INTENSITY can be retrieved, making the option `types_to_apply` obsolete.

Is this intended behaviour? Thanks for looking into it!

**Comment by fepegar** [comment]
Hi @marcfi, thanks for the kind words. You're absolutely right! Would you like to contribute with a PR adding `intensity_only=False` in the `Lambda` transforms?
