### ISSUE TITLE
How do you load additional information regarding an image?

### ISSUE THREAD

**Issue by danieltudosiu** [fepegar/torchio#165]
I am working with Torch.io version 0.13.9 and I am trying to follow [the example from the docs](https://torchio.readthedocs.io/data/dataset.html#torchio.data.Subject) and it complains that all elements of the dictionary must be instances of torchio.Image what could it be?

**Comment by fepegar** [comment]
Hi Dan. Can you please try with the latest version?

**Comment by fepegar** [comment]
I believe that was added in version `0.14.3`.

**Comment by fepegar** [comment]
Closing as @danieltudosiu says it did work.
