### ISSUE TITLE
Is there any example for a classification task ?

### ISSUE THREAD

**Issue by farazahmeds** [fepegar/torchio#166]
The `subject` class uses `image.nii.gz` and `segmentedimage.nii.gz` for segmentation task but since I want to work with classification, how do I assign `class label` to an  `image.nii.gz`  instead of `segmentedimage.nii.gz`?

Thanks.

**Comment by fepegar** [comment]
Hi @farazahmeds,

You can assign any kwargs to `torchio.Subject` and `torchio.Image`:

```python
subject = torchio.Subject(
    t1_young=Image('t1_1989.nii', my_label=19),
    t1_old=Image('t1_1999.nii', my_other_label=29),
    lives_in='New York',
)
```

You can retrieve those attributes when sampling from the dataset.

```python
dataset = torchio.ImagesDataset([subject])
sample = dataset[0]
sample['lives_in']  # 'New York'
sample['t1_young']['my_label']  # 19
```

**Comment by fepegar** [comment]
Does that work for you?

**Comment by farazahmeds** [comment]
> Does that work for you?

Thankyou so much, I got it all working. 

I have to say you've done a great job, everything is very much stream lined and well documented.

**Comment by fepegar** [comment]
Thank you @farazahmeds :)
