### ISSUE TITLE
interpolation to make volume depth between volumes equal when loading batches

### ISSUE THREAD

**Issue by farazahmeds** [fepegar/torchio#170]
My apologies in advance if it doesn't belong here.

I want to use batch size >1 and load entire volumes, but there is difference in `number_of_slices` between volumes

for example:
shape [batch_size, channels, depth, height, width]

```
shape (1, 1, 50, 256, 256)
shape (1, 1, 51, 256, 256)
shape (1, 1, 50, 256, 256)
shape (1, 1, 49, 256, 256)
```

Do you have any advice for me on how do I add interpolation step/what kind of interpolation should suffice (to make depth equal) in the loading pipeline ?

**Comment by romainVala** [comment]
Hello
having the same matrix since is needed for batch >1 (but also for model where the input size matter)
the easiest way is to use CropOrPad transform (that will add a slice with 0 if missing or remove a slice if too much)

CropOrPad(target_shape=(50,256,256))

**Comment by fepegar** [comment]
@farazahmeds Your question does belong here.

As @romainVala said, `CropOrPad` should do. Feel free to reopen the issue if it doesn't.
