### ISSUE TITLE
add translation in RandomAffine

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#171]
**🚀 Feature**
RandomAffin is only perfoming scaling and rotation, why not also small translation ?

**Motivation**

since we want to augment (in order to simulation bad coregistration between subject ... I guess) I think it will be more general to also add translation

I also notice that rotations, and scalling are done relative to the volume origine, which make those transform very specific ... Adding translation first, will simulate a more wide spread of affine 

**Pitch**
order of "sub-affine" like scaling, rotation translation is important, I suggest to try this order:
translation scalling and rotations ..

**Alternatives**

**Additional context**

**Comment by fepegar** [comment]
Hey @romainVala,

I haven't added translation because it's usually not helpful for classification or segmentation. I agree that it would be useful for registration, though.

Rotations should be applied around the center. I've been experimenting with [this Slicer module](https://github.com/fepegar/SlicerTorchIO) and it looks fine. Also, I think that should be part of a different issue.

**Comment by romainVala** [comment]
yes for segmentation with patch based, it is logical, but for classification (or regression) from full brain I am not sure (are you ?) 

About rotation center, It is around the point 0,0,0 define by the nifty affine right ? 
If yes, it may be dangerous for certain nifty header .(I did not checked ... )
a more safer option is to take the center from the voxel matrix, it could be an other default no ?

I wonder if it may be useful to allow different rotation center. But ok, it could be an other issue later. (it is related because : my understanding is that adding translation is equivalent to change the rotation center)

An other by side comment as curiosity: why not using nibabel resample, instead of sitk ?

**Comment by fepegar** [comment]
> yes for segmentation with patch based, it is logical, but for classification (or regression) from full brain I am not sure (are you ?)

I don't want to get into that, [talk to this guy](https://richzhang.github.io/antialiased-cnns/) 😄 

> About rotation center, It is around the point 0,0,0 define by the nifty affine right ?
If yes, it may be dangerous for certain nifty header .(I did not checked ... )
a more safer option is to take the center from the voxel matrix, it could be an other default no ?

As far as I know, currently, rotations are around the center of the matrix in world coordinates, not the origin.

> I wonder if it may be useful to allow different rotation center. But ok, it could be an other issue later. (it is related because : my understanding is that adding translation is equivalent to change the rotation center)

Yes, different issue! And I don't understand how those are equivalent.

> An other by side comment as curiosity: why not using nibabel resample, instead of sitk ?

I'm just more familiar with sitk resampling. I think it's very generic. At some point I would like to unify `RandomAffine`, `RandomElasticDeformation` and `Resample`. That way, a single interpolation is performed. But that's another issue :)

**Comment by romainVala** [comment]
> I don't want to get into that, [talk to this guy](https://richzhang.github.io/antialiased-cnns/) smile

very nice work, indeed !   But it is the opposite of what you just say : CNN is very sensible to translation, unless you take the correct architecture ! 
I do also experiment a great sensibility in spatial deformation, that is why I am digging into (realistic) data augmentation but I am impatient to give a try to his downsampling strategy (i hope it can be used in 3D too)


> As far as I know, currently, rotations are around the center of the matrix in world coordinates, not the origin.

Well, a "matrix in world coordinates" is a bit confusing: a matrix is a matrix whether it is in world coordinate... The question is whether it is relative to the matrix (center, or any voxel point i,j,k) or to a point in world coordinates (origin, or any mm point x,y,z).
I just check, and I deduce :  the rotation is relative to the world coordinates origin:
To test I took a volume and manually change the affine translation in the header affine. The first row show the focus at 0,0,0 mm position, and the second row is when I apply the same rotation (10°). The first column is the original image in mni space and the second is where I change the nifty affine translation (-30 mm)

![rotation_dependance_on_affine](https://user-images.githubusercontent.com/5611962/83231635-1818e700-a18c-11ea-866d-d44f260be52c.png)

Note that this is why sitk needs the nifti affine, If it was a rotation define in the "voxel (==matrix) space" then no affine would be needed, and the rotation will be the same whatever the nifti affine is. To change this, you need to pass to sitk a affine where the origin is at the center of the matrix ... 
but I think it should be an option and may be the default, because this is what happen if the nifti affine origine is further away :
 
![Screenshot from 2020-05-29 09-32-38](https://user-images.githubusercontent.com/5611962/83233659-5532a880-a18f-11ea-8cad-ec63f0373018.png)


> Yes, different issue! And I don't understand how those are equivalent.

because changing the rotation center is equivalent to a system coordinate change : xnew=(x-x0) so from the pure rotation matrix R, you have R*(x-x0) = A*x , where A is the affine with the same rotation matrix and a translation term -R*x0 


> I'm just more familiar with sitk resampling. I think it's very generic. At some point I would like to unify `RandomAffine`, `RandomElasticDeformation` and `Resample`. That way, a single interpolation is performed. But that's another issue :)

that would be a nice feature, important indeed to avoid to much blurring, but may be difficult to implement when arbitrary independent transform are used.

**Comment by fepegar** [comment]
> very nice work, indeed !   But it is the opposite of what you just say : CNN is very sensible to translation, unless you take the correct architecture ! 

Yes! I guess I meant in general people think that CNNs are "translation invariant", but obviously it depends a bit on the downsampling strategy.

> I do also experiment a great sensibility in spatial deformation, that is why I am digging into (realistic) data augmentation but I am impatient to give a try to his downsampling strategy (i hope it can be used in 3D too)

I once looked for a 3D implementation and couldn't find it. Let me know if you do!

> Well, a "matrix in world coordinates" is a bit confusing: a matrix is a matrix whether it is in world coordinate... 

Sorry, I meant the center of the image.

> this is what happen if the nifti affine origine is further away :
 
You're absolutely right! I didn't appreciate it with the two images I tried because the origin was very close to the image center in both images. I just tried setting the origin very far and the image moves a lot. I think this is easy to modify, I'll try today.
