### ISSUE TITLE
PyTorch CONV3D takes different Shape input than what Dataloader returns

### ISSUE THREAD

**Issue by kahn12345** [fepegar/torchio#176]
I am using TorchIO but my dataloader returns the shape:  ` torch.size([1, 1, 256, 256, 50])`   
I'm assuming it's following the order `(batchsize, channel, height, width, depth)`

while the The CONV3D takes in different order [Pytorch Documentation ](https://pytorch.org/docs/master/generated/torch.nn.Conv3d.html)  

`(batchsize, channel, depth, height, width)`

Since I am new to TorchIO, I am not sure if I need to correct the shape arrangement to be fed to CONV3D or TorchIO natively inputs the correct shape arrangement?
 
If I have to change the shape, is there any quick transformation I could apply?

Thankyou

**Comment by fepegar** [comment]
Hi @kahn12345,

That should work. Why do you assume `B, C, H, W, D`? Anyway these names don't really make sense for 3D medical images. I just use them in the docs to follow PyTorch syntax. The important thing to know is that PyTorch doesn't permute any dimensions internally, so what you get is the original images shape.

In medical images, the name of each dimension would depemd on the image orientation (for example RAS or LPS). I might add support for named tensors in the future.

Let me.know if that's not clear.

**Comment by kahn12345** [comment]
_Why do you assume `B, C, H, W, D`?_ 

The dataset I am using contains 256x256 slice resolution with 50 slices per volume,greyscale, with batchsize=1  I assumed the shape `B,C,H,W,D` .

So the last time I was working with non-medical images, 2D Images, I was following the representation `[batch_size, channels, height, width]` during training since in my model, `nn.Conv2D()` takes in the input takes 4D Tensor with dimensions `[batch_size, channels, height, width]`

I thought the same idea would extrapolate to medical images, with model using `nn.Conv3D`, I would use 5D Tensor with dimensions `[batch_size, channels, height, width, depth]` as input.

My confusion is with the `Conv3D` layer taking in shape `(batchsize, channel, height, width, depth)` as input when it should be taking `(batchsize, channel, depth, height, width)` as input during training. 

_In medical images, the name of each dimension would depemd on the image orientation (for example RAS or LPS). I might add support for named tensors in the future._

Thanks, I did not know that, I am very new to medical Images therefore the confusion.

Again thankyou for your time!

**Comment by fepegar** [comment]
I suggest you ignore the concepts of depth, width and height for medical images and start thinking in 3D and anatomical axes.

Here are some links about medical images that I've always found very useful:
https://nipy.org/nibabel/nifti_images.html
https://nipy.org/nibabel/coordinate_systems.html
https://nipy.org/nibabel/image_orientation.html
https://www.slicer.org/wiki/Coordinate_systems
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Orientation%20Explained

I've just added an `orientation` property to `Image` (in https://github.com/fepegar/torchio/commit/f28e4c99298297b2fad0ce58ad8de3b5c5802642) that might help us here.

```python
In [1]: import torchio
   ...: subject = torchio.datasets.Colin27()
   ...: sample = torchio.ImagesDataset([subject])[0]
   ...: sample.t1.orientation
Out[1]: ('R', 'A', 'S')
```

In this image, first dimension goes from left to right, second goes from posterior (back of the head) to anterior (face), and third goes from inferior (feet) to superior (head).

```python
In [2]: import torchio
   ...: subject = torchio.datasets.SubjectSlicer()
   ...: sample = torchio.ImagesDataset([subject])[0]
   ...: sample.MRHead.orientation
Out[2]: ('P', 'I', 'R')
```

This image is totally different, as you can see. 

Let me know if my examples and those links help!
