### ISSUE TITLE
Specify axes with anatomical labels

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#185]
**🚀 Feature**

Add support to pass anatomical labels instead of axes numbers.

**Motivation**

It would be nice to be able to specify axes with anatomical labels such as L, R or A, instead of 0, 1 and 2. The numbers could be inferred from the orientation in the image header. That way, the user wouldn't need to know how the image is oriented when choosing the axes for a transform such as `RandomFlip`.

**Comment by romainVala** [comment]
is there other transform that will use it ?

**Comment by fepegar** [comment]
Yes, `RandomGhosting`.
