### ISSUE TITLE
Understanding Torchio.LABEL vs Torchio.INTENSITY

### ISSUE THREAD

**Issue by hikmet-demir** [fepegar/torchio#189]
Hi,
I'm trying to understand and select which one of them to use, I couldn't see clear description of them so here we are.

my transformation are very basic for now
`#TRANSFORMATIONS on Traning
training_transform = Compose([
    Resample((2, 2, 2)),
    RescaleIntensity(
        out_min_max = (0,1),
        percentiles = (0.5,99.5)
    )
])`

RescaleIntensity transformation happens when I choose torchio.INTENSITY. Did you described or written out which transformation happen for which ( INTENSITY or LABEL)? If not written out it would be super nice to write it out to wiki. It can be confusing

**Comment by fepegar** [comment]
Hey @hikmet-demir,

You're right that the docs are not very explicit about it. I'll work on that. The docs for `Image` describe this a bit: https://torchio.readthedocs.io/data/dataset.html#image
