### ISSUE TITLE
transform history : save the original order

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#190]
**🚀 Feature**
It would be nice to have a way to store the transform's order in the history

**Motivation**
I thought that the list order in the history struct one get from Subject would reflect the transform order, but it seems not to be the casee (the list order seems not to be consistent ...)
**Pitch**

Not sure if it is the best way, but I can imagine a field number of transform in the history, which contains the total number of transforms, and a extra field withing the transform dict which specify the order 
You then just have to assign number_of_transform +1 and take it as value for the order 

**Alternatives**

fixed the list order, so that it keept the same order as the transform order

**Comment by fepegar** [comment]
I'm surprised that the order is not kept, as the history is just a list:
https://github.com/fepegar/torchio/blob/0e8172c3253050fcbf309989b57cdf9e81a3cc6c/torchio/data/subject.py#L58

Do you have a snippet to reproduce this?

**Comment by romainVala** [comment]
may be I am wrong, I'll check a second time, and let you know

**Comment by romainVala** [comment]
ok sorry, it was my fault
(I was confused because of the use of oneOf so the index number was changing)
but you're right the transform order is correct,
great job 
++

**Comment by fepegar** [comment]
Ok, thanks @romainVala.
