### ISSUE TITLE
resizing the image instead of using CropOrPad? 

### ISSUE THREAD

**Issue by farazahmeds** [fepegar/torchio#193]
Quick question, Is it possible to to resize the image instead of using `CropOrPad` ? like `torchvision.transforms.Resize` transform ? I basically want to make use of interpolation methods to assign new target shape.

**Comment by fepegar** [comment]
Hi @farazahmeds,

I haven't implemented a `Resize` transform, but you can probably use `Resample` for this.

If your image has n1 = 100 voxels along a certain dimension with spacing s1 = 1.25 mm and you want it to have n2 = 75 voxels, you can compute a target spacing for that dimension and pass it to [`Resample`](https://torchio.readthedocs.io/transforms/preprocessing.html#resample), knowing that n1 * s1 = n2 * s2. In this case, s2 = (n1 * s1) / n2 = 1.67 mm., with any interpolation accepted by `Resample`.

Does that make sense?

**Comment by fepegar** [comment]
May I ask why you want to resize your images like this? I have never needed to do this with medical images.

**Comment by farazahmeds** [comment]
> May I ask why you want to resize your images like this? I have never needed to do this with medical images.

I didn't need it either, it was one of those things my supervisor wanted me to change for no obvious reasons. Rest assured I was doing well without Resize function.

Thanks for such a prompt reply.

**Comment by fepegar** [comment]
Ah, supervisors. They probably forgot the right vocabulary for such low-level operations.

Please let me know if that worked for you.

**Comment by farazahmeds** [comment]
@fepegar another quick question,  maybe I found the use case for sampling ? 

I was using BraTS and without `CropOrPad` transform my GPU was out of memory even with `batch_size=1`.

The issue is that the minimum amount of cropping (HxW) it took just to run (and not be out of memory) also cropped the brain part (see picture).

Do you think resampling would help in this case ?

**Comment by fepegar** [comment]
Yes, resampling would make your voxels larger by keeping the same physical size, so your image would have fewer voxels and therefore would use less memory. However, it's a lossy operation and you probably don't want that. How much memory do you have in your GPU?

Things you can try:
1. [Patch-based training](https://torchio.readthedocs.io/data/patch_based.html)
2. [Mixed precision](https://github.com/NVIDIA/apex)

P.S.: note you can drag and drop images into the GitHub comment and they'll be shown here.

**Comment by fepegar** [comment]
Resizing an image means resampling it, if you think about it. You're reducing the number of samples (pixels/voxels) while keeping the field of view by reducing the sampling rate (e.g. keeping every other voxel in an image). This is the equivalent of using resample and specify a larger target spacing than the original one.

In computer vision, you typically don't care about the pixel size because it doesn't really have a meaning in most cases. In medical images, however, there is inherent spatial information for each voxels and that needs to be taken into account when processing the images.

Maybe section 2 of the preprint will help you understand all these issues: [TorchIO: a Python library for efficient loading, preprocessing, augmentation and patch-based sampling of medical images in deep learning](https://arxiv.org/pdf/2003.04696.pdf).

**Comment by fepegar** [comment]
Here's a paper by @ReubenDo that used patch-based training successfully with Brats data (patches of size 112x112x112): [Hetero-Modal Variational Encoder-Decoder for Joint Modality Completion and Segmentation](https://link.springer.com/chapter/10.1007/978-3-030-32245-8_9).

**Comment by farazahmeds** [comment]
> Yes, resampling would make your voxels larger by keeping the same physical size, so your image would have fewer voxels and therefore would use less memory. However, it's a lossy operation and you probably don't want that. How much memory do you have in your GPU?
> 
> Things you can try:
> 
>     1. [Patch-based training](https://torchio.readthedocs.io/data/patch_based.html)
> 
>     2. [Mixed precision](https://github.com/NVIDIA/apex)
> 
> 
> P.S.: note you can drag and drop images into the GitHub comment and they'll be shown here.

I have total of  7.80 GB. Yea Patch-training makes sense here.

**Comment by farazahmeds** [comment]
Thanks for all the input mate, I will let know you know if the patch-based training worked. For now I'm closing the issue.

**Comment by fepegar** [comment]
No worries, good luck! I strongly suggest you try mixed precision, it's worked very well for me in the past.

**Comment by farazahmeds** [comment]
> No worries, good luck! I strongly suggest you try mixed precision, it's worked very well for me in the past.

I did not know it would be that easy!! I literally just replaced 3 lines, and memory usage is under. I have to read up on how it works, but I am sure amazed! 

I am not loosing any information now, I am up from 140x140x155 to 230x213x155  

:D

**Comment by fepegar** [comment]
Glad to hear that! But beware, you are actually losing a bit of information when using 2 bytes for your float variables in the convolutions instead of 4.

**Comment by farazahmeds** [comment]
> Glad to hear that! But beware, you are actually losing a bit of information when using 2 bytes for your float variables in the convolutions instead of 4.

ahh okay. I think it's still not as much of a compromise as using interpolation to scale down images. I think will talk with my supervisor and hopefully he'd agree with me on this one.
