### ISSUE TITLE
Is torch 1.2 still mandatory?

### ISSUE THREAD

**Issue by MonsieurWave** [fepegar/torchio#195]
IterableDataset seems to have been removed as of #175, therefore torch>=1.1 could be sufficient. 
This is in interest of many people still relying on CUDA 9.

https://github.com/fepegar/torchio/blob/0e8172c3253050fcbf309989b57cdf9e81a3cc6c/setup.py#L20

**Comment by fepegar** [comment]
You're absolutely right. Would you like to open a PR?

**Comment by MonsieurWave** [comment]
Here you go.
