### ISSUE TITLE
ZNormalization is slow

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#202]
`ZNormalization` is a very simple transform that should be very fast, but it's not.

Script:

```python
import time
import numpy as np
import torchio as tio
colin = tio.datasets.Colin27(version=2008)  # (362, 434, 362)
sample = tio.ImagesDataset([colin])[0]
transform = tio.ZNormalization()

times = []
for _ in range(10):
    start = time.time()
    transformed = transform(sample)
    times.append(time.time() - start)

times = np.array(times)
print(f'{times.mean():.1f} +- {times.std():.1f} seconds')
```

Output:

```
29.9 seconds
27.1 seconds
23.1 seconds
36.6 seconds
37.7 seconds
30.8 seconds
28.6 seconds
33.1 seconds
32.9 seconds
29.7 seconds
30.9 +- 4.1 seconds
```

On:

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
```

**Comment by fepegar** [comment]
Refactoring `znorm`:

```python
    @staticmethod
    def znorm(tensor: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        values = tensor.masked_select(mask)
        mean, std = values.mean(), values.std()
        if std == 0:
            return None
        tensor -= mean
        tensor /= std
        return tensor
```

Output: `8.5 +- 1.8 seconds`.

**Comment by fepegar** [comment]
Using `Colin27(year=1998)`:

Before: `718.5 +- 54.8 ms`.
After: `257.9 +- 22.4 ms`.

**Comment by romainVala** [comment]
Hi fernado, 
sound goods,  just to understand, changing :
tensor = tensor + noise   
to 
tensor += noise

avoid a copy variable ??
you gain a factor 4 which is nice, but 8 s to compute the Znorm is still big, ... How it comes ? (I though it would be less that 1s .)

By the way it was good to have the timing include in torchio, for all transform when verbose was on. (you removed this feature a long time ago ...)

**Comment by fepegar** [comment]
> Hi fernado,
sound goods, just to understand, changing :
tensor = tensor + noise
to
tensor += noise
avoid a copy variable ??

Yes. I think it's equivalent to `torch.add(tensor, noise, out=tensor)`.

> you gain a factor 4 which is nice, but 8 s to compute the Znorm is still big, ... How it comes ? (I though it would be less that 1s .)

Well, Colin2008 is a large sample compared to Colin1998. It has one more image and each image has double resolution, making them 8 times heavier:

```python
In [1]: import torchio as tio

In [2]: colin1998 = tio.datasets.Colin27(version=1998)
Using cache found in /Users/fernando/.cache/torchio/mni_colin27_1998_nifti

In [3]: colin1998
Out[3]: Colin27(Keys: ('t1', 'head', 'brain'); images: 3)

In [4]: colin1998.shape
Out[4]: (1, 181, 217, 181)

In [5]: colin2008 = tio.datasets.Colin27(version=2008)
Using cache found in /Users/fernando/.cache/torchio/mni_colin27_2008_nifti

In [6]: colin2008
Out[6]: Colin27(Keys: ('t1', 't2', 'pd', 'cls'); images: 4)

In [7]: colin2008.shape
Out[7]: (1, 362, 434, 362)

In [8]: colin1998.t1
Out[8]: Image(shape: (1, 181, 217, 181); spacing: (1.00, 1.00, 1.00); orientation: RAS+; memory: 27.1 MiB; type: intensity)

In [9]: colin2008.t1
Out[9]: Image(shape: (1, 362, 434, 362); spacing: (0.50, 0.50, 0.50); orientation: RAS+; memory: 217.0 MiB; type: intensity)

In [10]: transform = tio.ZNormalization()

In [11]: %timeit transform(colin1998)
206 ms ± 20.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]: %timeit transform(colin2008)
9.51 s ± 1.18 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

> By the way it was good to have the timing include in torchio, for all transform when verbose was on. (you removed this feature a long time ago ...)

I was just using it to debug my own code when this library was just for me. I thought users can measure the time it takes in many other, better ways. But we can open a discussion about it if you like.

**Comment by romainVala** [comment]
well in this case it is important to dissociate loading time from transform time, which seems to me easier to do within torchio ...
but there may be other better way like the one you recently advertise (py-spy) ... I have to play with it to see  ...
