### ISSUE TITLE
Add support to take more types as transform input

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#203]
- [x] Python dictionaries
- [x] SimpleITK image
- [x] `torchio.Image`s
- [ ] NiBabel images
- [ ] 5D tensors (batches of 4D tensors)
- [ ] PIL images
- [ ] path

**Comment by Zhack47** [comment]
Hello, is there someone working on handling 5D tensors?
Or is there a known workaround currently recommended?

**Comment by fepegar** [comment]
Hi, @Zhack47. You can iterate over a 5D tensor and transform each 4D tensor. Is this to transform a batch?

**Comment by Zhack47** [comment]
@fepegar Yes,exactly. I used the method you mentioned in my code.
Can i try and submit a pull request if I manage to implement it directly inside the transform class?

**Comment by romainVala** [comment]
hi
just curious to know what kind of data needs a 5D tensor representations ?

**Comment by Zhack47** [comment]
@romainVala 3D volumes, n channels and the batch dimension
