### ISSUE TITLE
Questions about RandomResizedCrop and ColorJitter

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#205]
Question by Mjavan on [PyTorch Discourse](https://discuss.pytorch.org/t/data-agumentation-in-3d-images/86289):

> Hi @ptrblck and thank you @fepegar.
I am working with 3D medical images that are Grayscale.
I looked at TorchIO and your nice effort there. I need RandomResizedCrop, that gives me the original size of the image after cropping. This transformation in PyTorch crops the image with an aspect ratio [0.08,1]. I found Crop in TorchIO without resizing to the original image, or the capability of accepting any aspect ratio. I googled it in the net and I found that it is difficult to define aspect ratio in 3D space. Would it be possible to add these two parameters to Crop in TorchIO. I have also a question about the type of inputs for transformations in TorchIO. Dose it support both 4D Torch tensor and Numpy? Would it be possible that in TorchIO we have Colorjitter like transformation that we have in pytorch. I am not sure how much difference it may make as images here are Grayscale, but still I like to try it.
Thanks again for your help.

**Comment by fepegar** [comment]
> Would it be possible to add these two parameters to Crop in TorchIO?

What is your application? I think those transforms are typically used for image classification in computer vision but are rarer for medical images.

You can implement random cropping plus changing the aspect ratio as follows:

```python
from itertools import islice
import torch
import torchio as tio


class RandomCrop:
    def __init__(self, scale=(0.8, 1)):
        for n in scale:
            if not 0 < n <= 1:
                raise ValueError(f'Invalid scale value {n}')
        self.scale = scale

    def __call__(self, sample):
        multiplier = torch.FloatTensor(3).uniform_(*self.scale)
        spatial_shape = torch.Tensor([sample.spatial_shape]).squeeze()
        crop_shape = (spatial_shape * multiplier).round().int()
        sampler = tio.data.UniformSampler(crop_shape)
        patch = list(sampler(sample, 1))[0]
        return patch


random_crop = RandomCrop(scale=(0.5, 1))

affine = tio.RandomAffine(
    scales=(3/4, 4/3),
    degrees=0,
    translation=0,
)

transform = tio.Compose([random_crop, affine])
colin = tio.datasets.Colin27()
colin_transformed = transform(colin)

colin.t1.save('/tmp/colin_t1.nii.gz')
colin.brain.save('/tmp/colin_brain_seg.nii.gz')
colin_transformed.t1.save('/tmp/colin_t1_tr.nii.gz')
colin_transformed.brain.save('/tmp/colin_brain_tr_seg.nii.gz')
```

Here are the saved images before (shape `(181, 217, 181)`) and after (shape `(166, 197, 171)`) applying the transform:

![Screenshot](https://user-images.githubusercontent.com/12688084/85323049-3f2eb400-b4bf-11ea-92b2-90d02c09dfd7.png)


> I have also a question about the type of inputs for transformations in TorchIO. Dose it support both 4D Torch tensor and Numpy?

Yes, both. Here's an example with a Torch tensor:

```python
In [145]: tensor = torch.ones(1, 2, 2, 2)

In [146]: tensor
Out[146]:
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [147]: transform = tio.RandomNoise()

In [148]: transformed = transform(tensor)

In [149]: transformed
Out[149]:
tensor([[[[1.0796, 1.0461],
          [0.9705, 1.0458]],

         [[1.1461, 0.9810],
          [1.0161, 0.9975]]]])
```


> Would it be possible that in TorchIO we have Colorjitter like transformation that we have in pytorch?

I think the grayscale equivalent would be [`torchio.RandomNoise`](https://torchio.readthedocs.io/transforms/augmentation.html#randomnoise).

Would all this work for you?

**Comment by Mjavan** [comment]
Hi fepegar

Thank you for your answer.  It works properly, but I need to resize the images after cropping. I wrote a costum transformation here and I combined it with RandomBlur of your package.  Sometimes it is working but sometimes it is not working, and I get the following error:
` At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().)`

Here is my code:

class RandomCropResized3d(object):
    
    def __init__(self,crop_size,is_training=True):
        
        """Crop vol to crop_size"""
        
        assert isinstance(crop_size, (int, tuple))
        
        self.is_training = is_training
        
        if isinstance(crop_size, int):
            
            self.crop_size = (crop_size, crop_size,crop_size)
            
        else:
            
            assert len(crop_size) == 3
            
            self.crop_size = crop_size
            
    def __call__(self,vol):
        
        vol= vol.squeeze()
        
        h_old,w_old,d_old = vol.shape[:3]
        
        h,w,d = self.crop_size
        
        if self.is_training:
    
        
            x = np.random.randint(0,h_old-h)
        
            y = np.random.randint(0,w_old-w)
        
            z = np.random.randint(0,d_old-d)
            
        else:
            
            # crop center
            x = int((h_old - h) / 2)
            y = int((w_old - w) / 2)
            z = int((d_old - d) / 2)
        
        vol = vol[x:x+h,y:y+w,z:z+d]
    
        
        scale = [h_old*1.0/h, w_old*1.0/w, d_old*1.0/d]
        
        vol = ndimage.interpolation.zoom(vol, scale, order=0)  
        return(vol[np.newaxis,...])

class RandomHorizontalFlip3D(object):
    
    def __init__(self,p):
        
        self.p = p
        
    def __call__(self,vol):
        
        vol = vol.squeeze()
        
        if np.random.rand() < self.p:
            
            vol = np.fliplr(vol)
            
            return(vol[np.newaxis,...])
            
        return(vol[np.newaxis,...])

class GaussianBlur(object):
    
    def __init__(self,min=0.1,max=2.0):
        
        self.min = min
        
        self.max = max
        
    def __call__(self,vol):
        
        prob = np.random.random_sample()
        
        if prob<0.5:
            
        GausBlur= torchio.transforms.RandomBlur((self.min,self.max), p=0.5)
            
        vol = GausBlur(vol)
            
        return(vol)

transform = transforms.Compose([RandomCropResized3d(conf.crop_size),RandomHorizontalFlip3D(conf.flip_rate),GaussianBlur()]) 

a = np.random.randn(1,256,256,159)

a_tr = transform(a)

print(a_tr.shape)

**Comment by fepegar** [comment]
> It works properly, but I need to resize the images after cropping

Then you need to compose the `RandomCrop` I suggested and a [`Resample`](https://torchio.readthedocs.io/transforms/preprocessing.html#resample) transform. It is equivalent to `scipy.ndimage.zoom`. But are you sure you want to "resize" your images? See discussion in https://github.com/fepegar/torchio/issues/193#issuecomment-645560174. Can you tell me a bit more about what you'd like to achieve? What's the task? And what kind of data are you using?

> Sometimes it is working but sometimes it is not working

When it works it's because your flip transform is not being applied. You're getting an error because PyTorch doesn't support negative strides. Why don't you use the [`RandomFlip`](https://torchio.readthedocs.io/transforms/augmentation.html#torchio.transforms.RandomFlip) transform in TorchIO? You won't get this error.

Also, you're using a probability of 0.5 twice for the Gaussian blur. That makes the transform happen only 25% of times.

**Comment by fepegar** [comment]
Also, I see that you crop around the center for inference. You can use [`CropOrPad`](https://torchio.readthedocs.io/transforms/preprocessing.html#croporpad) for that.

**Comment by Mjavan** [comment]
Hi, 
Thank you for your detailed answer.  Regarding what I want exactly to do, I am trying to develop a framework from 2D to 3D and apply it for medical images for segmentation tasks. The data that I am going to work is 3D pancreas images in 4D numpy format.

Regarding if I am sure that I want to resize the images after cropping, it is in the original paper and I want to take those transformations plus some other ones to try which one would work better for medical images and can imrove the performnace of the network.

**Comment by fepegar** [comment]
> a framework from 2D to 3D

What do you mean?

> 3D pancreas images in 4D numpy format.

What does the 4th dimension encode in these images?

> it is in the original paper

Could you please share it? I'm curious.

> I want to take those transformations plus some other ones to try which one would work better for medical images and can imrove the performnace of the network.

Hopefully, you won't need to implement anything yourself :) I think you can find all you need in this library.

**Comment by Mjavan** [comment]
Sorry, I can't explain it more, because it is a project that I am doing. 
However, I am not sure if it would work or not. I am in the elementary steps.
The 4th dimension in these images is the channel, which is 1 for medical images.
I would try the transformations in your library, one time more.
Thank you so much for your help, I checked what you said and it is working now.

**Comment by fepegar** [comment]
No worries. I'm glad it's working. Feel free to open issues for any other question. Good luck!

**Comment by Mjavan** [comment]
Thank you. Ok, sure.
