### ISSUE TITLE
RandomGhosting algorithm removes zero-frequency component

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#206]
**🐛Bug**

When the ghosting algorithm removes the center of k-space, the image is too distorted.

**To reproduce**

I'm using [this image](https://www.dropbox.com/s/3342ndv600tcmjp/t1.nii.gz?dl=1) and the [TorchIO Slicer module](https://torchio.readthedocs.io/slicer.html).

8 ghosts along axis 2:

<img width="1280" alt="Screen Shot 2020-06-24 at 13 45 15" src="https://user-images.githubusercontent.com/12688084/85559148-5980a300-b621-11ea-8e1d-3b0d590bff1b.png">

7 ghosts:
<img width="1280" alt="Screen Shot 2020-06-24 at 13 45 41" src="https://user-images.githubusercontent.com/12688084/85559190-67362880-b621-11ea-90bc-8ffd59b244f6.png">

The shape of the image along axis 2 is 176, which is a multiple of 8.

**Expected behavior**

An image that looks more like the second.

**TorchIO version**

0.17.0.

**Comment by fepegar** [comment]
If the zero-frequency component is restored, the image looks more natural, but the artifact is not very visible. 

<img width="1280" alt="Screen Shot 2020-06-24 at 14 00 57" src="https://user-images.githubusercontent.com/12688084/85561186-466ed280-b623-11ea-91a7-04091b342bb8.png">

Also, there's no reason to limit the `intensity` kwarg to 1. Maybe the intensity could be scaled to be inversely proportional to the number of ghosts. If number of ghosts is set to 2:

<img width="1280" alt="Screen Shot 2020-06-24 at 14 04 25" src="https://user-images.githubusercontent.com/12688084/85561599-a2d1f200-b623-11ea-9ec5-a0dac1e28ea0.png">

This also looks a bit like the original image. Maybe it's better to restore not just the middle line of k-space, but a percentage of the k-space around the center, e.g. 2-5%.

**Comment by romainVala** [comment]
there is already a  percentage_to_avoid = 0.05 in the code, 
no ?

**Comment by fepegar** [comment]
Lastly, I think there's no reason to take only images with positive values. We could use the real part of the inverse Fourier transform instead of the magnitude:

<img width="711" alt="download (1)" src="https://user-images.githubusercontent.com/12688084/85565186-d2362e00-b626-11ea-8b53-48b77b189a12.png">

This is the result of using 8 ghosts and getting the real component instead of the magnitude:

<img width="1280" alt="Screen Shot 2020-06-24 at 14 28 13" src="https://user-images.githubusercontent.com/12688084/85574282-8ab3a000-b62e-11ea-9b9d-6995748a4a34.png">

**Comment by fepegar** [comment]
> there is already a percentage_to_avoid = 0.05 in the code,
no ?

Yes, you're right. But it doesn't seem to be working, and the code I wrote for `RandomGhosting` is not clear. I have a new implementation, I'll open a PR in a second.

**Comment by romainVala** [comment]
ok
I am surprise about the visual different between abs and real (what is the color map in both (min max values) 
The reason taking the abs is that this is what is done in the acquisition process ... (you never get negative values in raw images) but not sure if we have to follow it ...

**Comment by fepegar** [comment]
In that plot I used an image with negative values to accentuate the issue. I don't know much about raw values from the MR scan. Are they always positive?

I think the imaginary component in the plot is just noise, almost 0, so taking the real part only would make sense.

**Comment by fepegar** [comment]
Here's the notebook I've been playing with: https://colab.research.google.com/drive/1Uk5Zq-uJFdyGh7Dzs7agprH1H5IYU0KP?usp=sharing

**Comment by romainVala** [comment]
> In that plot I used an image with negative values to accentuate the issue. I don't know much about raw values from the MR scan. Are they always positive?

the MR image is the inverse fourier transform of the measured signal, so you get a complex number, but most of the sequence just consider the magnitude 
The phase can have a lot of meaning in some case, but this is an other issue,

**Comment by fepegar** [comment]
I prefer the MRI artifacts at the beginning as well, but users might, for whatever reason, have some negative values in the input.

[Here's a notebook](https://colab.research.google.com/drive/1JGDJ8FsCH0BQ6SgjFE_ztwq1c7SmmIGy?usp=sharing) that I'm playing with. You can see that there's not much difference:

<img width="855" alt="download (2)" src="https://user-images.githubusercontent.com/12688084/85596273-7cbb4a80-b641-11ea-893f-fdff9268e176.png">

**Comment by romainVala** [comment]
> I'm using [this image](https://www.dropbox.com/s/3342ndv600tcmjp/t1.nii.gz?dl=1) and the [TorchIO Slicer module](https://torchio.readthedocs.io/slicer.html).
> 
> 8 ghosts along axis 2:

I do not reproduce your first image (with master branch), with you t1 and this code

```
suj = [tio.data.Subject(t1=tio.data.Image('/data/t1.nii.gz', tio.INTENSITY))]
t=    tio.transforms.RandomGhosting(axes=2, num_ghosts=(8,8), intensity=(1,1))

dataset = tio.data.ImagesDataset(suj, transform=t)
s = dataset[0]
s['t1'].save('/tmp/trans.nii')

```
what do I miss ?

**Comment by romainVala** [comment]
forget my previous message, I was using your last PR ...

**Comment by fepegar** [comment]
Note that since #204 you don't need to pass the subject through the dataset:

```python
suj = tio.data.Subject(t1=tio.Image('/data/t1.nii.gz'))
t = tio.RandomGhosting(axes=2, num_ghosts=(8, 8), intensity=(1, 1))
s = t(sun)
s.t1.save('/tmp/trans.nii')
```
