### ISSUE TITLE
Speedup crops

### ISSUE THREAD

**Issue by MoiseevMikhail** [fepegar/torchio#212]
Hi! Thanks for your amazing library, I'll definitely cite it in my work!

**🚀 Feature**
Faster crops in GridSampler and other samplers

**Motivation**
I've tried to use GridSampler with 512x512x512 array. On my Ryzen 2700 cpu one call of __getitem__ takes ~5 seconds. I've figured out the reason: it's sitk.GetImageFromArray(array.transpose()) in nib_to_sitk function, which takes 2.5 seconds for both intensity and mask arrays. You use it on the whole source array on every apply_transform call, which is fine for smaller arrays, but becomes a huge bottleneck for big arrays.

**Pitch**
You could probably somehow refactor samplers to call nib_to_sitk once at the initialization, and then make crops from sitk array without conversion of the whole big array for every single crop

**Alternatives**
The other possible way is to get rid of sitk crop completely and use torch/numpy slicing directly

**Comment by fepegar** [comment]
Hi @MoiseevMikhail,

Thanks for reporting and for your kind words!

How large are your windows? I just tried with `(128, 128, 128)` on my macOS from 2014 and sampling all windows took 1:26 minutes (1.23 +- 0.44 seconds per iteration).

If I crop using PyTorch instead, it takes 30 seconds in total and 0.36 +- 0.07 per iteration.

As you suggest, most of the time is taking by `sitk.GetImageFromArray` in the first case, and by `torch.clone`. I think the solution is copying all the fields that are not images and, for the images, crop and *then* copy. I'll think of a way to do this.

As reference, we introduced cropping with `Crop` for samplers in #175 and reverted it for random samplers in https://github.com/fepegar/torchio/commit/89acf631d3329c83ec91ac526ebe7ae7ae433cd6, as `nib_to_sitk` was taking too long.

**Comment by fepegar** [comment]
Using `patch.clone()` is much faster: 0.044 +- 0.005 seconds per iteration. I'll go for that one.

As a reference, `patch.clone()` is much faster than `copy.deepcopy(patch)`. It looks like the whole tensor is copied in the second case.

**Comment by fepegar** [comment]
Could you please upgrade `torchio` and tell me how long it takes now?

**Comment by MoiseevMikhail** [comment]
Now getitem takes ~1ms. Good job, thanks!
