### ISSUE TITLE
transform torchio subject - mask with multiple masks and different shapes than image

### ISSUE THREAD

**Issue by xen0f0n** [fepegar/torchio#215]
I have an RGB Image and a 7-class ground truth mask and I'm trying to figure out how to integrate torchio into my pipeline. 
I get this error

```
ValueError: Images in sample have inconsistent shapes:
{'Image': (1, 3, 4041, 2817), 'Mask': (1, 7, 4041, 2817)}
```

Also, when transforming the ground truth mask, what is the appropriate shape? onehot (eg. 1, 7, 4041, 2817) or categorical (eg. 1, 1 ,4041, 2817)?

**Comment by fepegar** [comment]
Hi @xen0f0n,

Could you please share the code that produces this error? TorchIO hasn't been tested thoroughly with 2D data, but maybe I can help. First, I think you need to add a dimension to your images when you instantiate the `Image` class. At the moment, TorchIO thinks your images are 3D. What transforms are you planning to use? Any samplers?

**Comment by xen0f0n** [comment]
Hey @fepegar.
I'm not sure why I should add a dim to my images... They already have 4-dims.
I plan to use znorm, affine and elastic transforms. It's my understanding that the Image type (INTENSITY, LABEL) defines what transforms can be applied (just to not mess with ground truth masks). For the znorm and affine transforms, I thought the following would work (it does not):

```
from torchio.transforms import ZNormalization, RandomAffine

znorm_transform = ZNormalization(masking_method='Image')
affine_transform = RandomAffine(degrees=(0, 10), image_interpolation='bspline')
transform = torchio.transforms.Compose([znorm_transform, affine_transform])

transformed = transform(sample)
``` 

```sample``` is a Subject object with keys "Image" and "Mask".

**Comment by fepegar** [comment]
> I'm not sure why I should add a dim to my images... They already have 4-dims.

Can you share the code you're using to define `sample`? Tensors in TorchIO have shape (channels, si, sj, sk). I don't think the code is currently adapted to work with RGB, but I could look into that if needed. This is related to #213. Something you could do is split your RGB into the three channels. That would definitely work.

> Also, when transforming the ground truth mask, what is the appropriate shape? onehot (eg. 1, 7, 4041, 2817) or categorical (eg. 1, 1 ,4041, 2817)?

Categorical, for the reason stated above.

**Comment by xen0f0n** [comment]
> Something you could do is split your RGB into the three channels. That would definitely work.

I'm not sure how to do that. Adding an extra dimension to the image as 
```torchio.Image(tensor=torch.from_numpy(np.expand_dims(img, 0)).transpose(0,1), type=torchio.INTENSITY)```
, leads to:

```RuntimeError: The input tensor must have 3 dimensions (D, H, W), but has 4: torch.Size([3, 1, 4041, 2817])
```

> Can you share the code you're using to define sample?

It's something like this... 

img = cv2.imread(image_path)
img = np.transpose(img, (2, 0, 1))
mask = cv2.imread(mask_path, 0)

d = {}
d['Image'] = torchio.Image(tensor=torch.from_numpy(img), type=torchio.INTENSITY) 
d['Mask'] = torchio.Image(tensor=torch.from_numpy(new_mask), type=torchio.LABEL)

sample = torchio.Subject(d)

**Comment by fepegar** [comment]
Can you try this?

```python
b, g, r = cv2.imread(image_path)
mask = cv2.imread(mask_path, 0)

d = {}
d['Image_red'] = torchio.Image(tensor=r[np.newaxis], type=torchio.INTENSITY)
d['Image_green'] = torchio.Image(tensor=g[np.newaxis], type=torchio.INTENSITY)
d['Image_blue'] = torchio.Image(tensor=b[np.newaxis], type=torchio.INTENSITY)
d['Mask'] = torchio.Image(tensor=mask, type=torchio.LABEL)

sample = torchio.Subject(d)
```

**Comment by xen0f0n** [comment]
Ok, this works! 
It seems to me that in order to use  ```torchio.ImagesDataset``` I'll have to merge these different rgb channels into a single tensor (If diff shapes allow that). I wonder if this will work.
 
And since I plan to use Grid sampler also, I'll have to repeat  this "upack - merge" inside the ```model.eval``` loop. 

If it's ok with you, I'll try this and follow up, either here or in  https://github.com/fepegar/torchio/issues/216#issue-650486076

**Comment by fepegar** [comment]
> It seems to me that in order to use torchio.ImagesDataset I'll have to merge these different rgb channels into a single tensor (If diff shapes allow that). I wonder if this will work.

Why do you think you need to merge them?

> And since I plan to use Grid sampler also, I'll have to repeat this "upack - merge" inside the model.eval loop.

I haven't tried samplers from 2D images, but it should work, given an appropriate patch size.

> If it's ok with you, I'll try this and follow up, either here or in #216 (comment)

Yeah let's finish up here with the question about `ImagesDataset` and then we can move on to #216.

**Comment by xen0f0n** [comment]
@fepegar hey! 
So, what I did is a bit messy, but I think it works. 
First of, of course you were right, that using ```torchio.ImagesDataset``` works without this upack-merge.

But, I ended up doing this upack-merge inside a subclass of Dataset and a ```__get_item__``` method, 'cause I needed to resample each image with a different scale, and couldn't do that outside the Dataset. I do the transforms, get the tensors and  have the ```__get_item__``` return them (```return image, mask```).

Ideally the resample transform would take a lambda function as argument that "finds" the appropriate scaling factor for each image, based on its original shape. (Not sure if this makes sense to you). 

It's a bit hacky, but I think it'll be fine. 

Thanks again!

**Comment by fepegar** [comment]
> Ideally the resample transform would take a lambda function as argument that "finds" the appropriate scaling factor for each image, based on its original shape. (Not sure if this makes sense to you).

Do you mean a `Resize` transform?

**Comment by xen0f0n** [comment]
Yes. I though that Resample does resize... 
Although I resize 2d images, I think it works. I use the bspline interpolation method (since there is no bilinear or bicubic). 
Am I missing something?

**Comment by fepegar** [comment]
You can use `image_interpolation='linear'`.

Interpolation with B-splines of order 1 is equivalent to using linear interpolation, AFAIK. In 2 and 3D, linear interpolation is also called bilinear and trilinear interpolation, respectively.
