### ISSUE TITLE
Question about RandomElasticDeformation

### ISSUE THREAD

**Issue by Mjavan** [fepegar/torchio#217]
Hi, I have a question about, `RandomElasticDeformation` in Torchio, how should I find an appropriate num_control_points for a 3D volume? And is it necessary to define max_displacement?

My last question is how Can I get a visualization of transformed 3D volumes using these transformations?  My 3d volumes are 4d NumPy arrays of dimension [channel, H, W, D] that are pancreas 3D images. I apply transformation and I got no error but I do not know if transformation is already applied or not. And is the input of all transformations in this library are in the form of 
`(channel,h,w,d)`?
Thanks

**Comment by fepegar** [comment]
Hi @Mjavan,

> Hi, I have a question about, RandomElasticDeformation in Torchio, how should I find an appropriate num_control_points for a 3D volume?

I suggest you read the [documentation for `RandomElasticDeformation`](https://torchio.readthedocs.io/transforms/augmentation.html#randomelasticdeformation). You'll see that the number of control points defines how smooth your transformation is. You can download [this notebook](https://gist.github.com/fepegar/b723d15de620cd2a3a4dbd71e491b59d), that I reference in the docs, and change the value of the `ctrl_pts ` variable to see the effect of this parameter.

> And is it necessary to define max_displacement?

If the maximum displacement is too large, you might get a transformation that is not physically plausible (folding).

> My last question is how Can I get a visualization of transformed 3D volumes using these transformations? My 3d volumes are 4d NumPy arrays of dimension [channel, H, W, D] that are pancreas 3D images. I apply transformation and I got no error but I do not know if transformation is already applied or not. Thanks

The first thing you can do is print out your data. You could ask the same for this case:

```python
>>> def transform(x):
...    return 2 * x
>>> 
>>> a = 5
>>> b = transform(a)
```

How do you know the transformation has already been applied? You just look at `b`:

```python
>>> b
10
```

I don't know the code you're using, but here's a similar check using volumes:

```python
In [1]: import torchio as tio

In [2]: colin = tio.datasets.Colin27()
Using cache found in /Users/fernando/.cache/torchio/mni_colin27_1998_nifti

In [3]: transform = tio.RandomElasticDeformation()

In [4]: transformed = transform(colin)

In [5]: colin.t1.data.sum()
Out[5]: tensor(1.2958e+13)

In [6]: transformed.t1.data.sum()
Out[6]: tensor(1.2845e+13)
```

As you can see, the image after transformation is different.

You can use 3D Slicer to play with these parameters and visualize the images. I have written an [extension](https://torchio.readthedocs.io/slicer.html) you can use for this. [ITK-SNAP](http://www.itksnap.org/pmwiki/pmwiki.php) is a light tool you can also use to open your images.

**Comment by Mjavan** [comment]
Thank you so much. Just in the last block you made a sum over pixels, right? 
so I can do the same when volumes are numpy arrays, right?

**Comment by fepegar** [comment]
Yes, both NumPy arrays and PyTorch tensors have a `sum` method.

**Comment by Mjavan** [comment]
Thank you, it is a good clue to understanding if transformations are working or not. The order of the dimensions of inputs to transformations in your package is `(channel,h,w,d)`?

**Comment by fepegar** [comment]
Yes. But at the moment there's not a lot of support for 4D images. Why are your images 4D?

**Comment by Mjavan** [comment]
They are 3D grayscale not 4D

**Comment by fepegar** [comment]
Ok, good. You said they were 4D NumPy arrays. Let me know if you need anything else.

**Comment by Mjavan** [comment]
Thank you. Sure.
