### ISSUE TITLE
Incoherence between RandomTransform.parse_range and RandomGhosting intensity

### ISSUE THREAD

**Issue by GFabien** [fepegar/torchio#218]
**🐛Bug**

When given a single positive number `x`, `RandomTransform.parse_range` outputs the tuple `(-x, x)`. From the doc of  `RandomGhosting`, it states that you can give a single value for the `intensity` parameter. However, if you do so you get an error as intensity cannot be negative. 

**To reproduce**

```python
import torchio
tranform = torchio.transforms.RandomGhosting(intensity=1)
```

```python-traceback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-57113dda3e8e>", line 2, in <module>
    tranform = torchio.transforms.RandomGhosting(num_ghosts=10, intensity=1)
  File ".../torchio/torchio/transforms/augmentation/intensity/random_ghosting.py", line 63, in __init__
    raise ValueError(message)
ValueError: Intensity must be a positive number, not -1
```

**Expected behavior**

I guess the expected behavior would be to get the range `[x, x]` when providing the single value x.

**TorchIO version**

0.17.7

**Comment by fepegar** [comment]
Fixed in `v0.17.8`. Thanks for reporting, @GFabien!
