### ISSUE TITLE
Add support for 2D images

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#22]

**Comment by deepnarainsingh** [comment]
Hi @fepegar ,

Great work , could you please provide the details for this requirement , would like to contribute.

**Comment by fepegar** [comment]
Hi @deepnarainsingh,

Thanks for your interest!

I suppose there are multiple issues about this:
1. Adapting the `io` module to read and write common 2D formats such as JPEG or PNG
2. Thinking whether 2D images should be treated as 3D images with depth 1 or actually remove dimension
3. Make sure all transforms work as expected for 2D inputs

You can start by forking the repo, adding a branch named `22-add-2d-support`, create a temporary pull request to the master branch of this repo and start committing.

**Comment by deepnarainsingh** [comment]
Thanks for the details @fepegar .
I will go through the code and check .

**Comment by fepegar** [comment]
@deepnarainsingh What would be your use case?
