### ISSUE TITLE
Use SimpleITK to resample

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#227]
**🚀 Feature**

Currently, resampling in `Resample` is done using NiBabel, which performs interpolation using B-splines. Using a spline of order 0 and 1, one gets the equivalent of nearest neighbor and linear interpolation. However, both take as long. With `SimpleITK` the range of different interpolation techniques is larger and times between e.g. nearest and linear would be very different, which is desired.

Furthermore, the choices for interpolation techniques would be consistent with the rest of the transforms.

Finally, this is a step further towards having a unified transform for `RandomAffine`, `RandomDownsample` and `RandomElasticDeformation`.

**Comment by jshube2** [comment]
Hi,

I recently started phasing in TorchIO as the backbone for my company's deep learning pipelines. 

I was using the TorchIO Resample transform, but wasnt satisfied with its run time so I created my own Resample transform using SimpleITK.

I would be happy to clean it up and submit a merge request once my current workload is completed. 

Awesome framework by the way. I look forward to seeing it grow

**Comment by fepegar** [comment]
Hi @jshube2. Thanks! What's the difference with the current transform?

**Comment by fepegar** [comment]
I mean, is the main difference the tool used to perform the actual resampling?

**Comment by jshube2** [comment]
That appears to be the difference (using SimpleITK over NiBabel). Though as you mentioned in the OP, linear and nearest neighbor interpolation take as long as b-splines for NiBabel. I am only doing linear interpolation with SimpleITK. 

Perhaps Bspline for SimpleITK has the same performance as BSpline for NiBabel, but I have not been able to do an analysis yet.

**Comment by fepegar** [comment]
@jshube2 I recently had some time to work on this. Let me know if you think there are other improvements to be made!

**Comment by jshube2** [comment]
Ok awesome. I took a look at the changes and it looks good. I apologize for not getting to this task earlier but I hope I can make some contributions down the line

**Comment by fepegar** [comment]
No problem, thanks!
