### ISSUE TITLE
Request for new options

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#231]
First of all, I'd like to thank you for this package. It is really well written and easy to use.

**🚀 Feature**
It would be great if the following options could be added:
- [Random crops](https://github.com/mdbloice/Augmentor#cropping)
- [Random resizing](https://github.com/mdbloice/Augmentor#cropping)
- [Random erasing ](https://github.com/mdbloice/Augmentor#random-erasing)

**Motivation**

These would take care of cases where the input data is not great.

**Pitch**

The aforementioned options would make DL models more robust.

**Alternatives**

Using other packages.

**Comment by romainVala** [comment]
Hello, 

I think that fernando is on holliday, so he will respond later.
I can give a few hints
For random crops and resizing You can have similar augmenation with the 
RandomAffine and CropOrPad torchio transform
RandomAffine will induce rotation and scalling (scalling == resize) you can also specify translation , and adding a CropOrPad transform after it, will restrict the Field of view

Random erasing is not yet implemented, but should be easy to derive from the RandomSwap transform (instead of remplacing a patch by noise, it switch two path of the volume)

I hope it helps

**Comment by sarthakpati** [comment]
Hey, thanks, this does help. It would be great if these can be added as proper options. :)

**Comment by fepegar** [comment]
> Hey, thanks, this does help. It would be great if these can be added as proper options. :)

Hi, @sarthakpati. Would you like to contribute? PRs are welcome!

> Hello,
I think that fernando is on holliday, so he will respond later.
I can give a few hints

Thanks @romainVala, I was indeed on holiday :D

> Random crops
> Random resizing

Here's an implementation of `RandomCrop` that you can start from: https://github.com/fepegar/torchio/issues/205#issuecomment-647703444

You can also see an example of using `RandomAffine` to randomly resize, as @romainVala suggested.

> Random erasing

Should be easy to contribute this one, if you'd like to give it a go.

---

What type of images are you working with? What is the task?

**Comment by sarthakpati** [comment]
> Hi, @sarthakpati. Would you like to contribute? PRs are welcome!

Would love to, but unfortunately, I am hard-pressed for the next couple of months between various (and often unending) deadlines. I doubt I will be able to put something like this together in this time frame.

Thanks for the resources; I will stick to what is available, for now and re-evaluate after I get some results.

> What type of images are you working with? What is the task?

I was thinking of applying this to the BraTS data (and some other private GBM cases).

**Comment by fepegar** [comment]
> I was thinking of applying this to the BraTS data (and some other private GBM cases).

In that case, you should be able to use the currently available transforms for your purposes. I'll close this for now, feel free to reopen if necessary.
