### ISSUE TITLE
How to disable citation message

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#235]
Hi,

How can I disable the citation message that comes up:
```
If you use TorchIO for your research, please cite the following paper:
Pérez-García et al., TorchIO: a Python library for efficient loading, 
preprocessing, augmentation and patch-based sampling of medical images
in deep learning. Link: https://arxiv.org/abs/2003.04696
```

This is implicit for people in academia. 😄 

Cheers,
Sarthak

**Comment by fepegar** [comment]
Hi @sarthakpati. Being an early researcher, citations help me a lot. Furthermore, people tend to not cite the software they use (see [Research software citation in the Data Citation Index: Current practices and implications for research software sharing and reuse](https://www.sciencedirect.com/science/article/pii/S1751157718302372)).

If you really want to remove the message, you can set this environment variable in your `.bashrc` or equivalent:

```shell
export TORCHIO_HIDE_CITATION_PROMPT=1
```

**Comment by sarthakpati** [comment]
Of course, I completely understand. And don't worry, any work that I publish where `torchio` will be used, you will get appropriately cited. 😄 

Thanks.

**Comment by neuronflow** [comment]
Thank you, is there a way to set this inside a python script? so the code runs the same way regardless of the machine being used?

```
os.environ["TORCHIO_HIDE_CITATION_PROMPT"] = str(1)

```

seems to have no effect even when set right at the beginning of the script before importing any tio stuff.

**Comment by fepegar** [comment]
Good. It works fine for me:

```python
In [1]: import os

In [2]: os.environ["TORCHIO_HIDE_CITATION_PROMPT"] = str(1)

In [3]: import torchio

In [4]:
```
