### ISSUE TITLE
Cropping gets rid of some attributes

### ISSUE THREAD

**Issue by GFabien** [fepegar/torchio#239]
**🐛Bug**

Cropping now:
- removes every key that is not among `DATA`, `AFFINE` and `TYPE` at the `Image` level;
- reinitializes every attribute that was already set at the `Subject` level.

It was introduced in aaae0560a45ac2477c8c7e5bea627320e17143d6. (I guess you already knew about it @fepegar since there is a TODO in the `Image.crop` method.)

**To reproduce**

```python
from torchio import RandomBlur
from torchio.datasets import Colin27

colin = Colin27(2008)
transform = RandomBlur()
transformed = transform(colin)
cropped = transformed.crop((0, 0, 0), (10, 10, 10))

print('Path before cropping:\t\t', transformed['t1']['path'])
print('Path after cropping: \t\t', cropped['t1']['path'])

print('History before cropping:\t', transformed.history)
print('History after cropping: \t', cropped.history)

>>> Using cache found in /.../.cache/torchio/mni_colin27_2008_nifti
>>> Path before cropping:	 /.../.cache/torchio/mni_colin27_2008_nifti/colin27_t1_tal_hires.nii
>>> Path after cropping: 		 
>>> History before cropping:	 [('RandomBlur', {'t1': {'std': array([2.6496408, 1.359108 , 3.448594 ], dtype=float32)}, 't2': {'std': array([3.449116  , 0.23409271, 0.9134309 ], dtype=float32)}, 'pd': {'std': array([0.53169155, 3.554979  , 0.03398538], dtype=float32)}})]
>>> History after cropping: 	 []
```
Therefore, you lose access to the original path of the `Image` (but you would also have lost any custom attribute that you would have added) and you lose access to the history of the `Subject`. 

**Expected behavior**

I expect that information is preserved after cropping. It is important to be able to reproduce results are trying to understand why we get especially good or bad results on given patches.

**TorchIO version**

`0.17.7`

**Comment by fepegar** [comment]
Thanks, @GFabien. Fixed in `v0.17.12`.
