### ISSUE TITLE
Please update changelog/history

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#242]
Current history is for `0.15.0`, whereas the tag has gone up to `0.17.12`. It would be great to get a cohesive set of changes (however minor they may be) so that projects that depend on TorchIO can take a call whether they need to update (and potentially re-check any potential changes to their pipelines).

**Comment by fepegar** [comment]
You're right! I'll update it in a minute. Thanks for reporting!

**Comment by fepegar** [comment]
I've started creating GitHub releases after publishing:

https://github.com/fepegar/torchio/releases

Less nice than a good CHANGELOG.md, but better than nothing.
