### ISSUE TITLE
Unable to get the training started

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#243]
Hey,

I am trying to do dummy train but I am running into a weird error. Here is what I have written:

```python
trainingDataForTorch = torchio.ImagesDataset( ... )
train_loader = DataLoader( ... )

# all good till here

for ep in range(epochs)
    batch_iterator = iter(train_loader)
    for batch_idx, (subject) in enumerate(train_loader):
        batch_train = next(batch_iterator_train)
        image = torch.cat([batch_train[key][torchio.DATA] for key in batch_train.keys()], dim=1) # concatenate channels 
```

In the last line (taken from #236), I get the following error: 

```bash
Traceback (most recent call last):
  File "trainer.py", line 287, in <module>
    image = torch.cat([batch_train[key][torchio.DATA] for key in batch_train.keys()], dim=1) # concatenate channels
  File "trainer.py", line 287, in <listcomp>
    image = torch.cat([batch_train[key][torchio.DATA] for key in batch_train.keys()], dim=1) # concatenate channels
IndexError: too many indices for tensor of dimension 2
```

Pretty sure I am doing some silly syntactic mistake, here but wanted to get your opinion, too. Thanks.

**Comment by fepegar** [comment]
Hi, @sarthakpati. It's a bit hard to know what's going on without some more code. What is `batch_iterator_train`? Why not just doing `for batch_idx, batch in enumerate(train_loader)`? Do you think you can provide a minimal working example?

**Comment by sarthakpati** [comment]
No worries, I got it to work, thanks!

**Comment by fepegar** [comment]
Good! Can you say where the problem was, for reference?

**Comment by sarthakpati** [comment]
Basically did what you suggested and used `for batch_idx, batch in enumerate(train_loader)`. 😄
