### ISSUE TITLE
Some links to classes in docs are not working

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#247]
For example, in [`RandomLabelsToImage`](https://torchio.readthedocs.io/transforms/augmentation.html#randomlabelstoimage), the link to `RandomTransform` works but not the one to `RandomBlur`.

**Comment by jwitos** [comment]
Hey @fepegar, does this issue need any further help/work?

**Comment by fepegar** [comment]
Yes, definitely! I have very little experience with Sphinx and reStructuredText. It feels like fixing this should be easy, but I keep having trouble with this. For example, I'm not sure why the links to the classes in the first paragraph of the [Transforms](https://torchio.readthedocs.io/transforms/transforms.html#transforms) section don't work. I feel like there's a namespace problem, but I don't think using `.. currentmodule::` is always the solution.

I've managed to make work e.g. the `SubjectsDataset` link in [this page](https://torchio.readthedocs.io/data/patch_training.html), after taking a look at other projects.

Do you have experience with this / would you be able to contribute with this issue? That would be great! After setting up the [development environment](https://github.com/fepegar/torchio/blob/master/CONTRIBUTING.rst) I do `cd docs && make html` to build the docs locally and check whether things look right.

**Comment by jwitos** [comment]
I don't have experience with Sphinx but I'm happy to give it a try. It does feel like it should be straightforward. Let me give it a go and I will get back to you soon!

**Comment by fepegar** [comment]
Sounds great! Thanks, @jwitos.
