### ISSUE TITLE
save_sample from ImagesDataset

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#25]
When using the save_sample method from ImagesDataset
the nifti have a wrong dimention one should change

            tensor = sample[key]['data']
by

            tensor = sample[key]['data'].squeeze()

Not sure if this is the rigth place for this function, why not put it directly in io.py ?

**Comment by fepegar** [comment]
You're right that there was one dimension too many. I haven't put that one in `io` because I'd like to keep that module lower level, and this method is coupled with the dict format generated by `ImagesDataset`. Thanks!
