### ISSUE TITLE
Add missing reference in RandomLabelsToImage

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#254]
Billot B, Robinson E, Dalca A, Iglesias JE: “Partial Volume Segmentation of Brain MRI Scans of any Resolution and Contrast”, Proceedings of MICCAI 2020 (accepted).

**Comment by romainVala** [comment]
I would say the closet one, is the first one at at the same conference
""A Learning Strategy for Contrast-agnostic MRI Segmentation"

The partial volume part of the article you propose, is not related to this code, but should be  (almost)  reproducible with torchio transforms. @GFabien is currently testing ....

**Comment by fepegar** [comment]
It's a request from the authors personally :)
