### ISSUE TITLE
How to do inference using grid sampler and how does it exactly work?

### ISSUE THREAD

**Issue by meghbhalerao** [fepegar/torchio#256]
Hi All,

I want to perform inference on a multi modal data using the grid sampler. However, I am not able to wrap my head around the working of the grid sampler in this link: https://torchio.readthedocs.io/data/patch_inference.html?highlight=gridsample

Here, it says that: 

```python
grid_sampler = torchio.inference.GridSampler(
    sample,
    patch_size,
    patch_overlap,
)
```

Here the `sample` is one individual object of the `Subject` class? I was just wondering if this would become a little clumsy while performing inference on a list of `subjects`?Or do I just create a list of `grid_samplers` and iterate through them?

It would be great if you could point me to an example which does inference for an entire list of images.

Thanks you!

**Comment by fepegar** [comment]
Hi, @meghbhalerao.

> Here the sample is one individual object of the Subject class?

Yes. I guess that could be clearer in the docs.

> I was just wondering if this would become a little clumsy while performing inference on a list of subjects?Or do I just create a list of grid_samplers and iterate through them?

I think you can just instantiate a sampler at every iteration:

```python
for subject in dataset:
    grid_sampler = torchio.inference.GridSampler(
        sample,
        patch_size,
        patch_overlap,
    )
    # etc.
```

> It would be great if you could point me to an example which does inference for an entire list of images.

It's a bit like what I do in [this cell of the notebook](https://colab.research.google.com/drive/112NTL8uJXzcMw4PQbUvMQN-WHlVwQS3i#scrollTo=SKu8k5Z2wkSD&line=9&uniqifier=1), but at each iteration.

Does that make sense?

**Comment by meghbhalerao** [comment]
Hi @fepegar,
Thank you for your answer. Yes, it makes sense. I will instantiate the sampler at every iteration through the subjects dataset. 
Thanks again!

**Comment by meghbhalerao** [comment]
Hi @fepegar,
So, I tried using the method which you told me. From my observation, the `sample` is what I get while iterating through `torchio.ImagesDataset()`, and not what I get while iterating through the `DataLoader` object created from the `torchio.ImagesDataset()`. Is there any specific reason for doing so, that I am missing? Alternatively, why can't the `dict` that we get while iterating through the `dataloader` be passed in the `grid_sampler`?
Thanks again!

**Comment by fepegar** [comment]
What I would do is something like:

```python
for subject in dataset:
    subject_grid_sampler = GridSampler(subject, ...)  # the patches positions are computed here
    aggregator = GridAggregator(subject_grid_sampler)  # the aggregator checks the sampler to take decisions about overlap or padding
    loader = DataLoader(subject_grid_sampler, batch_size=B)
    for batch in loader:
        inputs, locations = prepare_batch(batch)
        outputs = model(input)    
        aggregator.add_batch(outputs, locations)
    output_tensor = aggregator.get_output_tensor()
```

Why would you need a data loader for the subjects? Would you like to load them in parallel? In that case, you can use a `DataLoader` with `collate_fn=lambda x: x` and the subjects data loader will return a list of instances of `Subject` that you can iterate through, using another data loader to run the inference on multiple patches at the same time.

**Comment by meghbhalerao** [comment]
Hi @fepegar,
Thanks a lot for your explanation. I understood it.
