### ISSUE TITLE
RuntimeWarning: Files have different affine matrices

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#266]
**🐛Bug**

This is a warning in `tests/data/test_image.py::TestImage::test_with_a_list_of_2d_paths`.

@GFabien, you wrote that one. Could you please take a look?

**To reproduce**

`$ pytest`

**TorchIO version**

`0.17.25`.

**Comment by GFabien** [comment]
Hi @fepegar! I had a look and it seems that it's an issue with `_write_sitk` from `torchio.data.io`.

Indeed, in `test.utils.get_image_path`, the first path from `tests/data/test_image.py::TestImage::test_with_a_list_of_2d_paths` is created with suffix `"img"`. When saving the image with that path, `torchio.data.io.write_image` first tries to save it using `torchio.data.io._write_nibabel` but fails when calling `nii.to_filename(str(path))` saying that "Filespec [...] does not look right for class <class 'nibabel.nifti1Nifti1Image'>". 

Therefore it calls `torchio.data.io._write_sitk` which manages to save the image but seems to mess up with the affine. I'll dive more into details to understand what's the matter there.

**Comment by fepegar** [comment]
I think that's because
1. `torchio.data.io._write_sitk` maybe doesn't have proper support to write `.img` images
2. In `torchio.data.io._write_nibabel`, the image type is hardcoded to be NIfTI, which I think can only have suffix `.nii`. 

`.img` is Analyze, right? Either we use an appropriate NiBabel class according to the extension (checking NiBabel code to see how they do that) or we discourage the use of Analyze and throw an error. However, it's very possible that some people still use it (despite the limitations in image orientation).

**Comment by GFabien** [comment]
I think I found it. It's a problem between `nib_to_sitk` and `sitk_to_nib` with 2D images. To go to SimpleITK format you multiply by `FLIP_XY` to go from RAS to LPS coordinates and to go back to NiBabel format you multiply again by `FLIP_XY` which is fine in most cases. However, in the case of 2D images, you remove the X axis so when you recover the rotation from the direction in `sitk_to_nib` you start from the identity matrix and fill the bottom right square of it with the direction making the rotation matrix the following:
```python
affine = [
    [1    0    0    0],
    [0   -1    0    0],
    [0    0    1    0],
    [0    0    0    1]
]
```
Therefore, when you multiply it with `FLIP_XY` you don't get the identity back. I guess the fix is just to start with a -1 in the upper left corner when recreating the rotation. Tell me if you think it can lead to other issues.

**Comment by GFabien** [comment]
From what I read on this [article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3948928/), `.img` can be Analyze or Nifti but more importantly, if the voxels are saved in the `.img` file, the header is saved in an `.hdr` file so we should probably save two files to handle this format correctly, I don't know if SimpleITK and NiBabel do this or not.

NiBabel seems to have some mechanism to find a header file from an image file according to its [documentation](https://nipy.org/nibabel/reference/nibabel.loadsave.html). In fact I just tried, using `nib.save` instead of method `to_filename` works fine and NiBabel manages to save and load the image without any problem.

To be sure, I checked and SimpleITK creates both a `.img` and a `hdr` file so it seems to work as expected.

**Comment by GFabien** [comment]
> I think I found it. It's a problem between nib_to_sitk and sitk_to_nib with 2D images.

Even if this is indeed a problem, correcting this does not solve the issue as `sitk_to_nib` is not called because NiBabel manages to load the image which means that there is a problem in the header saved by SimpleITK.

(Using `nib.save` instead of `to_filename` solves the issue)

**Comment by fepegar** [comment]
> I think I found it. It's a problem between nib_to_sitk and sitk_to_nib with 2D images. To go to SimpleITK format you multiply by FLIP_XY to go from RAS to LPS coordinates and to go back to NiBabel format you multiply again by FLIP_XY which is fine in most cases. However, in the case of 2D images, you remove the X axis so when you recover the rotation from the direction in sitk_to_nib you start from the identity matrix and fill the bottom right square of it with the direction making the rotation matrix the following:

affine = [
    [1    0    0    0],
    [0   -1    0    0],
    [0    0    1    0],
    [0    0    0    1]
]
Therefore, when you multiply it with FLIP_XY you don't get the identity back. I guess the fix is just to start with a -1 in the upper left corner when recreating the rotation. Tell me if you think it can lead to other issues.

Good catch!

> I don't know if SimpleITK and NiBabel do this or not.

AFAIK NiBabel handles this automatically. You can give either path, it will look for the other one.

> NiBabel seems to have some mechanism to find a header file from an image file according to its documentation. In fact I just tried, using nib.save instead of method to_filename works fine and NiBabel manages to save and load the image without any problem.

I thought these two methods worked the same way... I wonder why it's different.

**Comment by GFabien** [comment]
Ok I've played a bit with SimpleITK and NiBabel and what I think is happening is that when SimpleITK saves a 2D image it considers that the axes used are X and Y but not Y and Z as torchio is handling 2D images. 
Therefore, when you save a 2D image using SimpleITK, you first flip axes X and Y, get the direction, then remove axis X from the direction and save the image. In a Nifty header, it appears that `quatern_b = 1` while `quatern_c = 0` and `quatern_d = 0` and `pixdim[0]=-1`. It means that there is a 180° rotation around axis X (i.e. a flip of axes Y and Z) and axis Z is flipped again. So in the end, only axis Y gets flipped. That's why when NiBabel tries to read the image it finds that axis Y is flipped resulting in a wrong affine.

The other way around, if you save the 2D image with NiBabel and read it with SimpleITK, SimpleITK finds that the direction for the first two axes (which it thinks are X and Y) is 'RA' so it sets its direction to `-1, 0, 0, -1` (as it is in 'LP'). Then, you reconstruct the 3x3 matrix by adding axis X and flip axes X and Y. However, because of the direction vector, you get that axis Z has been flipped resulting in a wrong affine.

I do think that SimpleITK expects 2D images to be on the X and Y axes but I haven't found any evidence in the documentation so far...

```python
from numpy.testing import assert_array_equal

class TestIO(TorchioTestCase)
...
    def test_write_2d_with_itk_read_it_with_nib(self):
        tensor = torch.randn(1, 1, 20, 30)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_sitk(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_nibabel(path)
        assert_array_equal(tensor, loaded_tensor)
        assert_array_equal(affine, loaded_affine)

    def test_write_2d_with_nib_read_it_with_itk(self):
        tensor = torch.randn(1, 1, 20, 30)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_nibabel(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_sitk(path)
        assert_array_equal(tensor, loaded_tensor)
        assert_array_equal(affine, loaded_affine)
```

**Comment by fepegar** [comment]
Do you think changing the behaviour of the library so that it assumes 2D images if the shape along the last axis is 1 instead? I don't think it would be too late, as 2D support is still very experimental anyway. That would probably be friendlier with respect to ITK.

**Comment by GFabien** [comment]
Yes that's probably a good idea and their choice seems natural as when you have a 2D image you would say that you have a height and a width but no depth.

**Comment by fepegar** [comment]
The docs say (channels, depth, height, width) everywhere. This was for compatibility with PyTorch docs. But I agree it feels more natural in medical imaging to talk about (height, width, depth). A potential issue is that SimpleITK gives you (height, width):

```
$ curl -LO https://cdn.eso.org/images/thumb300y/eso1907a.jpg                                                                   
$ identify eso1907a.jpg                        
eso1907a.jpg JPEG 515x300 515x300+0+0 8-bit sRGB 7817B 0.000u 0:00.000
$ python -c "import SimpleITK as sitk; print(sitk.ReadImage('eso1907a.jpg').GetSize())"                                     
(515, 300)
```

This is the image:
![](https://cdn.eso.org/images/thumb300y/eso1907a.jpg)

**Comment by GFabien** [comment]
> The docs say (channels, depth, height, width) everywhere. This was for compatibility with PyTorch docs.

Is there any impact in PyTorch to have (channels, height, width, depth) instead of (channels, depth, height, width) ? PyTorch should be generic enough to handle both exactly the same way so maybe there's no need to follow this convention and we should use (channels, height, width, depth) instead.

**Comment by fepegar** [comment]
Yeah it was mostly for consistency. What's height and width in a 3D acquisition anyway? I'll open a PR.

**Comment by fepegar** [comment]
I've made a lot of changes in #270. However, the one that seemed to solve this issue is the last commit: saving .img files with NiBabel.

**Comment by GFabien** [comment]
Nice work! I have a few questions about it. Is there a reason why you chose to distinguish between suffixes and use either `Nifti1Image` or `Nifti1Pair` objects and not just calling `nib.save`?
I'm not sure I get when `transpose_2d` in `_read_sitk` or `_write_sitk` will be used. I've added a few tests to `io.py` and some of them fail with `transpose_2d=True` (`test_write_2d_with_itk_read_it_with_nib` and `test_write_2d_with_nib_read_it_with_itk`):

```python
    def test_write_3d_with_itk_read_it_with_itk(self):
        tensor = torch.randn(1, 10, 20, 30)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_sitk(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_sitk(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)

    def test_write_3d_with_itk_read_it_with_nib(self):
        tensor = torch.randn(1, 10, 20, 30)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_sitk(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_nibabel(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)

    def test_write_3d_with_nib_read_it_with_itk(self):
        tensor = torch.randn(1, 10, 20, 30)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_nibabel(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_sitk(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)

    def test_write_3d_with_nib_read_it_with_nib(self):
        tensor = torch.randn(1, 10, 20, 30)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_nibabel(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_nibabel(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)

    def test_write_2d_with_itk_read_it_with_itk(self):
        tensor = torch.randn(1, 10, 20, 1)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_sitk(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_sitk(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)

    def test_write_2d_with_itk_read_it_with_nib(self):
        tensor = torch.randn(1, 10, 20, 1)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_sitk(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_nibabel(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)

    def test_write_2d_with_nib_read_it_with_itk(self):
        tensor = torch.randn(1, 10, 20, 1)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_nibabel(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_sitk(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)

    def test_write_2d_with_nib_read_it_with_nib(self):
        tensor = torch.randn(1, 10, 20, 1)
        affine = np.eye(4)
        path = self.dir / 'test_io.nii.gz'
        io._write_nibabel(tensor, affine, path)
        loaded_tensor, loaded_affine = io._read_nibabel(path)
        assert_array_equal(tensor.squeeze(), loaded_tensor.squeeze())
        assert_array_equal(affine, loaded_affine)
```

**Comment by fepegar** [comment]
Should we also transpose 2D images with NiBabel then?

> Is there a reason why you chose to distinguish between suffixes and use either Nifti1Image or Nifti1Pair objects and not just calling nib.save?

I think NiBabel raised an error when trying to save Nifti1Image as `.img`.

**Comment by GFabien** [comment]
> Should we also transpose 2D images with NiBabel then?

I don't know, why would we need to transpose 2D images in the first place?

>  I think NiBabel raised an error when trying to save Nifti1Image as .img.

I tried it with `nib.save` instead of `nib.to_filename` and it worked fine.

**Comment by fepegar** [comment]
> I don't know, why would we need to transpose 2D images in the first place?

Well, I thought it'd be more user-friendly to think of the first axis as up->down and second as left->right, as in a numpy matrix.

```python
In [1]: import SimpleITK as sitk

In [2]: image = sitk.ReadImage('eso1907a.jpg')

In [3]: image.GetSize()
Out[3]: (515, 300)

In [4]: array = sitk.GetArrayFromImage(image)

In [5]: array.shape
Out[5]: (300, 515, 3)
```

But maybe it's a bad idea and makes things just confusing.

> I tried it with nib.save instead of nib.to_filename and it worked fine.

I guess we'll use that one instead, then. I opened an issue on the NiBabel repo to ask about the differences.


I'll open a PR and this time I'll wait for your review.

**Comment by GFabien** [comment]
> Well, I thought it'd be more user-friendly to think of the first axis as up->down and second as left->right, as in a numpy matrix.

OK I get it now. I think it does not matter for deep learning and it may probably be the role of a viewer to handle this kind of things.

**Comment by fepegar** [comment]
I need to change everything again from (C, H, W, D) to (C, W, H, D) 🤦🤦🤦🤦🤦

**Comment by GFabien** [comment]
Sorry ^^'

**Comment by fepegar** [comment]
I think it's done. I refactored your tests to run in a loop. They fail if I add 4D images. Maybe we should follow again ITK conventions about where channels are in the saved files... but that's a different issue.

**Comment by fepegar** [comment]
Here's the 2D notebook: https://colab.research.google.com/drive/1yEhhFvUqvwCOsu_w7taHvRpvfD656fS3#scrollTo=ZB8RsAUOHJ1L
