### ISSUE TITLE
Inconsistent shapes of images

### ISSUE THREAD

**Issue by DerpyCoder** [fepegar/torchio#273]
**🐛Bug**
The shapes of the images of CT scans vary from images

**To reproduce**

Versions above 0.17.15 will have a different output if reading in .mhd or dicom folders

```python
print(torchio.__version__)
subject = torchio.Subject(
    CT = torchio.Image(path = "something here", type=torchio.INTENSITY),
)
print(subject.shape)
```

```python-traceback
'''
0.17.10
(1, 512, 512, 345)
'''

'''
0.17.18
(345, 1, 512, 512)
'''

'''
0.17.14
(1, 512, 512, 345)
'''

'''
0.17.15
(1, 512, 512, 345)
'''

'''
0.17.17
(345, 1, 512, 512)
'''
```

**Expected behavior**

I expected the format in Channel x X x Y x Z but versions above 0.17.15 seem to follow a different format
Not sure if this is a bug or a feature

**TorchIO version**

**Comment by fepegar** [comment]
Hi, @DerpyCoder. Thanks for reporting.

Recent support for 4D images is probably causing this behavior. I don't know how your images are stored. Can you share some examples?

You can change the way 4D images are read with the `channels_last` keyword argument of `Image`. By the way, you can now use `ScalarImage` and forget about `type`.

**Comment by DerpyCoder** [comment]
I directly pass the path to the image (mhd) or folder (dicom) in the `path` keyword argument.

The dataset I am using to test this are the LUNA16 and the LIDC-IDRI dataset
The dicom images are stored in a folder like
01.dcm
02.dcm
03.dcm

The mhd files are in the same folder as their respective raw files

Are these images counted as 4D images though since they only contain a channel

**Comment by fepegar** [comment]
Changes in 349d771 should have fixed this. Now, DICOM images are read with channels first by default so your results should be consistent in `v0.17.30`. Feel free to reopen if they're not.
