### ISSUE TITLE
Uniform sampling across classes

### ISSUE THREAD

**Issue by GFabien** [fepegar/torchio#291]
**🚀 Feature**

The proposed feature is the creation of a sampler that will take a label map and will have the same probability for each class of the label map to take a voxel of this class as the center of the sampled patch.

**Motivation**

After training some segmentation models, I've seen that if some classes were not present enough in the ground truth, performance dropped drastically. Sampling a bit more from these classes seems to solve the issue.

**Pitch**

I would like to have a sampler that would directly achieve that by just giving it the label map of interest. Maybe a list of labels we are interested in could be useful to sample only from the classes we want.

**Alternatives**

The current alternative is to use a `WeightedSampler` and provide it the probability map.

**Additional context**

The feature is rather simple, to achieve this behaviour, we just need to set the same value to every voxel and then divide the value of each voxel by the volume of its class (and finally normalize to have probabilities).

I think the feature is still generic enough to be relevant in TorchIO, do you agree? If you do I will provide a PR.

**Comment by GFabien** [comment]
Sorry I got confused, the `LabelSampler` already achieves that for discrete label maps. My need is for partial-volume map. Would it be relevant to update it to handle partial-volume label maps?

**Comment by fepegar** [comment]
If you think it'll be helpful, I guess it wouldn't hurt to add this feature.

**Comment by GFabien** [comment]
Ok, cool. I made the implementation on @romainVala's fork, it looks like this: https://github.com/romainVala/torchio/pull/13/files

**Comment by fepegar** [comment]
Nice! I thought it would need more changes. Would you like to submit a PR?
