### ISSUE TITLE
TorchIO tutorial is not runable on Colab

### ISSUE THREAD

**Issue by nye0** [fepegar/torchio#293]
Hi,
Thank you for make this awesome tool!
I'm trying to learning to use it through the tutorial on Colab. 
However i found a lot of functions not define. (such as : show_subject, plot_histogram,get_model_and_optimizer,prepare_batch ...)

**Comment by fepegar** [comment]
Hi, @nye0. Thanks for the kind words!

Those functions are in collapsed cells to reduce verbosity. If you double-click on them, they'll expand. Also, if you download the notebook, you'll see them expanded. The visualization functions are [here](https://colab.research.google.com/drive/112NTL8uJXzcMw4PQbUvMQN-WHlVwQS3i#scrollTo=QS_PG3sMsH4w&line=1&uniqifier=1), and the deep learning ones are [here](https://colab.research.google.com/drive/112NTL8uJXzcMw4PQbUvMQN-WHlVwQS3i#scrollTo=oWbWAyFNTj74&line=1&uniqifier=1).

I've changed the text to make it more explicit that one needs to double-click on them to expand them.

Let me know if you can find them.

**Comment by nye0** [comment]
Wow, Got it! Thank you!
Ningrong
