### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by 9B8DY6** [fepegar/torchio#294]
torchio is not working on linux. is it only for mac and window?

**Comment by fepegar** [comment]
Hi @9B8DY6. TorchIO works on Linux, macOS and Windows. Most users I know work on Linux. If you have an issue, please do follow the instructions in the [`Bug report` template](https://github.com/fepegar/torchio/issues/new?assignees=&labels=bug&template=bug_report.md&title=).

**Comment by 9B8DY6** [comment]
thank you! I have solved the problem and now it is working well

**Comment by fepegar** [comment]
Great! Can you share the problem and the solution?
