### ISSUE TITLE
flag to disable citation spam

### ISSUE THREAD

**Issue by neuronflow** [fepegar/torchio#309]
**🚀 Feature**

flag to disable printing:
```
If you use TorchIO for your research, please cite the following paper:
Pérez-García et al., TorchIO: a Python library for efficient loading,
preprocessing, augmentation and patch-based sampling of medical images
in deep learning. Link: https://arxiv.org/abs/2003.04696
```

**Motivation**
It's annoying spam in the console, when debugging code. I will cite your work - no worries! :)

**Pitch**
provide a setting / flag to disable the print
**Alternatives**
remove the print :)
**Additional context**

<3 tio

**Comment by fepegar** [comment]
It's unfortunate that you find the citation prompt to be *annoying spam*. You can find instructions to mute it in #235.
