### ISSUE TITLE
Reading DICOM Vs. NIFTII

### ISSUE THREAD

**Issue by ilyanelken** [fepegar/torchio#317]
Hi,

I see discrepancies between data intensity values I get when reading DICOM or NIFTI.
I use ScalarImage() for reading.

So when DICOM is loaded I see that **scl_slope** factor is not applied on raw intensity values,
as it is automatically done with Nifti (I guess it is done in Nibabel), so I get different values.

I will appreciate your help.

Thanks,
Ilya

**Comment by fepegar** [comment]
Hi, Ilya. Thanks for reporting. Could you please share some anonymized data so that I can reproduce and investigate?

**Comment by ilyanelken** [comment]
@fepegar Sure, what is your email? I will send the data.

**Comment by fepegar** [comment]
Thanks! It's fernando.perezgarcia.17@ucl.ac.uk.

**Comment by fepegar** [comment]
(although I suspect this will be an ITK issue)

**Comment by ilyanelken** [comment]
@fepegar It might take a while, since after anonymization **scl_slope** parameter is being set to 1. I will send the data, after I will figure out what is going on.

**Comment by ilyanelken** [comment]
@fepegar I sent you the data. Thanks.

**Comment by fepegar** [comment]
It looks like the conversion to NIfTI failed: the intercept and slope are `nan` in the NiBabel header. What tool did you use for the conversion? I recommend `dcm2niix`.

Also, there are two series in the DICOM you sent me.

**Comment by ilyanelken** [comment]
I have used dcm2niix.

If you load NIFTI with nibabel, it performs data intensity scaling with intercept and slope and sets them both to nan.
If you open this nifti with MRICRON  you will be able to see the slope of ~7 for one of the series.

**Comment by fepegar** [comment]
For reference:

> Maximum intensity I get for DICOM is: 420.000
While for NIFTI it is: 3086.974
scl_slope is : 7.34994

In that case, there might be something wrong with your DICOM and dcm2niix is able to work around it. 3D Slicer shows the same values as TorchIO, but both use [Simple]ITK.

I suggest you ask the SimpleITK folks about this. Here's some code you can use for the issue:

```python
import SimpleITK as sitk

def read_dicom(directory):
    reader = sitk.ImageSeriesReader()
    dicom_names = reader.GetGDCMSeriesFileNames(directory)
    reader.SetFileNames(dicom_names)
    image = reader.Execute()
    return image

nii = sitk.ReadImage('/tmp/T1_ano.nii.gz')
dcm = read_dicom('/tmp/dicom_test/')
print(sitk.GetArrayViewFromImage(nii).max())
print(sitk.GetArrayViewFromImage(dcm).max())
```

I have tried with SimpleITK 1 and 2, and results are the same:

```
3086.9744
420
```

If you do open an issue on the SimpleITK GitHub, please mention me so that I'm updated!

**Comment by ilyanelken** [comment]
Thanks, I have opened an issue there:
https://github.com/SimpleITK/SimpleITK/issues/1205

**Comment by fepegar** [comment]
Great, thanks.

**Comment by ilyanelken** [comment]
@fepegar The issue is due to lack of original slope/intercept tags (only private ones are present). Seems like dcm2niix is using the private ones in that case, which is not the case for SimpleITK.

**Comment by fepegar** [comment]
Thanks for the update!
