### ISSUE TITLE
errro in random_bias_field.py

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#32]
Hello 
I get the following error when I try to apply the bias_field

```python-traceback
/data/romain/toolbox_python/torchio/torchio/transforms/random_bias_field.py in apply_transform(self, sample)
     34             bias_field = self.generate_bias_field_map(
     35                 image_dict['data'], self.order, coefficients)
---> 36             image_dict['data'] *= torch.from_numpy(bias_field)
     37         return sample
     38 

RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
```

if I change the corresponding  line with 
```python
            iii = image_dict['data'] * torch.from_numpy(bias_field)
            image_dict['data'] = iii
```
it pass,
very strange I do not understand why ...

**Comment by fepegar** [comment]
I'm not sure why this happens either. I was having this error yesterday in some other in-place tensor operation and it's indeed solved like that. I'll fix it.

I think it's related to the warning here: https://pytorch.org/docs/stable/tensors.html#torch.Tensor.expand

**Comment by fepegar** [comment]
Thanks, @romainVala

**Comment by fepegar** [comment]
I think I was getting the error [here](https://github.com/fepegar/torchio/commit/9ca546aea33638933e401ce8d54f46628e5d4398#diff-952d33516c3f8cf1d45c1f9ac1df431fR26-R28) and [here](https://github.com/fepegar/torchio/commit/bf60d5d403b794e0dcf6853e10157cedaf54604a).
