### ISSUE TITLE
HistogramStandardization   default params

### ISSUE THREAD

**Issue by ilyanelken** [fepegar/torchio#326]
Hi,

 I have a question about HistogramStandardization default params:

```
DEFAULT_CUTOFF = 0.01, 0.99
STANDARD_RANGE = 0, 100
```

Why those specific ones were chosen for standard range? Since as far as I know MRI intensities might get to ~2000/3000.
Also why there is no option to change STANDARD_RANGE via a function argument as it is done with cutoff?

Thanks,
Ilya

**Comment by fepegar** [comment]
Hi, @ilyanelken. That is the range of the output images, not the input, so it's not very important. It just means that most of the images will be in [0, 100] after applying this transform.

Look at the x-axis in the figure I added in the [docs](https://torchio.readthedocs.io/transforms/preprocessing.html#histogramstandardization):

![hist-standardization](https://torchio.readthedocs.io/_images/histogram_standardization.png)

**Comment by fepegar** [comment]
Or the figures in [one of the Colab notebooks](https://colab.research.google.com/drive/112NTL8uJXzcMw4PQbUvMQN-WHlVwQS3i?usp=sharing):

![hist_original](https://user-images.githubusercontent.com/12688084/94991442-1799be00-057b-11eb-9aa9-95a5aefbf329.png)
![hist_standard](https://user-images.githubusercontent.com/12688084/94991444-18caeb00-057b-11eb-901c-37e7b9d75f15.png)

**Comment by ilyanelken** [comment]
@fepegar I see, just to make sure: even if the output intensity values are squeezed to [0, 100], we are not loosing some of the original values since all calculations are in float, correct? Meaning we don't have any intensity quantisation effects during the standardisation flow?

**Comment by fepegar** [comment]
You do lose information because this is not an invertible transform, but
you're right that results are not quantized so you won't lose that kind of
information. Does that make sense?

**Comment by ilyanelken** [comment]
@fepegar Yep, just wanted to be sure that we are not loosing important information. I am currently using the standardization for T2 scans I am working with and I see significant improvements as there is more consistency between different scans. Thanks again and I am say you have created a great and very useful library. I am going to recommend it to my colleagues.

**Comment by fepegar** [comment]
Thanks, Ilya :D
