### ISSUE TITLE
segmentation fault problem...

### ISSUE THREAD

**Issue by Cheng-Liu-nihao** [fepegar/torchio#329]
excuse me, i have a question... if i use four ways of data augmentation at the same time, e.g. RandomFlip/RandomElasticDeformation/RandomAffine/RandomBiasField, how much memory does these augmentation processes will take? i meet a problem when i was training a model, it reported 'segmentation fault' or sometimes 'Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)' after one or several epochs of training. then other processes in my computer would be killed...
i think maybe it was the augmentation process which has token a lot of  memory that caused this problem, or maybe there were some errors in my ugly code.. hhhh.   someone can help me? thanks a lot!!!!  my ram memory is 32G, pytorch 1.6, ubuntu 16.04

**Comment by fepegar** [comment]
Hi, @Cheng-Liu-nihao. It's hard to know without information. It might be unrelated to TorchIO. What's the size of your images? Are you using the `Queue`? Can you paste here the whole error message?

**Comment by Cheng-Liu-nihao** [comment]
hi, very glad you can response me!!!!! my ubuntu system was broken due to my frequent rebooting... so now there is no error information that i could afford...  image size in my data set is 110*512*512. patch size is 384*384*1 because the model that i use is 2D U-Net, i also use the queue with num_of_workers =8, here are some important parts in my code...
![dataset](https://user-images.githubusercontent.com/59153394/95754534-c6ee3780-0cd5-11eb-91fd-6ae5ff99552b.png)
![main](https://user-images.githubusercontent.com/59153394/95754543-c8b7fb00-0cd5-11eb-8c99-64b2901cb14b.png)

**Comment by fepegar** [comment]
Unfortunately, this is not enough information. A Python traceback with the error might help. Feel free to reopen of you can provide one.

Also, I suggest you take a look at this: https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks
