### ISSUE TITLE
Error in tio.RandomAffine: 'Transform' object has no attribute 'AddTransform'

### ISSUE THREAD

**Issue by JavierBZ** [fepegar/torchio#331]
**🐛Bug**
Missing 'AddTransform' attribute in 'Transform' object from tio.RandomAffine.

**To reproduce**

 I used your Colab [Tutorial](https://colab.research.google.com/drive/1tI35u7V1ogDTKzaraXwwZRMebBIYiqOe?usp=sharing) for Data Preprocessing and Data Augmentation, and in the example in section Spatial Transforms > Random Affine with the code.

```python
random_affine = tio.RandomAffine(seed=0)
slice_affine = random_affine(slice_grid)
to_pil(slice_affine)
```

 i get this error in the second line of code.

```python-traceback
AttributeError: 'Transform' object has no attribute 'AddTransform'
```

**Expected behavior**

 Random Affine transformation of the example grid

**Actual behavior**

 Error 

**TorchIO version**

0.17.25

**Comment by fepegar** [comment]
Hi, Javier.

1. Can you provide a minimally working example as it's asked in the issue
template?
2. Can you try with the latest version? `pip install --upgrade torchio`

**Comment by fepegar** [comment]
Oh, I see. Where did you find that link? It's an old version. This is a newer version of that tutorial: https://colab.research.google.com/github/fepegar/miccai-educational-challenge-2020/blob/master/Data_preprocessing_and_augmentation_using_TorchIO_a_tutorial.ipynb

**Comment by JavierBZ** [comment]
New version of tutorial solves the issue.

**Comment by Binztech** [comment]
Hi Fernando,
I still run into the issue using the TorchIO version 0.18.53.
Do you have any suggestions?

**Comment by fepegar** [comment]
Hi, @Binztech. Can you please upgrade TorchIO and try again? And if it still does not work, can you open a new issue and share a minimal working example?
