### ISSUE TITLE
Coding issue with nibabel--- + Torchio

### ISSUE THREAD

**Issue by Sayantan17** [fepegar/torchio#339]
Hi. 
Thx for this wonderful repository.

I have a question. If I get the image + labels array for all my data, and corresponding ground truths with img=nib.load(os.path......), with gt......
Then, I use img=img_getdata()....., then return them. So then, my question=> in order to use Torchio, which I guess whill be provided by the (subjects, channel, h,w,d)----nibabel, right? If that's correct, do I need to use then as---

For example a class, 

```python
if transform is None:

            if mode == 'train':

               transform = ([
               tio.RandomAffine(): 0.75,
               tio.RandomElasticDeformation(): 0.25,
               tio.RandomAffine(scales=(0.9, 1.2), degrees=(10)),
               tio.RandomFlip(axes=('LR'))..... Likewise
               ])
```

**Comment by fepegar** [comment]
Hi, @Sayantan17. I think you missed something!

**Comment by Sayantan17** [comment]
> Hi, @Sayantan17. I think you missed something!

Edited! ☺️

**Comment by fepegar** [comment]
I'm not sure what the question is. Can you maybe try to be more specific?

**Comment by fepegar** [comment]
Typically, `array = img.get_data()` will return a NumPy array of shape `(w, h, d)`. You can add a channels dimension doing for example `array[np.newaxis]`and passing that to the `tensor` kwarg of `tio.ScalarImage`. But this is probably not necessary. Just pass the image path to `tio.ScalarImage` and it will take care of reading it.

I suggest you take a look at the [Getting started](https://torchio.readthedocs.io/quickstart.html) section in the docs, and go through all the [notebooks](https://torchio.readthedocs.io/quickstart.html#google-colab-jupyter-notebooks).

**Comment by Sayantan17** [comment]
I appreciate your response. I mean the format that mentioned for the transform is correct, right?

**Comment by fepegar** [comment]
I'm not sure what you mean by "format". I think the transform you're after would look something like this:

```python
transform = ([
    tio.OneOf({
        tio.RandomAffine(): 0.75,
        tio.RandomElasticDeformation(): 0.25,
    }),
    tio.RandomAffine(scales=(0.9, 1.2), degrees=10),
    tio.RandomFlip(axes=('LR')),
])
```

**Comment by Sayantan17** [comment]
That should work! But sorry for confusion though! 
Thanks!
