### ISSUE TITLE
Overlapping patches for training

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#340]
Hey,

Is there any way to obtain overlapping patches for training? I was thinking something similar to https://torchio.readthedocs.io/data/patch_inference.html#torchio.data.GridSampler but with the `overlap` parameter enabled.

Cheers,
Sarthak

**Comment by fepegar** [comment]
Hi, @sarthakpati. You'll need to be a bit more specific. I'm not sure what you would like to achieve. Would you like a sampler that is not random for training?

**Comment by sarthakpati** [comment]
Let's say we have an image of [100,100] and we select a patch size of [25,25]. From what I understand, the patch construction always picks up **unique** patches of [25,25] from that image (the number is controlled by the number of patches from each volume). I was wondering if it would be possible to extract **overlapping** patches, i.e., patches that contain overlapping information from each image. 

Illustratively:
- Current implementation: a patch starting from [0,0] and going to [24,24], another starts from from [25,25] and going to [49,49] and so on until the number of required patches per volume is reached
- Required functionality: a patch starting from [0,0] and going to [24,24], another starting from [10,10] (this is controlled using the overlap parameter) and going to [34,34]

Hope this makes more sense! 😄

**Comment by fepegar** [comment]
What do you mean by "patch construction"?

> Current implementation: a patch starting from [0,0] and going to [24,24], another starts from from [25,25] and going to [49,49] and so on until the number of required patches per volume is reached
Required functionality: a patch starting from [0,0] and going to [24,24], another starting from [10,10] (this is controlled using the overlap parameter) and going to [34,34]

This can be achieved (during inference) with the`patch_overlap` kwarg of the `GridSampler`.

**Comment by sarthakpati** [comment]
> What do you mean by "patch construction"?

I meant when we use one of the patch samplers.

> This can be achieved (during inference) with the`patch_overlap` kwarg of the `GridSampler`.

Yes, I know this (I have referenced this in my first post). I am asking if this can be done with the training sampler as well.

**Comment by fepegar** [comment]
I'm going to close this issue, as it's basically the same as #341. We can continue the discussion there.
