### ISSUE TITLE
How to use Lambda?

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#349]
Hi,

I am trying use the [Lambda](https://torchio.readthedocs.io/transforms/others.html#lambda) transform but I guess I am missing something. Could you help?

```powershell
# in environment
>>> def pow(x,e):
...     return x**e
>>> test_transform = Lambda(pow)
>>> x=torch.rand([1,255,255,100])
>>> test_transform(x,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() takes 2 positional arguments but 3 were given
>>> test_transform(data=x,e=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() got an unexpected keyword argument 'e'
```

**Comment by fepegar** [comment]
Hi, @sarthakpati. The docs for `Lambda` say

> function – Callable that receives and returns a 4D torch.Tensor.

It should receive _only_ a tensor.

But your function also needs an exponent `e`. You can use a fixed exponent: `Lambda(lambda x: x ** 2)`.

**Comment by sarthakpati** [comment]
I was giving that as an example. How would I use this function as a Lambda:

```python
def threshold(x, min_val, max_val):
    '''
    'x' is the (4D?) tensor, min and max are floats
    '''
    l1_tensor = torch.where(input_tensor < min_val, input_tensor, 0)
    l2_tensor = torch.where(l1_tensor > max_val, l1_tensor, 0)
    return l2_tensor
```

**Comment by fepegar** [comment]
When are the values for `min_val` and `max_val` set? Typically, these are decided when you instantiate the transform. For example, if you want them to be 4 and 6, you can do

```python
threshold_transform = Lambda(lambda x: threshold(x, 4, 6))
```

**Comment by sarthakpati** [comment]
Awesome. I can use this to solve #347, so I am closing that.
