### ISSUE TITLE
Images in subject have different sizes after resampling

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#354]
Hi,

I have an image and mask with these properties:
> Size: 512x512x75
>Spacing: 0.703125x0.703125x5.000000

I am adding these to a subject dictionary:

> '0': /path/to/image.nii # this is loaded as type=torchio.INTENSITY
> 'label': /path/to/mask.nii # this is loaded as type=torchio.LABEL

And I construct a torchio.SubjectsDataset from this, and a torchio.data.UniformSampler for patch size `256x256x32`, which I then pass to the Queue, along with a transformation of resampling this to `1x1x1`.

But, during training, I am getting the following error:
```bash
RuntimeError: More than one spatial_shape found in subject images:
{'0': (429, 429, 593), 'label': (512, 512, 237)}
```

Am I missing something, here? 

Thanks,
Sarthak

**Comment by fepegar** [comment]
Hi, @sarthakpati. Can you please paste the full error traceback?

**Comment by sarthakpati** [comment]
Does this help?

```
[user@cubic-login3 exp_0]$ cat log.e90532
Traceback (most recent call last):
  File "/home/code/venv_92/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/code/venv_92/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/code/training_loop.py", line 374, in <module>
    holdoutDataFromPickle=holdoutDataFromPickle,)
  File "/home/code/training_loop.py", line 168, in trainingLoop
    batch = next(iter(train_loader))
  File "/home/code/venv_92/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__

    data = self._next_data()
  File "/home/code/venv_92/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/code/venv_92/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch

# Number of channels/modalities - we shall use this as sanity check when we read the train.csv or test.csv
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/code/venv_92/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/code/venv_92/lib/python3.6/site-packages/torchio/data/queue.py", line 108, in __getitem__
    self.fill()
  File "/home/code/venv_92/lib/python3.6/site-packages/torchio/data/queue.py", line 165, in fill
    patches = list(islice(iterable, self.samples_per_volume))
  File "/home/code/venv_92/lib/python3.6/site-packages/torchio/data/sampler/uniform.py", line 22, in __call__
    sample.check_consistent_spatial_shape()
  File "/home/code/venv_92/lib/python3.6/site-packages/torchio/data/subject.py", line 123, in check_consistent_spatial_shape
    self.check_consistent_attribute('spatial_shape')
  File "/home/code/venv_92/lib/python3.6/site-packages/torchio/data/subject.py", line 120, in check_consistent_attribute
    raise RuntimeError(message)
RuntimeError: More than one spatial_shape found in subject images:
{'0': (429, 429, 593), 'label': (512, 512, 237)}
```

**Comment by fepegar** [comment]
> Does this help?

Of course! Now I see the problem. Please use the `python-traceback` syntax next time (see how I edited your comment).

Samplers need the `Image`s in the `Subject` to have the same spatial shape, as the error says. I think you can fix this using `Resample` and one of the two image names as reference, or using `CropOrPad`.

**Comment by sarthakpati** [comment]
Thanks, could you give me an example of how I could pass resample as a transform with one of the images as reference? My inputs are of the same sizes, so I am confused why this is coming up.

**Comment by fepegar** [comment]
What transforms are you using?

Are you sure your inputs have the same sizes? If that's the case, you shouldn't need to resample, but it'd be `Resample('0')` to resample the label map in the image space, and `Resample('label')` for the opposite.

**Comment by sarthakpati** [comment]
I am composing my transformations in the following way:

```python
transform = Compose(augmentation_list) 
subjects_dataset = torchio.SubjectsDataset(subjects_list, transform=transform)
```

Order: Resample -> Normalize -> augmentations (affine and swap)

**Comment by fepegar** [comment]
Do you have a way to verify that your images have the same size when loading?

**Comment by sarthakpati** [comment]
Are you referring to the images or the image-mask pairs?

**Comment by fepegar** [comment]
The pairs, I guess.

For example, you can instantiate the `SubjectsDataset` with `transform=None` and then:

```python
for subject in dataset:
   print(subject.shape)
```

**Comment by sarthakpati** [comment]
So, the pairs have the same sizes, but between 2 different pairs, the sizes _can_ be different.

**Comment by fepegar** [comment]
That should be fine. Can you reproduce using a single pair? If you can, could you please share the data or a MWE with simulated data?

**Comment by sarthakpati** [comment]
This is the LiTS data: https://academictorrents.com/details/27772adef6f563a1ecc0ae19a528b956e6c803ce 

I am trying to see if I can replicate using a single pair.

**Comment by sarthakpati** [comment]
Here you go:

```python    
for batch_idx, (subject) in enumerate(data_loader): # just contains a single subject, with resample transformation added
        # accumulate dice weights for each label
        mask = subject['label'][torchio.DATA]
        image = subject['0'][torchio.DATA]
        print('mask.shape: ', mask.shape)
        print('image.shape: ', image.shape)
```

And I am getting:

```powershell
mask.shape:  torch.Size([1, 1, 397, 397, 517])
image.shape:  torch.Size([1, 1, 397, 397, 517])
```

**Comment by fepegar** [comment]
Hmm that doesn't seem to replicate the issue: shapes are the same, as expected.

**Comment by sarthakpati** [comment]
Yes, I tried with a bunch of different images but it always came up as the same size... Also, I am confused why the size is like this when I specify the patch size?

**Comment by fepegar** [comment]
> Also, I am confused why the size is like this when I specify the patch size?

Hard to say without seeing the full code, but that would be a different issue anyway.

> Yes, I tried with a bunch of different images but it always came up as the same size...

Seems like your pairs have the same shape then :)
Feel free to reopen this if you can reproduce with a proper [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by sarthakpati** [comment]
Turns out this is an issue with the Resample! I have a minimal example ready here: https://github.com/sarthakpati/torchio_minimal/

**Comment by fepegar** [comment]
Thanks, that's very useful. I can replicate running this:

```python
In [1]: import torchio as tio

In [2]: subject = tio.Subject(image=tio.ScalarImage('volume-100.nii.gz'), label=tio.LabelMap('segmentation-100.nii.gz'))

In [3]: transformed = tio.Resample(1)(subject)

In [4]: transformed.shape
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-30414fc1adec> in <module>
----> 1 transformed.shape

~/git/torchio/torchio/data/subject.py in shape(self)
     84         Consistency of shapes across images in the subject is checked first.
     85         """
---> 86         self.check_consistent_attribute('shape')
     87         return self.get_first_image().shape
     88 

~/git/torchio/torchio/data/subject.py in check_consistent_attribute(self, attribute)
    117                 f'\n{pprint.pformat(values_dict)}'
    118             )
--> 119             raise RuntimeError(message)
    120 
    121     def check_consistent_spatial_shape(self) -> None:

RuntimeError: More than one shape found in subject images:
{'image': (1, 358, 358, 480), 'label': (1, 359, 359, 480)}
```

The problem is that the pair with ID 100 is not in the same physical space:

```python
In [1]: import nibabel as nib

In [2]: nib.load('volume-100.nii.gz').affine
Out[2]: 
array([[ -0.69921875,   0.        ,   0.        , 169.11578369],
       [  0.        ,  -0.69921875,   0.        ,  37.26315689],
       [  0.        ,   0.        ,   0.69999993,  15.30004883],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [3]: nib.load('segmentation-100.nii.gz').affine
Out[3]: 
array([[ -0.69921881,   0.        ,   0.        , 169.11578369],
       [  0.        ,  -0.69921881,   0.        ,  37.26315689],
       [  0.        ,   0.        ,   0.69999993,  15.30003738],
       [  0.        ,   0.        ,   0.        ,   1.        ]])
```

Not only do you need the same size for your volumes, but they should be in the same space. I'll add a check for this in the transform, but you'll need to fix your dataset.

**Comment by sarthakpati** [comment]
Great, thanks!
