### ISSUE TITLE
2D X-ray image

### ISSUE THREAD

**Issue by 9B8DY6** [fepegar/torchio#356]
I want to do segmentation 2D lung x-ray images with torchio. 
When I made dataset with them, image size was changed. (2674, 2685)->(3,2674,2685,1)
Is it possible to use torchio in 2D x-ray image? Does size change in image matter??
I am new to deep learning. Thank you.

**Comment by fepegar** [comment]
Yes, it is possible. I suggest you go through all the notebooks in the examples folder in this repository.

(2674, 2685) are the spatial dimensions of the 2D image: 2674 columns and 2685 rows. But it's probably saved as an RGB image, therefore you have 3 channels. The last dimension represents a 3rd spatial dimension, which is one for a 2D image.

I suppose your images are grayscale. In that case, you could create a transform to get rid of the other two channels:

```python
import torchio as tio
rgb_to_gray = tio.Lambda(lambda x: x[0:])
```

Feel free to reopen if you have any other specific questions.
