### ISSUE TITLE
WriteImage

### ISSUE THREAD

**Issue by ruiruian** [fepegar/torchio#363]
Hi,is there IO to write the transformed Image？I use tio.ScalarImage() to read 3D medical Image, I want to save the transformed image,but don't know how to write, thank you!

**Comment by fepegar** [comment]
Hi, @ruiruian. You can use the `save()` method: https://torchio.readthedocs.io/data/image.html?highlight=save#torchio.data.Image.save

That will hopefully help. Feel free to reopen if you have further related questions.
