### ISSUE TITLE
Other datatype for LabelMap than float32

### ISSUE THREAD

**Issue by dmus** [fepegar/torchio#375]
**🚀 Feature**
I noticed that a LabelMap and an IntensityImage are both saved as float32 tensors, which means that the LabelMap uses a lot more memory than needed. This is because this piece of code in io.py which casts all image to float32:

```
def _read_sitk(path: TypePath) -> Tuple[torch.Tensor, np.ndarray]:
    if Path(path).is_dir():  # assume DICOM
        image = _read_dicom(path)
    else:
        image = sitk.ReadImage(str(path))
    data, affine = sitk_to_nib(image, keepdim=True)
    if data.dtype != np.float32:
        data = data.astype(np.float32)
    tensor = torch.from_numpy(data)
    return tensor, affine
```

Is there a reason for this .astype(np.float32)?

This can be made a lot more memory friendly by removing this cast and storing segmentations in memory as uint8 for example. Also I expect spatial augmentations which requires resampling to be a lot faster when they work with uint8 instead of float32

**Motivation**

- Better use of memory
- Faster augmentations which require resampling

**Pitch**

No cast to float32 for all tensors, allowing different dtypes

Could these two lines be removed? All tests still pass when I comment them out. Maybe only cast bool to np.uint8 because SimpleITK does not support bool?
```
 if data.dtype != np.float32:
        data = data.astype(np.float32)
```

**Comment by fepegar** [comment]
I just tried this code

```python
import numpy as np
import SimpleITK as sitk

array = 256 * np.random.rand(256, 256, 180)

im_float = sitk.GetImageFromArray(array.astype(np.float32))
im_char = sitk.GetImageFromArray(array.astype(np.uint8))

print(im_float.GetPixelIDTypeAsString())
print(im_char.GetPixelIDTypeAsString())

transform = sitk.Euler3DTransform()
transform.SetRotation(10, 20, 30)
```

And then these:

```python
In [2]: %timeit sitk.Resample(im_float, transform)                                                                                                      
20.2 ms ± 484 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [3]: %timeit sitk.Resample(im_char, transform)                                                                                                       
15.2 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

So you're right, it's faster in uint8. I did this because some transforms required float and so I just transformed everything to float.
Another reason is that having a consistent data type, everything works smoothly with a data loader:

```python
In [9]: import torch 
   ...: import numpy as np 
   ...:  
   ...: class Dataset: 
   ...:     def __len__(self): 
   ...:         return 10 
   ...:      
   ...:     def __getitem__(self, i): 
   ...:         x = 10 * np.random.rand(10) 
   ...:         if i % 2: 
   ...:             x = x.astype(np.uint8) 
   ...:         return x 
   ...:  
   ...: loader = torch.utils.data.DataLoader(Dataset(), batch_size=5) 
   ...: next(iter(loader)) 
```

```python-traceback
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-ad773a21107d> in <module>
     13 
     14 loader = torch.utils.data.DataLoader(Dataset(), batch_size=5)
---> 15 next(iter(loader))

~/miniconda3/envs/episurg/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    344     def __next__(self):
    345         index = self._next_index()  # may raise StopIteration
--> 346         data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
    347         if self.pin_memory:
    348             data = _utils.pin_memory.pin_memory(data)

~/miniconda3/envs/episurg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     45         else:
     46             data = self.dataset[possibly_batched_index]
---> 47         return self.collate_fn(data)

~/miniconda3/envs/episurg/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     63                 raise TypeError(default_collate_err_msg_format.format(elem.dtype))
     64 
---> 65             return default_collate([torch.as_tensor(b) for b in batch])
     66         elif elem.shape == ():  # scalars
     67             return torch.as_tensor(batch)

~/miniconda3/envs/episurg/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     54             storage = elem.storage()._new_shared(numel)
     55             out = elem.new(storage)
---> 56         return torch.stack(batch, 0, out=out)
     57     elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
     58             and elem_type.__name__ != 'string_':

RuntimeError: Expected object of scalar type Double but got scalar type Byte for sequence element 1 in sequence argument at position #1 'tensors'
```

The tests probably pass because they typically use images that are created in float 32 (and obviously because they're not complete enough).

I agree that saving in float by default is not good. There should be at least a kwarg for the dtype.

So what do you think? I suppose there could be a `Cast` transform that could be used before a data loader (and by transforms that need float) but this would be quite backwards incompatible. But if it makes the library way faster, might be a good thing to do.

**Comment by dmus** [comment]
```
import torch
import numpy as np

class Dataset:
    def __len__(self):
        return 10

    def __getitem__(self, i):
        x = 10 * np.random.rand(10)
        if i % 2:
            print('uint8')
            x = x.astype(np.uint8)

        return x

loader = torch.utils.data.DataLoader(Dataset(), batch_size=5)
for batch in iter(loader):
    print(batch)

```

This example does run without error (using torch 1.7.0), outputting float64 tensors:

```
tensor([[7.0000, 0.0000, 2.0000, 0.0000, 7.0000, 6.0000, 2.0000, 1.0000, 8.0000,
         9.0000],
        [6.2086, 1.7309, 1.5465, 4.8889, 2.8222, 8.1264, 0.5281, 6.9531, 7.0541,
         2.0879],
        [6.0000, 1.0000, 9.0000, 4.0000, 2.0000, 8.0000, 7.0000, 3.0000, 7.0000,
         5.0000],
        [9.4684, 9.4387, 6.4075, 3.6182, 3.9816, 9.7294, 8.6937, 1.7711, 9.9342,
         2.9880],
        [7.0000, 3.0000, 0.0000, 5.0000, 5.0000, 6.0000, 2.0000, 1.0000, 7.0000,
         4.0000]], dtype=torch.float64)
```

For ScalarImage it could make sense to force float32. Are there transform for LabelMaps that require float?

**Comment by fepegar** [comment]
> This example does run without error (using torch 1.7.0), outputting float64 tensors.

Great. I was using 1.2 ¬¬. Thanks for verifying.

>  For ScalarImage it could make sense to force float32.

I think we could make the transforms responsible for the casting if that will make some of them faster.

> Are there transform for LabelMaps that require float?

I don't think so, this wouldn't be an issue.

**Comment by romainVala** [comment]
Hi
yes there are LabelMaps that need to be float. For instance we work with label map containing partial volume (so a continuous number [0 1]) and it is use in the RandomLabelToimage (and also outsite torchio to compute soft dice)
But then the input nifti file are defined as float datatype

For pure binary mask, it makes sens to keep int as it is much cheaper

May be on could keep the datatype that is in the nifti file ... ?

**Comment by romainVala** [comment]
it you want to force the internal type to int, (whatever is in the nifti) then it should be an option one can change ... no ?

**Comment by fepegar** [comment]
@romainVala I think the proposal is not really forcing a specific type, but stopping forcing everything to be float 32. So your partial volume maps (which maybe shouldn't be instantiated as a label map, as they don't contain categorical labels) would still be processed fine.

**Comment by dmus** [comment]
> I think we could make the transforms responsible for the casting if that will make some of them faster.
Seems like a good option, if a transform requires a specific datatype it is also responsible for the casting

> May be on could keep the datatype that is in the nifti file ... ?
Yes that was indeed the proposal

**Comment by fepegar** [comment]
> Seems like a good option, if a transform requires a specific datatype it is also responsible for the casting

Would you cast the image back to the original dtype it that was the case? This wouldn't make sense for e.g. `ZNormalization`, but maybe it would for e.g. `RandomGamma`. Otherwise, as soon as there's a transform that needs float in a transform composition, the rest of the operations will also use float, making everything slower.

**Comment by dmus** [comment]
Yes, I think it makes sense to cast it back to the original dtype if applicable. So for RandomGamma cast back, but not for ZNormalization

**Comment by fepegar** [comment]
The problem with that is that there will be some information loss when inverting transforms such as RandomGamma or RandomNoise. But I guess that 1) it would be neglible and 2) the casting could be a kwarg in Transform, now that it's easy to add kwargs to the class.

**Comment by dmus** [comment]
Yes there can be a littlebit information loss idd. For my use cases just removing the explicit casting to float in image.py and io.py will also suffice, the main gain will be in the labelmaps
