### ISSUE TITLE
Support for NVIDIA DALI

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#377]
Is there any plan to support [DALI](https://github.com/NVIDIA/DALI)?

Cheers,
Sarthak

**Comment by fepegar** [comment]
Hi, @sarthakpati. No, I haven't thought about anything related to DALI.

**Comment by sarthakpati** [comment]
Oh okay. I have been looking into options on improving the performance of the preprocessing and data loading and hit upon this and was wondering if it would make sense to explore porting this into TorchIO.

**Comment by fepegar** [comment]
We're looking into making things a bit faster in #375. I will also write a FAQ with advice about that. I don't really know much about DALI. I just looked into it once to load videos, but never used it. Do you think there's anything that could be integrated in TorchIO?

Another way to make things faster is looking into transforms of tensors in GPU, but I haven't had the time to investigate that.

**Comment by sarthakpati** [comment]
> I don't really know much about DALI.

I just found out about it ~15 minutes back myself, but I can investigate it in detail and report back.

> transforms of tensors in GPU

That would **definitely** help things...

**Comment by dmus** [comment]
I found a main issue is in queue.py

```
def __getitem__(self, _):
        # There are probably more elegant ways of doing this
        if not self.patches_list:
            self._print('Patches list is empty.')
            self.fill()
        sample_patch = self.patches_list.pop()
        self.num_sampled_patches += 1
        return sample_patch
```
The queue is filled again when the queue is already empty. This results in a gpu utilization like this (this is without augmentation):
![Screenshot from 2020-11-26 19-56-48](https://user-images.githubusercontent.com/464378/101817093-2cb63e80-3b22-11eb-9fd9-d59c29bc1d71.png)

It can be a lot faster if the queue keeps filling itself continuously in the background

**Comment by romainVala** [comment]
if you use a torch dataloader for the queue you can then use num-worker, to have several queue, but it cost num-worker times more memory...

An other try was made here #301 , but it is a bit experimental,

**Comment by fepegar** [comment]
@dmus, the queue is difficult to handle. As @romainVala said, attempts have been made to improve it, but the increase in performance is not clear.

But that is unrelated to this issue, please open a new one if you want to discuss this further.

Closing this for now, feel free to reopen if you want to discuss DALI.
