### ISSUE TITLE
Possibility to use external mask when masking function

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#38]
For some Transform : histogram_standardization rescale z_normalization there may be an interest to use a mask (just to compute percentyl or min max values) then the transform is apply to the all images

This is possible with histogram_standardization (and we should add the option with rescale)

My point is that a masking_function is not an easy job, and I do prefer to use mask compute independently (with your prefered software)

In the case of external mask, you can easily use them by including then in the ImageDataset

```python
suj = [[
    Image('T1','/oneT1.nii.gz',INTENSITY),
    Image('mask','/coresponding_mask.nii.gz',LABEL)
     ]]
```

Then you can use a parameter mask_field_name to get this mask when needed

here is an example of such an implementation 
  https://github.com/romainVala/torchio/blob/master/torchio/transforms/rescale_within_mask.py

but I thing it is better, to directly incorporate it as an optional feature of the Rescale class with something like 

```python
   if sefl.mask_field_name is not None :
       mask_data = sample[self.mask_field_name]['data']
```

About ZNormalization I would prefer to set use_mean_threshold to False by default and add the possiblity to use either a masking_function or the external mask 

For histogram_standardization, a masking_function is expected, (but not use in the call), I added the possibility of external mask 
   https://github.com/romainVala/torchio/blob/master/torchio/transforms/histogram_standardization.py

of course those option are exclusive, and the user should set only one of them, I am not sure what the best way to code it properly, I did something like

```python
    if masking_function is not None:
        mask = masking_function(img)
    else:
        if mask_data is not None:
            mask = mask_data
        else:
            mask = np.ones_like(img, dtype=np.bool)
```

**Comment by fepegar** [comment]
I agree that more flexibility is needed for this. The current implementation inherits some issues from NiftyNet. I'll work on this soon.
