### ISSUE TITLE
3d UNet example

### ISSUE THREAD

**Issue by obhutara** [fepegar/torchio#395]
tio.utils does not have sitk_to_nib 
The error occurs in the following line in show_subject:

border_array, _ = tio.utils.sitk_to_nib(border)

Please help resolve this. Thanks

**Comment by obhutara** [comment]
Please specify the versions of the packages used in the following tutorial.
https://colab.research.google.com/github/fepegar/torchio-notebooks/blob/main/notebooks/TorchIO_tutorial.ipynb

**Comment by fepegar** [comment]
Thanks for reporting. Fixed in https://github.com/fepegar/torchio-notebooks/commit/255b06744b065c76eeaad62b447eb224e830d1ef.
