### ISSUE TITLE
Inference with specified Region of Interest 

### ISSUE THREAD

**Issue by meghbhalerao** [fepegar/torchio#396]
Hi everyone, 
I was wondering if there is an option on `torchio` where I can do inference upon an image but with a **specified region of interest**. 

What I am trying to say is: 
1. I have: Torchio `Subject`,  trained `model`, RoI mask `mask.nii.gz`
2. Using this `mask.nii.gz`, I will find a bounding box, and only forward pass the bounding box**ed** image through the model (with some padding if necessary - to maintain the downsampled dimensions in the U-Net)

I was wondering if there is any way where I can add the _bounding box_ as another attribute of the `torchio Subject`object and it does inference automatically upon that.

Please let me know if something is not clear.
Thanks,
Megh

**Comment by fepegar** [comment]
> I was wondering if there is any way where I can add the bounding box as another attribute of the torchio Subjectobject and it does inference automatically upon that.

I'm not sure what you mean. You can add any attributes to `Subject`, e.g., `subject = tio.Subject(im=tio.ScalarImage(path), roi=bounding_box)`.

You might find the `mask_name` kwarg of [`CropOrPad`](https://torchio.readthedocs.io/transforms/preprocessing.html#torchio.transforms.CropOrPad) useful. You can also use `Resample` with the original image as reference, to have the inference back in the original space (the full image bounds). I hope that helps.

**Comment by meghbhalerao** [comment]
Thank you @fepegar, I think the crop/pad function would solve my problem - I can give a mask as a `LabelMap` and use the `croporpad` method to crop the image and then forward pass it. 
Thanks again

**Comment by fepegar** [comment]
No worries!

**Comment by meghbhalerao** [comment]
Hi @fepegar,
I get the following error when I am trying to apply the `CropOrPad` Transform on my `Subject` Object.
```python
RuntimeError: If input is a dictionary, a value for "include" must be specified when instantiating the transform
```
I am instantiating my `transform` as follows:
```python
transform = torchio.CropOrPad(roi_shape, mask_name='roi_mask')
transformed = transform(subject)
```

I searched the documentation for the [`CropOrPad` ](https://torchio.readthedocs.io/transforms/preprocessing.html#croporpad) transform, but I do not seem to find the `include` parameter anywhere.

My `Subject` is a dictionary with the following keys: `['1', '2', '3', 'label', 'path_to_metadata', 'roi_mask']`

Please do let me know if I am missing something.
Thanks for your help,
Megh

**Comment by fepegar** [comment]
Hi, @meghbhalerao. Please, open a new issue if there is a new question. `include` is defined in `Transform`. From the [documentation](https://torchio.readthedocs.io/transforms/preprocessing.html#croporpad):

> **kwargs – See Transform for additional keyword arguments.

**Comment by fepegar** [comment]
Is there a reason why you are using a `dict` instead of a TorchIO `Subject`?

**Comment by meghbhalerao** [comment]
Thanks for your reply, @fepegar. I will open a new issue as this could happen for other transforms as well. 
Thanks,
Megh
