### ISSUE TITLE
Label transformations

### ISSUE THREAD

**Issue by efirdc** [fepegar/torchio#400]
## **🚀 Feature**

Currently working on a `RemapLabels` transformation for `LabelMap`s as well as two derivative transformations: `RemoveLabels` and `SequentialLabels` . Would be happy to submit a PR for this if there is interest.

`RemapLabels` takes a `remapping: Dict[int, int]` which specifies how labels should be remapped. This only changes the underlying integer IDs of a class. For example `remapping={20:1, 2:3, 3:2, 4:0}` would remap 20 to 1, swap 2 and 3, and remove 4 by setting it to background.

`SequentialLabels` will make all labels sequential. For example if you have a label map with labels `2, 9, 10, 15, 16`, this will remap them to `1, 2, 3, 4, 5`. This transform would just apply a `RemapLabels` transform with `remapping={2:1, 9:2, 10:3, 15:4, 16:5}`.

`RemoveLabels` takes a list of labels and maps them all to zero. This will also reuse `RemapLabels`. It could take an option to specify which label is considered background. Although I doubt anyone would use something other than zero. 

Invertibility is easily supported for `RemapLabels` by swapping keys and values for `remapping`. This would also automatically make `SequentialLabels` invertible as well. The main purpose of `RemoveLabels` would be to disable invertibility when remapping classes to background.

There is another more difficult use case I would like to support of combining two labels into a single label, and then separating them again in the inverse pass. This would require an additional `masking_method` parameter.

## **Motivation**

Currently working with a dataset that has quite a few labels for deep gray matter structures:
```python
label_names={'left_ventricle': 1, 'right_ventricle': 2, 'left_caudate': 3, 'right_caudate': 4, 'left_putamen': 5, 'right_putamen': 6,
                      'left_thalamus': 7, 'right_thalamus': 8, 'left_globus_pallidus': 9, 'right_globus_pallidus': 10, 'internal_capsule': 17,
                      'left_red_nucleus': 19, 'right_red_nucleus': 20,'left_substantia_nigra': 21, 'right_substantia_nigra': 22, 
                      'left_dentate_nucleus': 23, 'right_dentate_nucleus': 24}
```
As you can see they are all split into left/right classes and there are a lot of gaps between the label numbers. This is the desired transformation pipeline:

```python
transforms = tio.Compose([
    RemoveLabels([1, 2, 17, 23, 24]),
    RemapLabels({4:3, 6:5, 10:9, 20:19, 22:21})
    SequentialLabels(),
])
```

which would remove the ventricles, internal capsule, and dentate nucleus. Then `RemapLabels` combines left/right for the remaining structures (except thalamus), and finally they are made sequential with `SequentialLabels`. The final labels would be in a much better state for training a segmentation network. Having labels ready in sequential order is usually desired since that is what a network will output after doing an argmax on probability maps. Also combining left/right is usually a good idea since there would be a lot of wasted bandwidth and potential mistakes with separate labels.

Supporting inverse transforms will make it very convenient to put the labels back into the format from the dataset. As mentioned before, splitting the labels back into left/right correctly could be done with a mask option for `RemapLabels`. Without a mask the inverse would just switch everything to right side labels instead of left side.

## **Pitch**

`RemapLabels`  inherits `Transform`  
`SequentialLabels` inherits `Transform`, favors composition and constructs `RemapLabels` when the transformation is applied.
`RemoveLabels` inherits `RemapLabels`, remapping is created in the constructor and invertibility is overloaded to false.

It would make sense to reuse the `masking_method: TypeMaskingMethod` from the normalization transforms. The current supported methods for masking with functions or other label maps are good, but I think it would also be great to support two new options:

- Masking based on anatomical labels like in `RandomFlip`, i.e. `'Left'`, `'Right'`, `'Anterior'`, `'Posterior'`, `'Inferior'`, `'Superior'`. Would set the mask to that half of the volume. There is a potential conflict if a label map matches one of the anatomical labels but I think its alright if one method has priority.
- Generating a mask from a `TypeBounds`, i.e. `TypeMaskingMethod = Union[str, TypeCallable, TypeBounds, None]`, if slightly finer control is needed.

This would move `TypeBounds` and `TypeMaskingMethod` definitions up to the `Transform` class, along with most of their related code so the functionality can be shared.

**Comment by fepegar** [comment]
Hi again, @efirdc. I think this makes a lot of sense and would be a great contribution. Looking forward to that PR! Let me know if I can help.
