### ISSUE TITLE
RuntimeError: If input is a dictionary, a value for "include" must be specified when instantiating the transform

### ISSUE THREAD

**Issue by meghbhalerao** [fepegar/torchio#412]
Hi @fepegar,
I get the following error when I am trying to apply the `CropOrPad` Transform on my `Subject` Object.
```python
RuntimeError: If input is a dictionary, a value for "include" must be specified when instantiating the transform
```
I am instantiating my `transform` as follows:
```python
transform = torchio.CropOrPad(roi_shape, mask_name='roi_mask')
transformed = transform(subject)
```

I searched the documentation for the [`CropOrPad` ](https://torchio.readthedocs.io/transforms/preprocessing.html#croporpad) transform, but I do not seem to find the `include` parameter anywhere.

My `Subject` is a dictionary with the following keys: `['1', '2', '3', 'label', 'path_to_metadata', 'roi_mask']`

Please do let me know if I am missing something.
Thanks for your help,
Megh

**Comment by meghbhalerao** [comment]
Pertaining to this: https://github.com/fepegar/torchio/issues/396#issuecomment-753646425 - I am initially creating a dictionary called `subject_dict`  and then wrapping it with `torchio.Subject(subject_dict)` so that it _becomes a torchio Subject object._

**Comment by fepegar** [comment]
Thanks for opening this new issue. Can you share the code where you instantiate the subject? A minimal working example would be ideal. What is the result of running `type(subject)`?

**Comment by meghbhalerao** [comment]
Sure, here is the code to instantiate the subject:
```python
subject_dict = {}
channelHeaders = [1,2,3] 
for channel in channelHeaders:
        subject_dict[str(channel)] = Image(str(dataframe[channel][patient]), type=torchio.INTENSITY)
subject_dict['label'] = Image(str(dataframe[labelHeader][patient]), type=torchio.LABEL)
subject_dict['path_to_metadata'] = str(dataframe[labelHeader][patient])
subject_dict['roi_mask'] = Image(str(dataframe[roiHeader][patient]),type=torchio.INTENSITY)
subject = Subject(subject_dict)
```
When I do `type(subject)`, I get:
```python
<class 'torchio.data.subject.Subject'>
```

**Comment by fepegar** [comment]
I am not sure why you are getting that message. Could you please provide a minimal working example that I can run on my computer to reproduce your error?

**Comment by fepegar** [comment]
I tried this to reproduce, but I get no error:

```python
import torch
import torchio as tio

subject_dict = {}
channelHeaders = [1,2,3]
subject_dict['1'] = tio.ScalarImage(tensor=torch.rand(1, 2, 3, 4))
subject_dict['label'] = tio.LabelMap(tensor=torch.rand(1, 2, 3, 4))
subject_dict['path_to_metadata'] = 'path'
subject_dict['roi_mask'] = tio.LabelMap(tensor=torch.rand(1, 2, 3, 4))
subject = tio.Subject(subject_dict)
tio.CropOrPad((2, 2, 2))(subject)
```

Note that 
1. You can use `ScalarImage` and `LabelMap` instead of `Image`
2. You are using a scalar-valued for a mask. Should it be a label map instead?

**Comment by meghbhalerao** [comment]
Hi @fepegar,
Sorry for my delayed reply. Thanks for your detailed reply. 
I got this to work. 
Thanks,
Megh

**Comment by fepegar** [comment]
Great! Can you please share your solution so the community can benefit?

**Comment by meghbhalerao** [comment]
Sure! Here is the way to use the `include` parameter while using `CropOrPad` function:
```python
subject_dict['1'] = tio.ScalarImage("path/to/image")
subject_dict['roi_mask'] = torchio.LabelMap("path/to/roi")
subject_dict['path_to_metadata'] = "path/to/metadata"
subject = torchio.Subject(subject_dict)
roi_shape = subject['roi_mask']['data'][0].shape
transform = torchio.CropOrPad(roi_shape, mask_name='roi_mask',include=['1','roi_mask'])
transformed = transform(subject)
```

**Comment by fepegar** [comment]
Thanks, @meghbhalerao.
