### ISSUE TITLE
Add option to ignore intensity images when inverting transforms

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#416]
**🚀 Feature**

**Motivation**

Typically, transforms need to be inverted for test-time augmentation or aleatoric uncertainty estimation. In this cases, we want to apply the inverse spatial and label transforms, but not the intensity. For example, we wouldn't want to remove from the probabilities the noise applied to the MRI.

**Pitch**

Add an option to ignore (by default!) intensity transforms when getting the composed inverse.

**Alternatives**

Removing them by hand, looking into the `transforms` attribute of the return `Compose` transform.

**Comment by dmus** [comment]
I see the use case that adding noise should not be inverted. However, how about the Normalization transform (RescaleIntensity for example). For regression problems that should be included when doing the inverse transform

**Comment by fepegar** [comment]
I suppose that would be a specific usage, in which case, the user will still be able to get the inverse using the kwarg. I'm opening a PR.

PS: normalization transforms are not invertible yet.
