### ISSUE TITLE
Add high-level brain MRI transforms for preprocessing

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#428]
**🚀 Feature**

Add some high-level brain MRI transforms for preprocessing.

**Motivation**

Arguably, there are three preprocessing steps performed on most multimodal neuroimaging studies:
1. Coregistration of the different modalities
2. Brain segmentation/skull-stripping
3. Registration to a reference space, typically MNI

I typically use [NiftyReg](https://github.com/KCL-BMEIS/niftyreg) for registration and [ROBEX](https://www.nitrc.org/projects/robex) for brain extraction. As discussed with @ReubenDo, other modern, robust and more Python-friendly tools that could be used for this are [SimpleElastix](https://simpleelastix.github.io/) or [ANTsPy](https://antspy.readthedocs.io/en/latest/) for registration and [HD-BET](https://github.com/MIC-DKFZ/HD-BET) for brain extraction, similar to what's done in [MRIPreprocessor](https://github.com/ReubenDo/MRIPreprocessor).

A related transform that might be useful is a defacing transform. The simplest way to do this is using a mask defined in the MNI space, therefore this is very related to the MNI registration.

**Pitch**

Add new preprocessing transforms, not meant to be used during training. Some ideas: `BrainExtraction`, `ToMNI`, `Coregister`. The requirements would be optional, rising an error with an informative message asking the user to install them using `pip`.

@romainVala, do you think this would be useful?

**Comment by sarthakpati** [comment]
I would also recommend adding a `ToSRI` transform, as the [SRI template](https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.20906) is also heavily used, especially in BraTS (and related studies).

**Comment by romainVala** [comment]
BUT there are case where there may be no other choice
For instance multimodal input, You may need to coregister the inputs volumes
Recently I get some strange result with nifty reg and I finally wen with fsl flirt utility, but I have heard several times of SimpeElastix, which is wildly use in other than MR communiity
It seems to bee versy fast, so I will be interested to test it

The main advantage to include it in torchio, is to automatically handel the write to file if needed (for nifty reg) but would be nice to have a solution with memory map (may be possible with SimpleElaxtix ?)

I recently came to an issue where I need to do a coregistration (motion corrupted volume, have a global displacement regard to original volume, and I am still unsucess to  predict it, (despite the Shaw proposition)

**Comment by fepegar** [comment]
These would be utilities for preprocessing before training, for convenience. Each transform could have different backends, to use the user's preferred method.

Here is some code I adapted from [MRIPreprocessor](https://github.com/ReubenDo/MRIPreprocessor): 

https://github.com/fepegar/resseg/blob/06b28889d65780eadc07a405c695598dcb028bbb/resseg/cli/resseg_mni.py#L19-L39

**Comment by romainVala** [comment]
I have some use-case too where I need to register 2 images
for now I just build the fsl filrt command line and then used python subprocess.run
which make the job very quickly
I could also have used fslpy which make wrapper of some fsl function to python (similar to ants)

But what the goal next, to make a proper torchio transform (your example is just a main function ... ) ?
should we made one transform for each tools (ants, fsl ...) or a generic one,
How to deal with output directories (such command line often need the data on the disk, which mean we need to write the data (if it comes from a torchio transform too)  and read the result from disk get back the result in the torchio subject ?
How deep do we go with all parameters ... a way to get it flexible ?

seems a good idea to me, but I am affraid it will ask a lot of dev ... ?

**Comment by romainVala** [comment]
for the same reason as, you, ...
Even if you stay with your specific case, there is no perfect tool for the 2 task, so since it will failled some times, I would like to test other tools, or more control over the parameters ... 

and about registration I need to register the motion corrupt image with the original one, so I add it now within my torchio transform but it looks like dirty code ...

**Comment by fepegar** [comment]
> for the same reason as, you, ...

Well, I wouldn't use TorchIO as a generic registration tool.

> Even if you stay with your specific case, there is no perfect tool for the 2 task, so since it will failled some times, I would like to test other tools, or more control over the parameters ...

Sure, that could maybe be controlled with different backends contributed by users and custom `kwargs` for each one.

> and about registration I need to register the motion corrupt image with the original one, so I add it now within my torchio transform but it looks like dirty code ...

Aren't you adding the artifacts yourself? Why do you need registration?

**Comment by romainVala** [comment]
I agree TorchIO is not meant to be a generic registration tool, but since you have a use case, you will need some genericity. I think we agree on that. (one just need to define how generic it will be)
Once you have a coregistration to mni, then why not allow a coregistration to a given image, (this is just an additional input parameter to change, (path to a template in your case, and 'image_key' to torchio subject in my case)

When working with multichannel images (T1 T2 ect ...) one may wish that all channel are realign before going to a deep network. This make sense that the voxel values need to be realign in order to gain information of multicontrast inputs
(I just reviewed a Billot synthetic and Super Resolution work on neuroimage and this is indeed the only preprocessing needed)
 
Motion corruption is a an other case may be more specific:  I can not find a theoretical solution to perfectly demean the motion time course, and I do observer coregistration misalignment between the original and the artifacted volume. I already discuss there #85 . I test the solution published by Shaw but it is an approximation ... 
Since I want to learn the motion artefact (at the voxel level, or at the volume level with global difference metric (L1 L2 ...) I do not want to have global displacement. (the regression task of my network is then to learn this metric difference, (motion severity)

**Comment by romainVala** [comment]
and @GReguig  or I will also do a PR for a new motion transform, (with coregistration, among other adds)
but still a few things to finish first ...

**Comment by ryancinsight** [comment]
I personally highly recommend SimpleElastix:

`        def make_affine(image):
            # get affine transform in LPS
            affine = np.eye(4,dtype=np.float64)
            affine[:3, :3] = np.array(image.GetDirection()).reshape(3, 3).__imul__(np.array(image.GetSpacing()))
            affine[:3, 3] = image.GetOrigin()
            return affine
        def elastix_affine(foundTrnPath: str = None):
            with open(foundTrnPath, "r") as f:
                for line in f:
                    if "(TransformParameters" in line:
                        params = np.array(
                            line.split("ers ")[1].split(")")[0].split(" "), np.float64
                        )
                    if "(CenterOfRotationPoint" in line:
                        cnt = np.array(
                            line.split("int ")[1].split(")")[0].split(" "), np.float64
                        )
            trn = sitk.Euler3DTransform()
            trn.SetParameters((params[0], params[1], params[2], 0, 0, 0))
            C = np.matrix(np.array([[cnt[0]], [cnt[1]], [cnt[2]]]))
            M = np.eye(4,dtype=np.float64)
            M[:3, :3] = np.matrix(np.reshape(np.array(trn.GetMatrix(),dtype=np.float64), [3, 3],order='F'))
            M[:3, 3:4] = C - M[:3, :3] * C - M[:3, :3] * np.matrix(np.array([[params[3]], [params[4]], [params[5]]]))
            return M        def make_affine(image):
            # get affine transform in LPS
            affine = np.eye(4,dtype=np.float64)
            affine[:3, :3] = np.array(image.GetDirection()).reshape(3, 3).__imul__(np.array(image.GetSpacing()))
            affine[:3, 3] = image.GetOrigin()
            return affine
        def elastix_affine(foundTrnPath: str = None):
            with open(foundTrnPath, "r") as f:
                for line in f:
                    if "(TransformParameters" in line:
                        params = np.array(
                            line.split("ers ")[1].split(")")[0].split(" "), np.float64
                        )
                    if "(CenterOfRotationPoint" in line:
                        cnt = np.array(
                            line.split("int ")[1].split(")")[0].split(" "), np.float64
                        )
            trn = sitk.Euler3DTransform()
            trn.SetParameters((params[0], params[1], params[2], 0, 0, 0))
            C = np.matrix(np.array([[cnt[0]], [cnt[1]], [cnt[2]]]))
            M = np.eye(4,dtype=np.float64)
            M[:3, :3] = np.matrix(np.reshape(np.array(trn.GetMatrix(),dtype=np.float64), [3, 3],order='F'))
            M[:3, 3:4] = C - M[:3, :3] * C - M[:3, :3] * np.matrix(np.array([[params[3]], [params[4]], [params[5]]]))
            return M`

**Comment by fepegar** [comment]
I think these are out of scope for this library.
