### ISSUE TITLE
Custom image loader 

### ISSUE THREAD

**Issue by vijaypshah** [fepegar/torchio#437]
Hi,

Thank you for developing a wonderful imageIO loader for medical images.
How can I write my own customer image loader for TorchIO?

Best Regards,
Vijay

**Comment by fepegar** [comment]
Hi, @vijaypshah. Thanks for your kind words.

What kind of image do you want to load? TorchIO is built on top of ITK and
NiBabel, which have support for a wide range of formats.

**Comment by vijaypshah** [comment]
Hi @fepegar,

We have our own internal image writer and reader that are not supported by open source.
One solution I could think was to load the image in tensor and then create torchio.ScalarImage using tensor and affine matrix. But that will not be lazy loading, I believe because I need tensor loaded. 

I was just wondering if I could create customer loader and have in my package  so that when I call torchio.ScalerImage  with that particular file type it will load image using my reader. I kind of see that I need to add function in io.py file to actually read my own file format but if I modify io.py file which may not be good as any update will remove my changes. 

Best Regards,
Vijay

**Comment by fepegar** [comment]
Ok, I see. I suppose you can inherit from e.g. `ScalarImage` and override the `read_and_check` method, which takes a path and returns a 4D PyTorch tensor and a 4x4 affine transform. If you don't care about image orientation etc., the transform can just be `numpy.eye(4)`.

```python
import numpy as np
import torchio as tio

class CustomImage(tio.ScalarImage):
    def read_and_check(self, path):
        tensor = torch.random.rand(3, 4, 5, 6)  # your code to read images here
        affine = np.eye(4)
        return tensor, affine

image = CustomImage('path')

**Comment by vijaypshah** [comment]
Great! Thank you! Works like a charm!

Best Regards,
Vijay
