### ISSUE TITLE
RTD 404 in EPISURG dataset description

### ISSUE THREAD

**Issue by NMontanaBrown** [fepegar/torchio#447]
**🐛Bug**

For the [EPISURG](https://torchio.readthedocs.io/datasets.html#torchio.datasets.episurg.EPISURG) medical imaging dataset, you point out that by using the dataset the users must agree and cite the appropriate papers according to the Data use agreement. Clicking on the [provided link](https://torchio.readthedocs.io/EPISURG) leads to a 404.

**To reproduce**

Navigate to the torchio.dataset.episurg RTD entry [here](https://torchio.readthedocs.io/datasets.html#torchio.datasets.episurg.EPISURG). Click on [" UCL Research Data Repository "](https://torchio.readthedocs.io/EPISURG).

**Expected behavior**

I assume that this is meant to link to the following, but authors of the EPISURG data might be able to correct me..?

[EPISURG dataset with a data use agreement section](https://rdr.ucl.ac.uk/articles/dataset/EPISURG_a_dataset_of_postoperative_magnetic_resonance_images_MRI_for_quantitative_analysis_of_resection_neurosurgery_for_refractory_epilepsy/9996158/1)

**Actual behavior**

Get 404, page doesn't exist.

**TorchIO version**

N/A

**Comment by fepegar** [comment]
Thanks, @NMontanaBrown. Good catch! Thankfully, I am the author of EPISURG :)

@all-contributors please add @NMontanaBrown for doc.
