### ISSUE TITLE
Advice to create a new dataset

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#461]
Hi everyone ! 

**🚀 Feature**
I would like to create a dataset, of partial volume brain mask from the 600 hcp subject

Not sure if I is the right place, but I am looking for advice on how to do this (since I saw you link to new dataset)

**Motivation**

this will be a nice dataset, to start with for training from synthetic data. The originality is that this is not standard binary mask, but they contain partial volumes (computed with toblerone, from freesurfer surfaces) and so it is suited to work with ideal data.

**Additional context**
I ask the HCP (Elam Jennifer) and get a positive response
 
"Resharing derived data is allowed as long as you Cite the HCP (https://www.humanconnectome.org/study/hcp-young-adult/document/hcp-citations)  and refer users to the HCP Data Use terms (https://www.humanconnectome.org/study/hcp-young-adult/document/wu-minn-hcp-consortium-open-access-data-use-terms). One way to easily share derived data under the HCP terms is by creating Connectome Workbench scene files with the data and sharing on the BALSA database (https://balsa.wustl.edu/)." 

so she suggest me the BLASA database, but here it is not exactly group results, but such subject mask that may be usefull for torchio users

**Comment by fepegar** [comment]
> Not sure if I is the right place, but I am looking for advice on how to do this

Hi @romainVala. What do you need?

**Comment by romainVala** [comment]
information about how to do it ... 
where to put the data, (how to associate the licences)
where to put it, 

can I put them directly in torchio ?

**Comment by fepegar** [comment]
This is not very related to a preprocessing and augmentation library. The [datasets classes in TorchIO](https://torchio.readthedocs.io/datasets.html) are there for convenience, but most are stored somewhere else.

I'll email you.
