### ISSUE TITLE
Resample causes indifference between image and label shape

### ISSUE THREAD

**Issue by DieHumbleX** [fepegar/torchio#465]
On resampling Label shape and image shape do not match

Shapes after Resample:
Segment_Label->(1, 126, 126, 91)
Ct_image->(1, 126, 126, 90)

```
one_subject = dataset[3]
cano =  tio.ToCanonical()
x = cano(one_subject)
resample = tio.Resample(4)
x = resample(x)
print(one_subject.ct)
print(one_subject.seg)
print(x.ct)
print(x.seg)
```

ScalarImage(shape: (1, 512, 512, 120); spacing: (0.98, 0.98, 3.00); orientation: LPS+; memory: 60.0 MiB; dtype: torch.ShortTensor)
LabelMap(shape: (1, 512, 512, 120); spacing: (0.98, 0.98, 3.00); orientation: LPS+; memory: 60.0 MiB; dtype: torch.ShortTensor)
ScalarImage(shape: (1, 126, 126, 90); spacing: (4.00, 4.00, 4.00); orientation: RAS+; memory: 2.7 MiB; dtype: torch.ShortTensor)
LabelMap(shape: (1, 126, 126, 91); spacing: (4.00, 4.00, 4.00); orientation: RAS+; memory: 2.8 MiB; dtype: torch.ShortTensor)

**Comment by fepegar** [comment]
Hi, @DieHumbleX. Your images are probably not in the same space. Can you verify that `np.allclose((one_subject.ct.affine, one_subject.seg.affine))`?

You could use `Resample` with the ct as target, to make sure that the segmentation is in the space of the CT, and then resample to spacing 4 mm.

**Comment by DieHumbleX** [comment]
<img width="606" alt="Screenshot 2021-02-12 at 11 40 33 PM" src="https://user-images.githubusercontent.com/13509194/107805698-c05af400-6d8b-11eb-818c-a2b9008ffba9.png">
<img width="1016" alt="Screenshot 2021-02-12 at 11 50 31 PM" src="https://user-images.githubusercontent.com/13509194/107806662-24ca8300-6d8d-11eb-955b-8733f7f024a4.png">

Thanks @fepegar for lightning fast response.
yes there was bit difference in affine. It worked.

I am new to working with Dicom data. i am trying to train a tumor segmentation model using non contrast CT data (HN1 dataset). do you think this affine mismatch should be a cause of concern in anyway? as of now my 3D unet model is not converging. could this be the problem or non-contrast CT as just not good enough for segmentation? your input on this will be highly appreciated.

**Comment by fepegar** [comment]
This is a tiny difference, maybe due to the conversion from DICOM. You don't need to worry about that.

There could be many reasons for your networking not converging. Dataset too small, inappropriate preprocessing, bugs in the implementation...

Good luck!
