### ISSUE TITLE
What transform I should have in order to use LabelSample

### ISSUE THREAD

**Issue by vankhoa21991** [fepegar/torchio#481]
Hello, I run into this issue while creating dataloader using torchio. I defined a sampler with LabelSampler, and it gives me this error:

```python-traceback
RuntimeError: Empty probability map found: ...
Voxels with positive probability might be near the image border.
If you suspect that this is the case, try adding a padding transform
```

The transform I'm using is 

```python
training_transform = tio.Compose([
    tio.ToCanonical(),
    tio.Pad(int(patch_size[0]/2)),
    tio.CropOrPad(patch_size),
    tio.ZNormalization(masking_method=tio.ZNormalization.mean),
    tio.OneHot(3),
])
```

I means I have to pad after cropandpad?

Thanks

**Comment by vankhoa21991** [comment]
Thanks for the answer, I tried that and it's blocking my cpu usage, and very slow to create the dataloader. My size is cubic 64x64x64, the whole dataset is about 100 volume with size 300x300x300 in average.

**Comment by vankhoa21991** [comment]
It means that I might fact CPU bound when run training?

**Comment by fepegar** [comment]
Are you using the Queue? Can you share some code? What's the resolution of your images? 300^3 is quite big.

**Comment by vankhoa21991** [comment]
Yes I'm using Queue, but 300^3 is not so big in medical image, and I'm already downsampling before

label_prob = {1: 0.5, 2:0.5}
            sampler = tio.data.LabelSampler(self.patch_size, label_name='mask', label_probabilities=label_prob)
            self.max_queue_length = 300
            self.samples_per_volume = 5

            self.patches_training_set = tio.Queue(
                subjects_dataset=self.training_set,
                max_length=self.max_queue_length,
                samples_per_volume=self.samples_per_volume,
                sampler=sampler,
                num_workers=self.num_workers,
                shuffle_subjects=True,
                shuffle_patches=True,
            )

            self.patches_validation_set = tio.Queue(
                subjects_dataset=self.validation_set,
                max_length=self.max_queue_length,
                samples_per_volume=self.samples_per_volume,
                sampler=sampler,
                num_workers=self.num_workers,
                shuffle_subjects=False,
                shuffle_patches=False,
            )

**Comment by fepegar** [comment]
[Please use [syntax highlighting](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) for code snippets]

Given the size of your volumes and patches, I suggest using a larger number of samples per volume, maybe 30 or 50. That will be less computationally expensive, as you will need to load and transform volumes less often.

**Comment by vankhoa21991** [comment]
THanks for the suggestion, it does not block like before, but sometime it crash on notebook (dataloader crash due to running out of memory). I will run training again to see if it's faster.

**Comment by fepegar** [comment]
In that case, you might want to lower the `max_queue_length`.

**Comment by vankhoa21991** [comment]
Hello, 

I read the document and understood about it's function, but I'm still unable to use Queue and LabelSampler for training. The phenomenom I observed is the RAM is full very quickly, and after the RAM is full, the thread seems stop working, or work very little.  My volumes are in nifty, does it affect the read and transform time of each thread?

**Comment by fepegar** [comment]
Can you share some more of your code? How many images per subject are you using? What is the transform? What parameters are you using for the queue and the sampler?

**Comment by vankhoa21991** [comment]
Yes, sure, my pc: 8cores, 32GB RAM, RTX2070

Volume size: ~300^3 nifti
mini batch size: 2
patch: 64^3
number of samples: 10
queue length: 60
num threads: 6
LabelSampler
Augmentations: training_transform = tio.Compose([
        tio.ToCanonical(),
        tio.Pad((int(patch_size[0] / 2))),
        tio.RandomMotion(p=0.2),
        tio.RescaleIntensity(),
        tio.RandomNoise(p=0.5),
        tio.OneOf({
            tio.RandomAffine(): 0.8,
            tio.RandomElasticDeformation(): 0.2,
        }),

So it takes long to prepare a queue, and the RAM is full after first or second queue.

**Comment by vankhoa21991** [comment]
Update: if I change queue lenth to 120 or 150, samples_per_volume to 30, it runs better, but non-use GPU time is still high.

**Comment by fepegar** [comment]
How many images per subject do you have? I think the main issue is that you are applying two very slow transforms, `RandomMotion` and (sometimes) `RandomElasticDeformation`, to one or more images of size 364 x 364 x 364. If you do that with all 8 cores, it will be quite computationally intense. About GPU time, you'll need to experiment with the different parameters until you get a combination that works for you.

**Comment by vankhoa21991** [comment]
Well, I have only one volume and one mask for one subject. I tried to read in numpy array instead of nifti, the dataloading seems faster, but it crashes when I use patch bigger than 64x64x32, I experienced the same using a server to train model. I removed those two augmentations but the improvement is not much.

**Comment by fepegar** [comment]
Loading with numpy is probably faster because the images are not compressed. You can store your images as .nii, but they will take more storage. I don't know what you mean by "it crashes".
