### ISSUE TITLE
NormalisationTransform has no attribute masking_method

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#49]
I get an error with
transfo = Compose(( Rescale(masking_method='mask', verbose=True),))

In the init of NormalizationTransform you use self.masking_method
but it is not assign

**Comment by romainVala** [comment]
it is not assign if you use a strin as argument

**Comment by fepegar** [comment]
Fixed in `v0.11.3`. Thanks, @romainVala

**Comment by fepegar** [comment]
By the way,

1. Are you using `Rescale` for CT data?
2. You don't need to use `Compose` if you only have one transform

**Comment by romainVala** [comment]
Ok pour Compose, (I though it was mandatory)

I do not work with CT data, I use rescale to have number between 0 and 1 (by the way I would change the default for out_min_max  0 1

Currently I do not undersand, why I get value between 1 and 3 instead of value between -1 1 ... (but it woks fine if I ask fo (0,1) ...

**Comment by romainVala** [comment]
Instead of 
        array -= self.out_min  # [out_min, out_max]
it should be
        array += self.out_min  # [out_min, out_max]

**Comment by fepegar** [comment]
Thanks again! I definitely need to write some unit tests...

**Comment by fepegar** [comment]
Is there a strong reason to choose (0, 1) over (-1, 1)?

**Comment by fepegar** [comment]
I'd like to make this implementation look more like https://github.com/scikit-image/scikit-image/blob/master/skimage/exposure/exposure.py#L269

**Comment by romainVala** [comment]
I do not know if it makes a difference from a CNN point of view. ... ?

It is just that mri is usually always positive (see https://github.com/fepegar/torchio/issues/37#issuecomment-572929791)

Other point may be, after masking you usually get voxel value to zero in the background, so normalizing to -1 1 will break it ...

but not a big deal it is just the default value, easy to change
