### ISSUE TITLE
LabelSampler can give 0 probability sample

### ISSUE THREAD

**Issue by TylerSpears** [fepegar/torchio#510]
**🐛Bug**
The `LabelSampler` and `WeightSampler`s can generate patches that have 0 probability according to the probability map, failing the `assert` statement in [line 243](https://github.com/fepegar/torchio/blob/76fa773ec52273bfc3254f3afc5bf3170205dedf/torchio/data/sampler/weighted.py#L243).

I'm pretty sure this happens because the random number in [line 228](https://github.com/fepegar/torchio/blob/76fa773ec52273bfc3254f3afc5bf3170205dedf/torchio/data/sampler/weighted.py#L228) can have a value of exactly 0, given enough samples. Then, the call to `np.searchsorted` finds the 0th patch from the `cdf`, giving a patch centered at `(0, 0, 0)`. This then fails the `assert` statement in line 243.

I think this can be fixed by just ensuring the `random_number` cannot be exactly 0:

```python
random_number = max(torch.rand(1).item(), torch.finfo(torch.float32).eps)
```

**To reproduce**

This cannot be quickly reproduced, as the `torch.rand(1)` call must generate a value of exactly 0.0. This can happen given enough iterations (hundreds of millions, in my case), or you can just manually inject a value of 0 for the `random_number`.

Tweaking the `LabelSampler` example code:

```python
import pdb
import torchio as tio
subject = tio.datasets.Colin27()
probabilities = {0: 0, 1: 0.5}
sampler = tio.data.LabelSampler(
    patch_size=64,
    label_name="brain",
    label_probabilities=probabilities,
)
generator = sampler(subject)
pdb.set_trace()
for patch in generator:
    continue
```

Then interacting with pdb:

```
python label_sample_bug.py
-> for patch in generator:
(Pdb) b [torchio install location]/torchio/data/sampler/weighted.py:230
Breakpoint 1 at /opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py:230
(Pdb) c
> /opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py(230)sample_probability_map()
-> if random_number > cdf.max():
(Pdb) random_number = 0
(Pdb) c
Traceback (most recent call last):
  File "label_sample_bug.py", line 12, in <module>
    for patch in generator:
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 78, in __call__
    yield self.extract_patch(subject, probability_map, cdf)
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 186, in extract_patch
    index_ini = self.get_random_index_ini(probability_map, cdf)
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 196, in get_random_index_ini
    center = self.sample_probability_map(probability_map, cdf)
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 243, in sample_probability_map
    assert probability > 0
AssertionError
```

**Expected behavior**

In a real-world case, expected a to pass the `assert` check and have a sample with probability > 0.

**Actual behavior**

Failed the `assert` statement.

Traceback is given above, but: 
```python-traceback
Traceback (most recent call last):
  File "label_sample_bug.py", line 12, in <module>
    for patch in generator:
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 78, in __call__
    yield self.extract_patch(subject, probability_map, cdf)
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 186, in extract_patch
    index_ini = self.get_random_index_ini(probability_map, cdf)
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 196, in get_random_index_ini
    center = self.sample_probability_map(probability_map, cdf)
  File "/opt/miniconda/envs/pitn/lib/python3.8/site-packages/torchio/data/sampler/weighted.py", line 243, in sample_probability_map
    assert probability > 0
AssertionError
```

**System info**

```
Platform: Linux-5.10.0-6-amd64-x86_64-with-glibc2.10
TorchIO:  0.18.34
PyTorch:  1.8.1
NumPy:    1.20.1
Python:   3.8.8 (default, Feb 24 2021, 21:46:12) 
[GCC 7.3.0]
```

**Comment by fepegar** [comment]
Hi, @TylerSpears. Thank you very much for this excellent report and for the thorough investigation, I really appreciate it. I think your proposal makes sense. Would you like to open a PR to fix this?

By the way, your probabilities for the label sampler are `probabilities = {0: 0, 1: 0.5}`. What are you trying to accomplish? These value makes the sampler to sample patches from label 1 only, as probabilities are normalized. Basically, it's the same as not passing that argument. If you're aiming to sample have the patches from the background and half from the foreground, you should use the same value for both keys in the dictionary.

**Comment by TylerSpears** [comment]
Hi @fepegar, sure thing! I'll send a PR shortly.

For the probabilities, that was just from editing the `LabelSampler` example as little as possible. All I wanted was to give equal probability of sampling the foreground with 0 chance of sampling the background. I could have removed the `probabilities` entirely and gotten the same result, I was just going for a quick example.
