### ISSUE TITLE
Grid Sampler for Training

### ISSUE THREAD

**Issue by MFaizyabAli** [fepegar/torchio#513]
**🚀 Feature**
Several medical imaging tasks require patch-based analyses which are suitable implemented by the random samplers provided in Torch IO.  In some cases, however, it becomes necessary to sample the entire image grid to ensure all image regions are being captured by the model.

For that, I would like to request Grid_Sampler to suitable with the training Queue as well, just like Uniform or other random samplers.

**Comment by fepegar** [comment]
You should be able to use the grid sampler like the other samplers in `v0.18.37`.
