### ISSUE TITLE
Applying DataLoader to PatientDataset returns a Dict instead of a Patient object

### ISSUE THREAD

**Issue by dfioravanti** [fepegar/torchio#514]
**🐛Bug**

If one loads a PatientDataset via Pytorch DataLoader then the resulting object from next(PatientDataset) is a Dict not a Patient. This behaviour makes it impossible to do the following
```python
dataset = PatientDataset(args)
data_loader = DataLoader(dataset)

for patient in data_loader:
  grid_sampler = tio.inference.GridSampler(
     subject, 
     other_args
 )
```
**To reproduce**

```python
import torchio as tio
from torch.utils.data.dataloader import DataLoader

subject = tio.datasets.Colin27()
dataset = tio.SubjectsDataset([subject])
data_loader = DataLoader(dataset)
for subject in data_loader:
    print(type(subject))
```

**Expected behavior**

I would expect the DataLoader to return a Patient object not a Dictionary.

**Actual behavior**

A Dictionary is returned not a Patient object

**Comment by fepegar** [comment]
Hi, @dfioravanti. This is not a TorchIO bug, is a PyTorch feature. If you want to get instances of `Subject` from the data loader, you can use a custom `collate_fn` such as `lambda x: x`. More on `collate_fn` on the [PyTorch docs](https://pytorch.org/docs/stable/data.html#dataloader-collate-fn).

If you want to use a grid sampler for patch-based training, I recommend you subscribe to #513. Also, have you checked the docs on [patch-based training](https://torchio.readthedocs.io/data/patch_based.html)?

**Comment by dfioravanti** [comment]
@fepegar thanks a lot, that does the trick. Yes, I am trying to use the grid sampler but my problem originated when trying to combine TorchIO with PytorchLightning as I need to pass a Dataloader to the Trainer.test() method or everything breaks. #513 looks like a nice improvement. I will subscribe as it will make my life easier here and there

**Comment by fepegar** [comment]
Thanks for the explanation. I'm planning to write a tutorial using TorchIO + PT Lightning. I'll share it here when it's done (if I remember :D).

**Comment by dfioravanti** [comment]
Just FYI, the approach above does not really work. Pytorch lighting wants to move the tensor to the device at the beginning of the training loop so if one passes in a PatientDataset it tries to move a patient object, which cannot be moved, and it crashes. I think that waiting for #513 to be done is the only solution.

**Comment by fepegar** [comment]
Can you please share the error traceback and the relevant associated code?

**Comment by fepegar** [comment]
The tutorial is now up on https://github.com/fepegar/torchio/tree/master/notebooks.

I'll close this for now. Feel free to reopen if you're still having issues.

**Comment by fepegar** [comment]
You should be able to use the grid sampler like the others in `v0.18.37`.
