### ISSUE TITLE
Image interpolation in RandomElasticDeformation

### ISSUE THREAD

**Issue by timroelofs123** [fepegar/torchio#515]
**🐛Bug**
When applying a RandomElasticDeformation on a subject, the image_interpolation is not applied; Instead, "nearest" interpolation is used. (I think it is only the case for RandomElasticDeformation; RandomAffine did not give this same issue)

**To reproduce**
Below is a toy example to illustrate. The image (a 3D zero array with a box of 1s in the center) is deformed. The default settings for RandomElasticDeformation are used, though I wrote the interpolation to be explicit.
The deformed image should have been made using linear interpolation; However, in the tests, it can be seen that nearest interpolation is used instead. 

```python
# toy image
image = np.zeros((1, 100, 100, 100))
image[0, 40:60, 40:60, 40:60] = 1.

# applying the deformation using a Subject
subject = tio.Subject(image=tio.Image(tensor=image))
elastic_transform = tio.RandomElasticDeformation(image_interpolation='linear')
subject = elastic_transform(subject)
deformed_image = subject['image'][tio.DATA].numpy()

# applying the same deformation without a subject
applied_transform = subject.get_composed_history()
applied_transform2 = subject.get_composed_history(image_interpolation='nearest')
deformed_image_linear = applied_transform(image)
deformed_image_nearest = applied_transform2(image)

# testing
print((deformed_image == deformed_image_linear).all()) # Expected True; Returns False
print((deformed_image == deformed_image_nearest).all()) # Expected False; Returns True
```

**Expected behavior and actual behavior**
The code above is expected to return True, False; Instead, it returns False, True, indicating that the interpolation is "nearest".

**System info**

Platform: Linux-5.8.0-50-generic-x86_64-with-glibc2.10
TorchIO:  0.18.30
PyTorch:  1.8.0
NumPy:    1.19.2
Python:   3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]

**Comment by fepegar** [comment]
Hi, @timroelofs123. Thanks for reporting.

I just tried this code and couldn't reproduce:

```python
import torch
import torchio as tio
sheep = tio.datasets.Sheep()
tr = tio.RandomElasticDeformation(image_interpolation='linear')
torch.manual_seed(0)
t = tr(sheep)
t.t1.save('/tmp/linear.nii.gz'
torch.manual_seed(0)
tr = tio.RandomElasticDeformation(image_interpolation='nearest')
t = tr(sheep)
t.t1.save('/tmp/nearest.nii.gz')
```

<img width="704" alt="Screen Shot 2021-04-29 at 09 56 02" src="https://user-images.githubusercontent.com/12688084/116526147-3376ff80-a8d1-11eb-98e4-4d8d0fa6d44b.png">

I'll try your code now.

**Comment by fepegar** [comment]
Ok I think I see what's happening. You're instantiating your image using `tio.Image`. You probably got a warning for that (did you?).

This transform uses nearest neighbor by default when the image class is not `tio.ScalarImage`:

https://github.com/fepegar/torchio/blob/e64e250ddf9637f25442873378ea119df1bbd955/torchio/transforms/augmentation/spatial/random_elastic_deformation.py#L255-L258

Therefore, your `deformed_image` was interpolated using nearest neighbor. Please use `tio.ScalarImage` instead of `tio.Image` and try again.

**Comment by fepegar** [comment]
You probably didn't get the warning because, apparently, [`DeprecationWarning`s are suppressed by default from Python 3.2](https://stackoverflow.com/a/20960427/3956024), which doesn't seem convenient. I will change the warnings.

**Comment by timroelofs123** [comment]
changing to `tio.ScalarImage` indeed fixes it, thanks for the insight!
