### ISSUE TITLE
Mask values outside of a LabelMap

### ISSUE THREAD

**Issue by Svdvoort** [fepegar/torchio#521]
**🚀 Feature**

Have an IntensityTransform that sets values outside of a certain LabelMap to a specific value.

**Motivation**

This can be handy for example for skull-stripping (as also discussed in #428 ) when a brain mask is already available or in general when a foreground mask is available and you want to mask out the 'background'

**Pitch**

Easily use a transform to mask out certain parts of the image.

**Alternatives**

It is possible to do intensity normalization with a mask using the current IntensityTransforms, and these only take into account the values within the mask, but it doesn't seem to be actually possible to set the values outside of the mask. 

**Additional context**

I can implement this feature but wanted to open a request first according to the contributing guidelines and to check whether there's not something that I missed.

**Comment by fepegar** [comment]
Hi, @Svdvoort. Thanks for your proposal. I think this would be helpful.

> I can implement this feature but wanted to open a request first according to the contributing guidelines and to check whether there's not something that I missed.

That's great! And yes, this is the preferred workflow, thanks. I agree it shouldn't be complicated.

Have you thought of how this would work? Maybe an interface similar to the [normalization transforms](https://torchio.readthedocs.io/transforms/preprocessing.html#torchio.transforms.preprocessing.intensity.NormalizationTransform), using `masking_method`?

**Comment by Svdvoort** [comment]
Great! 

Yes, I would just make it a subclass of `NormalizationTransform`, with `masking_method` being a non-optional argument, unless you would prefer a different approach.

**Comment by fepegar** [comment]
I'm not sure this counts as normalization. The masking logic is now in `Transform`, so I'd just make this new transform (`Mask`?) directly inherit from `IntensityTransform`. What do you think?

**Comment by Svdvoort** [comment]
Indeed you're right, `IntensityTransform` is a better start point.  I was doubting between `Mask` and `MaskIntensity` as options. The first might be confusing with the actual LabelMask as a property rather than a function.

**Comment by fepegar** [comment]
> The first might be confusing with the actual LabelMask as a property rather than a function.

I'm not sure I understand.

> I was doubting between Mask and MaskIntensity

I'd say `Mask` is good enough because it already implies intensity. I added it to `RescaleIntensity`, originally called `Rescale`, I believe, because it might be misinterpreted as resampling.

**Comment by Svdvoort** [comment]
See above for the propose pull request.

> I'm not sure I understand.

At first instance I thought there could be some confusion as `Mask` is often used (at least in our institute), to mean with what in torchio is basically a `LabelMap`. For example, a brain mask or a defacing mask. Hence, there could be some confusion about whether it is an 'object' (like the `LabelMap`) or a function/verb, like intended in this case. However, since SimpleITK also just uses `Mask` as the function, I think I agree with you that it is better to just stay with `Mask` as the function name.
