### ISSUE TITLE
Aggregator return error when the tensors in batch are integer tensors.

### ISSUE THREAD

**Issue by alabamagan** [fepegar/torchio#526]
**🐛Bug**
Aggregator return error when the tensors in batch are integer tensors when invoking `get_output_tensor()` in 'average' mode.

**To reproduce**

```python
import torch
import torchio as tio
from torch.utils.data import DataLoader
# create target image
int_im = tio.ScalarImage(tensor=(torch.rand(1, 256, 256, 256) * 65535).type(torch.int32))

# create sampler
subject = tio.Subject(im=int_im)
grid_sampler = tio.GridSampler(subject, patch_overlap=20, patch_size=128)
inference_dl = DataLoader(grid_sampler, batch_size=4)
aggregator = tio.GridAggregator(grid_sampler, 'average')

# sampler and rebuild tensor
for i, mb in enumerate(inference_dl):
    aggregator.add_batch(mb['im'][tio.DATA], mb[tio.LOCATION])
o = aggregator.get_output_tensor()
```

**Simple fix**
aggregator.py
https://github.com/alabamagan/torchio/commit/084caaca5c9b41bcb99aa734e46a2eee43c5a9da
![image](https://user-images.githubusercontent.com/11690091/117642467-e3921580-b1b9-11eb-955e-569617e59eb1.png)

**Expected behavior**

Reconstruct the output integer data array correctly.

**Actual behavior**

Produced an error.

```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-90a464355da2> in <module>()
      8 for i, mb in enumerate(inference_dl):
      9     aggregator.add_batch(mb['image'][tio.DATA], mb[tio.LOCATION])
---> 10 o = aggregator.get_output_tensor()

~/Toolkits/Anaconda2/envs/py3_cuda10/lib/python3.7/site-packages/torchio/data/inference/aggregator.py in get_output_tensor(self)
    163             self._output_tensor = self._output_tensor.type(torch.int32)
    164         if self.overlap_mode == 'average':
--> 165             output = self._output_tensor / self._avgmask_tensor
    166         else:
    167             output = self._output_tensor

RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
```

**System info**

```
Platform: Linux-4.15.0-140-generic-x86_64-with-debian-stretch-sid
TorchIO:  0.18.37
PyTorch:  1.6.0
NumPy:    1.19.1
Python:   3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
**```z**

**Comment by fepegar** [comment]
Hi, @alabamagan. Thanks for reporting.

Could you please upgrade `torch` and try again? I can't reproduce on `1.7.1`.

**Comment by alabamagan** [comment]
Hi I tested on 1.8.0 and got no error. Results are correct except tensor type become float32, but that's manageable.

**Comment by fepegar** [comment]
Thanks for trying. I feel like I'm missing something here, though. Why would you like to average integer values?

**Comment by alabamagan** [comment]
In short, I am working on index arrays and deformation tensor, so they took form of integer tensors during slicing, but I can perform manual casting as long as the pipeline is not broken.

**Comment by alabamagan** [comment]
I didn't notice at first because I was working on integer tensors, but I think changes in be4bf4d to using `true_division` might lead to loss in precision if the averaged images patches are meant to be float values. Might have big impact if the averaged patches are normalized to be ranged from 0-1. Might worth revisiting.
