### ISSUE TITLE
Add exclude/include parameters to transforms kwargs

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#54]
Use case: loading an MRI and CT from the same patients. We probably want very different transforms for each image, but we still want them to happen in the same parallel process.

**Comment by fepegar** [comment]
[@dmus in #330]

> I saw that torchio.Image is inheriting from dict class Image(dict):, so that was leading to some confusion.
I think this is an important feature. Because Image is already inheriting from dict it should not be that much work? Do you have ideas? Maybe I want to contribute, but I am still taking a dive into the codebase

At the moment, transforms are applied to all images by default (although intensity transforms are only applied to scalar images). Maybe the easiest would be to add an `exclude` kwarg in `Transform`. This kwarg will be used within each transform like:

```python
if image_name in self.excluded_images:
    continue
```

**Comment by dmus** [comment]
Will take a look to research it a bit more. I ment Subject is inheriting dict in my previous comment btw

**Comment by fepegar** [comment]
Yes, I understood!

**Comment by fepegar** [comment]
Don't hesitate to ask if you need anything.
