### ISSUE TITLE
Unexpected exception handling

### ISSUE THREAD

**Issue by siahuat0727** [fepegar/torchio#540]
**🐛Bug**

First, thanks for this awesome project!
There is an unexpected exception handling when parsing the image path.

https://github.com/fepegar/torchio/blob/bf0a86fa5832b7236932a6e0cdd0c19c8a6ce724/torchio/data/image.py#L380-L383

I think the implementation here may be better if it is in the following way. Can I send a PR for this?
Is there any other concern? :)

```python
if isinstance(path, Iterable):
    return [self._parse_single_path(p) for p in path]
return self._parse_single_path(path)
```

**To reproduce**

```python
import torchio as tio

tio.Image(0)
```

**Expected behavior**

```python-traceback
TypeError: expected str, bytes or os.PathLike object, not int
```

**Actual behavior**

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/siahuat0727/.local/lib/python3.8/site-packages/torchio/data/image.py", line 141, in __init__
    self.path = self._parse_path(path)
  File "/home/siahuat0727/.local/lib/python3.8/site-packages/torchio/data/image.py", line 383, in _parse_path
    return [self._parse_single_path(p) for p in path]
TypeError: 'int' object is not iterable
```

**Comment by fepegar** [comment]
Hi, @siahuat0727. Thanks for reporting. I think this makes sense. I would still keep the `else` for readability, even though it does nothing. This bit was implemented by @GFabien, so maybe he has more suggestions.

**Comment by GFabien** [comment]
Hi @fepegar. It's been a while! I don't have any suggestions, I think proposition from @siahuat0727 is good.
