### ISSUE TITLE
Why using -1 to handle accumulated floating-point errors

### ISSUE THREAD

**Issue by siahuat0727** [fepegar/torchio#548]
**🐛Bug**

Hi,
I wonder why L227 handles the accumulated floating-point errors using `random_location_index = -1` while `np.unravel_index` can't receive `-1`.

https://github.com/fepegar/torchio/blob/abb7fa1c04156b39f210cfe84974193c400924af/torchio/data/sampler/weighted.py#L223-L234

I think a `random_number` from `[MIN_FLOAT_32, cdf.max()]` or just `[MIN_FLOAT_32, cdf[-1]]` instead of `[MIN_FLOAT_32, 1]` can handle this well.

**Expected behavior**

Always success. (Implicitly handle accumulated floating-point errors)

**Actual behavior**

Maybe:

```python-traceback
ValueError: index -1 is out of bounds for array with size xxx
```

If I'm not mistaken...

**Comment by dvolgyes** [comment]
The reason is that most likely I sent the commit after midnight. :)
It is correct that the unravel cannot handle -1. This is actually strange for me,
I expected `X % size` behavior, just like with indexing in general, but indeed 
it cannot handle it.

I will send a fix soon.

**Comment by dvolgyes** [comment]
On second thought, I don't think actually I was the one introducing the -1, but anyway, I can patch it. :)

**Comment by fepegar** [comment]
Oops! Sorry for the false claim. Apparently, it was actually me who added that in #175. Anyway, thanks for looking into it!
