### ISSUE TITLE
AttributeError: module 'torchio' has no attribute 'ScalarImage'

### ISSUE THREAD

**Issue by r2chel** [fepegar/torchio#557]
**🐛Bug**
When attempting to use torchio for nifti images -  "AttributeError: module 'torchio' has no attribute 'ScalarImage'" 

```python
import torch
import torchio as tio


image = tio.ScalarImage('sub-MDP001_label-GM_probseg.nii')
transform = tio.CropOrPad((320,320,320))
output = transform(image)
```

**Expected behavior**

**Actual behavior**
Traceback (most recent call last):
  File "/home/r2chel/Software/Research/Examples/torchio.py", line 2, in <module>
    import torchio as tio
  File "/home/r2chel/Software/Research/Examples/torchio.py", line 5, in <module>
    image = tio.ScalarImage('sub-MDP001_label-GM_probseg.nii')
AttributeError: module 'torchio' has no attribute 'ScalarImage'
->

Output of `python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)`:

```
# flake8: noqa

import sys
import platform
import torchio
import torch
import numpy

print('Platform:', platform.platform())
print('TorchIO: ', torchio.__version__)
print('PyTorch: ', torch.__version__)
print('NumPy:   ', numpy.__version__)
print('Python:  ', sys.version)```

**Comment by fepegar** [comment]
It looks like there is something wrong with your installation.

What is the output of `import torchio; print(torchio)`?
How did you install `torchio`?

**Comment by fepegar** [comment]
Hopefully, you managed to solve this. Feel free to reopen otherwise.
