### ISSUE TITLE
RandomElasticDeformation doesn't change my image

### ISSUE THREAD

**Issue by Linardos** [fepegar/torchio#565]
Greetings,

I just realized that the elastic deformation I was using, doesn't seem to actually change my images:
![image](https://user-images.githubusercontent.com/26694607/121019913-86818380-c7a8-11eb-8269-122b933a6be9.png)
Note that the image is a torch tensor format. 
![image](https://user-images.githubusercontent.com/26694607/121030854-86868100-c7b2-11eb-9c5b-933680df334e.png)
Could you let me know if there's something wrong with the way I'm using it based on the attached screenshot?

**Comment by fepegar** [comment]
Can you please share that image?

**Comment by fepegar** [comment]
Closing for now. Feel free to reopen if you like.
