### ISSUE TITLE
All cpu cores (64) get occupied

### ISSUE THREAD

**Issue by saruarlive** [fepegar/torchio#573]
Hi, @fepegar ,
Hope you are doing great!
Even though I select num_workers = 4 or 8, all of CPU cores got occupied while using torchio transforms? Could you look into the issue? Another question to ask whether the torchio (latest version) is fully compatible with Pytorch 1.9!

With Thanks
SA

**Comment by fepegar** [comment]
Hi, @saruarlive.

> Even though I select num_workers = 4 or 8, all of CPU cores got occupied while using torchio transforms? Could you look into the issue?

Which transforms are you using?

> whether the torchio (latest version) is fully compatible with Pytorch 1.9!

I haven't tried myself, but everything should work fine, yes.

**Comment by saruarlive** [comment]
> Which transforms are you using?

Used transforms such as: 
```
    tio.ZNormalization(masking_method='brain_mask'), #lambda x: x > 0
    tio.RandomMotion(p=0.2),
    tio.RandomBiasField(p=0.3),
    tio.RandomNoise(p=0.3),
    tio.RandomFlip(axes=[0, 1, 2], flip_probability=0.5),
    tio.OneOf({
        tio.RandomAffine(): 0.6,
        tio.RandomElasticDeformation(): 0.4,
    }),
    tio.RandomGamma(p=0.3),
    tio.RandomBlur(p=0.3),
```

**Comment by fepegar** [comment]
I suspect SimpleITK (which is used within some of those) might be using multiple cores by default. I think you can avoid this by [setting the "global default number of threads" to 1 before calling the transform](https://discourse.itk.org/t/limit-number-of-threads-in-python-simpleitk-programatically/2723):

```python
import SimpleITK as sitk
sitk.ProcessObject.SetGlobalDefaultNumberOfThreads(1)
```

**Comment by fepegar** [comment]
(Or to whatever number of cores you want to use)

**Comment by fepegar** [comment]
Could you solve this issue?

**Comment by saruarlive** [comment]
@fepegar, well, at least all cores didn't get occupied now.  Actually, I used these transforms with monai. When I set 
```sitk.ProcessObject.SetGlobalDefaultNumberOfThreads(1) ``` and ``` num_workers = 4 or 8``` in the monai/pytorch dataloader, still more than 40+ cores got occupied. I am not sure what causes it.

**Comment by fepegar** [comment]
Thanks for the info. Can you please try setting the number of threads with `sitk` and removing all TorchIO transforms? We could also bring someone from the MONAI team into the discussion (I work closely with some of them).

**Comment by saruarlive** [comment]
It is hard to capture the number of cores (of the total 40 cores) it is using as the command _htop_ oscillates.
Having said that, I used monai's CacheNTransDataset as noted below,
```
training_set = monai.data.CacheNTransDataset(data=train_files, transform=training_transform, cache_n_trans = n_train_cache_n_trans, cache_dir = cache_dir)
```
While using just monai transforms, it shows like,
![JustMonai](https://user-images.githubusercontent.com/24542592/124809002-e9a93600-df5f-11eb-8843-d6408a5ca59e.gif)

While using torcio+monai transforms together, it shows like,
![monia+torchIO](https://user-images.githubusercontent.com/24542592/124809041-f29a0780-df5f-11eb-8536-47a5c41d3611.gif)

**Comment by romainVala** [comment]
what the problem for multithreading, ? 
personally I can not use to much worker because of memory issue, so I am happy to have the full cpu usage ... and have the gpu waiting less ...

**Comment by saruarlive** [comment]
@romainVala, Well, If I share resources with others, I don't want to use all resources (cores, rams, gpus, etc), right!

**Comment by fepegar** [comment]
In your GIF, it looks like not all cores are being used when TorchIO is used. Is that correct? In that case, I suppose this issue could be closed.

**Comment by fepegar** [comment]
Closing this for now, feel free to reopen if necessary.
