### ISSUE TITLE
bad image reading when data type is float 64

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#591]
**🐛Bug**

the default sitk reader have problem to properly read a 64 float image

**To reproduce**
```python
import torchio as tio

Im1 = tio.Image('WM.nii.gz',type=tio.INTENSITY)
Im2 = tio.Image('WM.nii.gz',type=tio.INTENSITY, reader=tio.io._read_nibabel)

s1 = tio.Subject({'t1':Im1})
s2 = tio.Subject({'t1':Im2})

s1.plot() # gives blank result
s2.plot() # is ok
```

if I transform to float 32, then I do not have any problem

I know we discuss several time the default choice of nifti reader, this bug is an argument for making nibable the default (unless you find the bug fix)

```python
# Your code here
```

**Expected behavior**

**Actual behavior**

```python-traceback
# Paste the whole error stack trace here
```

**System info**

Output of `python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)`:
Platform: Linux-4.15.0-139-generic-x86_64-with-glibc2.10
TorchIO:  0.18.40
PyTorch:  1.7.1
NumPy:    1.20.2
Python:   3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]

```
# Paste here the output of that command in a terminal
```

**Comment by fepegar** [comment]
Hi, Romain. Can you please share those images?

**Comment by romainVala** [comment]
[WM.nii.gz](https://github.com/fepegar/torchio/files/6746382/WM.nii.gz)

**Comment by romainVala** [comment]
![bug_float](https://user-images.githubusercontent.com/5611962/124086713-9dd32a00-da51-11eb-8fad-7f5334d7679b.png)

**Comment by romainVala** [comment]
may be I am wrong, It seems not related to the datatype
I test other image (also with 64 float) and it is working fine

I do not see what is wrong with my data (which open correctly in mrview, and torchio with nibabel)

**Comment by fepegar** [comment]
I can open it fine with everything (including Slicer, that uses ITK). What version of SimpleITK do you have installed? I'll add that info to the environment script.

**Comment by romainVala** [comment]
2.0.2

**Comment by fepegar** [comment]
Thanks. I'm actually modifying the requirements at the moment to avoid that version anyway, as it's given some trouble with multiprocessing before (https://github.com/SimpleITK/SimpleITK/issues/1239). I'll install that and try to open the image anyway.

**Comment by romainVala** [comment]
arg, I do not understand, If I download the image, then it works for me ... !!!

it is even worth 
```python
Im = tio.Image('/data/romain/HCP/121820/T1w/ROI_PVE_1mm/WM.nii.gz',type=tio.INTENSITY)
s = tio.Subject({'t1':Im})
s.plot()
```
is not working 
but 
```python
Im = tio.Image('/home/romain.valabregue/www/WM.nii.gz',type=tio.INTENSITY)
s = tio.Subject({'t1':Im})
s.plot()
```
is working fine, 
and bot file are identical (I just copy it)
no diff with 
`diff /home/romain.valabregue/www/WM.nii.gz /data/romain/HCP/121820/T1w/ROI_PVE_1mm/WM.nii.gz`

that is weird ... I need a break ...

**Comment by fepegar** [comment]
Hahah that's very weird. I can open it correctly with 2.0.2 as well:

```python
In [1]: import SimpleITK as sitk

In [2]: sitk.__version__
Out[2]: '2.0.2'

In [3]: im = sitk.ReadImage('/tmp/WM.nii.gz')

In [4]: x = sitk.GetArrayViewFromImage(im)

In [5]: x.sum()
Out[5]: 420957.15869685216
```

Is it the plotting only or is the image empty as well? Maybe it's a visualization issue.

**Comment by romainVala** [comment]
no, it seems to be a bad reading, (the figure I upload is the ploting with nibable viewer)
(I do get a different sum) 

...

**Comment by fepegar** [comment]
What sum do you get?

**Comment by romainVala** [comment]
```
In [27]: s.t1.data.sum()
Out[27]: tensor(1336.6758, dtype=torch.float64)

```
but I get the same sum() when I get from the other path

downgrad of scitk, solve the issue too,  but may be I'll take nibabel reader as default for the future

thanks for looking at it, 
but I 'll give up, that is too weird ...

**Comment by fepegar** [comment]
> thanks for looking at it,
but I 'll give up, that is too weird ...

That's a shame, I was curious 🕵️‍♂️😅
