### ISSUE TITLE
accept list to define spacing in torchio.Resample

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#599]
**🚀 Feature**
today only tuple are acceptable
t = torchio.Resample((1,2,3))
but
t = torchio.Resample([1,2,3])
raise an error
**Motivation**

I use a json file to configure my torchio transform, and the tuple does not exist, so I can only specify list

**Pitch**

the change is very easy to do 
I just change 
https://github.com/fepegar/torchio/blob/1384bd3a0a24365edad4913c2355eb99717b1a98/torchio/transforms/preprocessing/spatial/resample.py#L101
by
```python
        if ( isinstance(spacing, tuple) or isinstance(spacing, list) )  and len(spacing) == 3:
```
**Alternatives**

after my json parsing, I could transform list to tuple, but ... I do not see the point to restrict to tuple here ... ?

**Additional context**

**Comment by fepegar** [comment]
Thanks, @romainVala. Fixed in `v0.18.44`.
