### ISSUE TITLE
Improve label sampler efficiency

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#6]

**Comment by romainVala** [comment]
I see the warning from the doc, but did not look at the code yet, 

Actually I was looking for a sampler, that contains the center of the patch within the label. (it is a more conservative alternative to the current setting "at least one non background voxel")

The implementation just need to randomly sample (for the patch center) the coordinate of the label mask ... it should be fast ?

**Comment by fepegar** [comment]
Yes I think that's the way to go. That's how NiftyNet works as well. I'll add a more generic weighted sampler. Then a label map can be used as sampler.

I need to think how to handle sampler images, though. That's why I also added a `torchio.SAMPLER` attribute. I guess the easiest is to treat them as `torchio.LABEL` and apply all spatial transforms using nearest neighbor interpolation. I'll try to work on this after the MICCAI deadline.

**Comment by romainVala** [comment]
ok
it makes sens to indeed treat them as LABEL

**Comment by GFabien** [comment]
Hi @fepegar, we will probably use the `LabelSampler` soon so I was wondering if there were any news regarding this issue.

I thought we could use the same signature with an extra argument that would be a list of probabilities for the different values in the label with default as `[1/n] * n` with `n` the number of different values. Checks would be added to make sure the length of the given list is equal to `n` and that probabilities sum to 1.

For the implementation itself, we could just draw a random number that decide which label value to focus on, then choose randomly a corresponding voxel from the label and return the patch centered on this voxel (with padding if needed).

Would that be enough or am I missing a deeper design choice that would lead to a different solution? In any case I would be happy to provide a PR if needed.

**Comment by fepegar** [comment]
I'll take a look at this next week. Before I forget, this is related to #50.

I think we can follow NiftyNet's approach, i.e. using weighted samplers. Then a label sampler would be a specific case, where the label map can be used as a weight map. They can be tricky, this needs to be done carefully (https://github.com/NifTK/NiftyNet/issues/432).

**Comment by GFabien** [comment]
Hi @fepegar! Any update on this issue?

**Comment by fepegar** [comment]
Sorry, I've been busy. I'll hopefully look into it on Friday.

**Comment by GFabien** [comment]
No problem!

**Comment by fepegar** [comment]
I just spent some hours on this. See #175.

**Comment by fepegar** [comment]
Let me know if that implementation would work for you and I'll merge the changes ASAP.
