### ISSUE TITLE
RuntimeWarning: divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by MichaelMonashev** [fepegar/torchio#620]
**🐛Bug**
/home/xxxx/.local/lib/python3.8/site-packages/torchio/transforms/preprocessing/intensity/histogram_standardization.py:223: RuntimeWarning: divide by zero encountered in true_divide
  slopes = (s2 - s1) / (pc2 - pc1)

**To reproduce**

I use this data https://www.kaggle.com/c/rsna-miccai-brain-tumor-radiogenomic-classification/data
```python
import numpy as np
import os
import pydicom
import cv2
import csv
import torchio

def main():

    max_DD = []
    nii_files = []
    for dir in ['../data/train/', '../data/train/']:
        for f in os.scandir(dir):
            for ff in os.scandir(os.path.join(dir,f.name)):
                nii_file = os.path.join(dir,f.name, ff.name,'0.nii')
                files = os.path.join(dir,f.name, ff.name)
                if os.path.isfile(nii_file):
                    image = torchio.ScalarImage(nii_file)
                else:
                    image = torchio.ScalarImage(files)

                    if image.data.min()==image.data.max():
                        print('empty image', files)

                    image = torchio.ToCanonical()(image)
                    image = torchio.Resample(image_interpolation = 'bspline')(image)
                    image.save(nii_file)

                nii_files.append(nii_file)
                print(nii_file)

                max_d = max(image.data.shape)
                print(max_d)
                max_DD.append(max_d)

    max_DD = np.array(max_DD)
    print('max', max_DD.min(), max_DD.mean(), max_DD.max())

    histogram_landmarks_path = '../data/landmarks.npy'

    landmarks = torchio.HistogramStandardization.train(
        nii_files,
        output_path=histogram_landmarks_path,
    )

if __name__ == '__main__':
    main()
```

**System info**

Output of `python <(curl -s https://raw.githubusercontent.com/fepegar/torchio/master/print_system.py)`:

```
Platform:   Linux-5.4.0-65-generic-x86_64-with-glibc2.29
TorchIO:    0.18.45
PyTorch:    1.9.0+cu111
SimpleITK:  2.1.0 (ITK 5.2)
NumPy:      1.21.1
Python:     3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]

```

**Comment by fepegar** [comment]
Hi, @MichaelMonashev. Thanks for reporting. Can you please share one or two images here, so I can reproduce? Maybe a WeTransfer link?

**Comment by MichaelMonashev** [comment]
https://disk.yandex.ru/d/tk3ffya1kK2lRg

**Comment by fepegar** [comment]
Thanks. It would be great if you could also provide a minimal working example using those files. I think your issue might be an empty image, but it's hard to know without more information.

**Comment by fepegar** [comment]
Thanks for checking. I'm not sure I'd consider this a TorchIO bug. What do you expect from the transform? Would you consider detecting and excluding empty images to compute the histogram landmarks?

**Comment by MichaelMonashev** [comment]
detecting empty images + print warning + excluding empty images is a good idea.

**Comment by fepegar** [comment]
Sounds good. Would you like to contribute with a pull request?

**Comment by MichaelMonashev** [comment]
Sorry.
I am start using torchio 1 day ago and not so familiar with it.

**Comment by fepegar** [comment]
Closing this for now. Happy to reopen is there is more interest.
