### ISSUE TITLE
Error when trying to GET torchio.Subject from torchio.SubjectDataset with multiple images with different spatial size

### ISSUE THREAD

**Issue by cepa995** [fepegar/torchio#647]
I am trying to construct `torchio.SubjectDataset` where each `torchio.Subject` has multiple images (different sequences). Potential problem is, all these images are DIFFERENT spatial sizes.

In order to bring them to same spatial size I've included `CropOrPad `transformation. But, when I try to GET one subject from the dataset, I am getting following error:

```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-79-1b7789238bcb> in <module>
----> 1 subj = dataset.train_set[0]
      2 #help(tio.Subject)
      3 subj.__dict__

/opt/conda/lib/python3.7/site-packages/torchio/data/dataset.py in __getitem__(self, index)
     83         # Apply transform (this is usually the bottleneck)
     84         if self._transform is not None:
---> 85             subject = self._transform(subject)
     86         return subject
     87 

/opt/conda/lib/python3.7/site-packages/torchio/transforms/transform.py in __call__(self, data)
    124             subject = copy.copy(subject)
    125         with np.errstate(all='raise', under='ignore'):
--> 126             transformed = self.apply_transform(subject)
    127         if self.keep is not None:
    128             for name, image in images_to_keep.items():

/opt/conda/lib/python3.7/site-packages/torchio/transforms/augmentation/composition.py in apply_transform(self, subject)
     45     def apply_transform(self, subject: Subject) -> Subject:
     46         for transform in self.transforms:
---> 47             subject = transform(subject)
     48         return subject
     49 

/opt/conda/lib/python3.7/site-packages/torchio/transforms/transform.py in __call__(self, data)
    124             subject = copy.copy(subject)
    125         with np.errstate(all='raise', under='ignore'):
--> 126             transformed = self.apply_transform(subject)
    127         if self.keep is not None:
    128             for name, image in images_to_keep.items():

/opt/conda/lib/python3.7/site-packages/torchio/transforms/augmentation/composition.py in apply_transform(self, subject)
     45     def apply_transform(self, subject: Subject) -> Subject:
     46         for transform in self.transforms:
---> 47             subject = transform(subject)
     48         return subject
     49 

/opt/conda/lib/python3.7/site-packages/torchio/transforms/transform.py in __call__(self, data)
    124             subject = copy.copy(subject)
    125         with np.errstate(all='raise', under='ignore'):
--> 126             transformed = self.apply_transform(subject)
    127         if self.keep is not None:
    128             for name, image in images_to_keep.items():

/opt/conda/lib/python3.7/site-packages/torchio/transforms/preprocessing/spatial/crop_or_pad.py in apply_transform(self, subject)
    238 
    239     def apply_transform(self, subject: Subject) -> Subject:
--> 240         padding_params, cropping_params = self.compute_crop_or_pad(subject)
    241         padding_kwargs = {'padding_mode': self.padding_mode}
    242         if padding_params is not None:

/opt/conda/lib/python3.7/site-packages/torchio/transforms/preprocessing/spatial/crop_or_pad.py in _compute_center_crop_or_pad(self, subject)
    157             subject: Subject,
    158             ) -> Tuple[Optional[TypeSixBounds], Optional[TypeSixBounds]]:
--> 159         source_shape = subject.spatial_shape
    160         # The parent class turns the 3-element shape tuple (w, h, d)
    161         # into a 6-element bounds tuple (w, w, h, h, d, d)

/opt/conda/lib/python3.7/site-packages/torchio/data/subject.py in spatial_shape(self)
    116             (181, 217, 181)
    117         """
--> 118         self.check_consistent_spatial_shape()
    119         return self.get_first_image().spatial_shape
    120 

/opt/conda/lib/python3.7/site-packages/torchio/data/subject.py in check_consistent_spatial_shape(self)
    294 
    295     def check_consistent_spatial_shape(self) -> None:
--> 296         self.check_consistent_attribute('spatial_shape')
    297 
    298     def check_consistent_orientation(self) -> None:

/opt/conda/lib/python3.7/site-packages/torchio/data/subject.py in check_consistent_attribute(self, attribute, relative_tolerance, absolute_tolerance, message)
    282                         }),
    283                     )
--> 284                     raise RuntimeError(message)
    285         except TypeError:
    286             # fallback for non-numeric values

RuntimeError: More than one value for "spatial_shape" found in subject images:
{'T1w': (416, 512, 36), 'T2w': (448, 512, 36)}
```

In summary, when it tries to apply CropOrPad transformation, it fails on following code block:

```python-traceback
/opt/conda/lib/python3.7/site-packages/torchio/data/subject.py in check_consistent_spatial_shape(self)
    294 
    295     def check_consistent_spatial_shape(self) -> None:
--> 296         self.check_consistent_attribute('spatial_shape')
    297 
    298     def check_consistent_orientation(self) -> None:
```

How do I turn off `check_consistent_attribute('spatial_shape')`? Because in the end all subjects WILL BE same size. But this breaks things before `CropOrPad `is applied.

**NOTE**: _Dataset is created SUCCESSFULLY, it is only when I try to GET one of its Subjects, and when transformations are being applied that code fails._

**Comment by fepegar** [comment]
Hi, @cepa995. That check is done for safety reasons. I suspect `Resample` might be more appropriate for your use case. Can you please share one pair of images?

**Comment by cepa995** [comment]
Hi @fepegar! Thanks for fast response!

Images are from Kaggle Competition - https://www.kaggle.com/c/rsna-miccai-brain-tumor-radiogenomic-classification. You can download a pair if you'd like.

Why do you think Resample would be better approach?

**Comment by fepegar** [comment]
> Images are from Kaggle Competition - https://www.kaggle.com/c/rsna-miccai-brain-tumor-radiogenomic-classification. You can download a pair if you'd like.

I'm not familiar with the Kaggle interface. Could you please just share a link to WeTransfer or similar with just a T1 and T2 from the same subject? It will be easier for me to help you.

> Why do you think Resample would be better approach?

I suspect your images are in the same physical space, but different voxel space. The solution for that would be to resample one of them into the voxel space of the other one.

**Comment by cepa995** [comment]
Understood. I will give it a shot.

Here is a link: https://we.tl/t-U7UKEU4CX4. Let me know if you have trouble accessing it.

**Comment by fepegar** [comment]
I opened the images in Slicer and made one green and the other, magenta:

![Screenshot](https://user-images.githubusercontent.com/12688084/132105520-9cc3719a-2ede-4d93-a468-ca8cedf245bb.png)

So they are in the same physical space. I ran these lines in Python:

```python
import torchio as tio
t1 = tio.ScalarImage('T1w')
t2 = tio.ScalarImage('T2w')
subject = tio.Subject(T1w=t1, T2w=t2)
cp = tio.CropOrPad((512, 512, 408))
subject = tio.Subject(T1w=cp(t1), T2w=cp(t2))
subject.plot(reorient=False)
```

![Figure_1](https://user-images.githubusercontent.com/12688084/132105612-494ed57b-0a81-40ec-a907-fcdb257992e7.png)

As you can see, this is not what we would like. This is because images are in different voxel spaces:

```python
In [17]: t1
Out[17]: ScalarImage(shape: (1, 512, 512, 33); spacing: (0.47, 0.47, 5.00); orientation: LPS+; dtype: torch.ShortTensor; memory: 16.5 MiB)

In [18]: t2
Out[18]: ScalarImage(shape: (1, 512, 512, 408); spacing: (0.50, 0.50, 0.50); orientation: PIR+; dtype: torch.ShortTensor; memory: 204.0 MiB)
```

You want to resample them to the same space, using one of them as reference. Also, it's good practice to use a standard orientation for all images, for which we can use `ToCanonical`:

```python
transforms = tio.ToCanonical(), tio.Resample('T2w')
transform = tio.Compose(transforms)
fixed = transform(subject)
subject.plot(reorient=False)
```

![Figure_1](https://user-images.githubusercontent.com/12688084/132105667-2c0d24fb-62eb-44bb-8f48-20960d454a96.png)

That's better!

I recommend preprocessing the images before training, though, as resampling takes time.

**Comment by cepa995** [comment]
Awesome! Thanks @fepegar for the help!

**Comment by fepegar** [comment]
No worries!

**Comment by nengwp** [comment]
I also encountered this problem, and my data has been preprocessed. But for some reasons, there are still some problems.

example:

> RuntimeError: More than one value for "origin" found in subject images:
> {'mask': (-182.7672584785447, -168.4749085656193, 0.9884697081477576),
>   't1': (-182.76725746688743, -168.4749083657494, 0.9884718678333329)}

In fact, my numbers are very close.
Include this function in the source code:

>      def check_consistent_attribute(
>              self,
>              attribute: str,
>              relative_tolerance: float = 1e-6,
>              absolute_tolerance: float = 1e-6,
>              message: Optional[str] = None,
>              ) -> None:

in:
    relative_tolerance: float = 1e-6,
    absolute_tolerance: float = 1e-6,
Can I use the form of passing parameters without modifying the source code to initialize the value to make it receive a greater error?

**If you can, please tell me the plan. If not, do you consider my idea.**

**Comment by fepegar** [comment]
@justusschock do you modify the tolerance or `1e-6` works for you?
Maybe the tolerances can be attributes of the class, instead of kwargs of the method.

**Comment by nengwp** [comment]
Expect it to be a value that can be initialized

**Comment by fepegar** [comment]
> Expect it to be a value that can be initialized

I'm not sure what you mean. Can you elaborate a bit? Maybe with an example?

**Comment by nengwp** [comment]
As you mentioned: Maybe the tolerances can be attributes of the class, instead of kwargs of the method.

This parameter can be used as the initialization parameter of the class, and the default is 1e-6. If necessary, I can initialize to other values.

Am I expressing it clearly?

**Comment by nengwp** [comment]
At present I can only do it by modifying the source code

**Comment by fepegar** [comment]
Thanks, I understand. Let's just see if Justus has any comments, as he worked on this before and might have some good ideas.

**Comment by justusschock** [comment]
I found 1e-6 to be working well for me. To quickly change the values, you could do something like:
```python
class MySubject(Subject):
     def check_consistent_attribute(
         self,
         attribute: str,
         relative_tolerance: float = 1e-5, # note the different defaults here
         absolute_tolerance: float = 1e-5,
         message: Optional[str] = None,
         ) -> None:
         return super().check_consistent_attribute(attribute, relative_tolerance, absolute_tolerance, message)

MySubject(...)
 ```
 
 Adding them as class attributes (or better static attributes to reflect the changes for all instances) would also be possible, but that way you also have to set them explicitly. Passing them as init arguments won't work since then they would be treated as subject members.

**Comment by nengwp** [comment]
This is indeed a good suggestion. But this forces me to understand the source code very well。

**Comment by fepegar** [comment]
> Adding them as class attributes (or better static attributes to reflect the changes for all instances) would also be possible, but that way you also have to set them explicitly. Passing them as init arguments won't work since then they would be treated as subject members.

Thanks for the insight, @justusschock.

> This is indeed a good suggestion. But this forces me to understand the source code very well。

@nengwp, if you follow Justus' suggestion, you should be fine. You would just be creating a class that is similar to `Subject`. You don't really need to understand the source code very well. Here's a reproducible example:

```python
import torch
import numpy as np
import torchio as tio

class MySubject(tio.Subject):
    def check_consistent_attribute(self, *args, **kwargs) -> None:
        kwargs['relative_tolerance'] = 1e-5
        kwargs['absolute_tolerance'] = 1e-5
        return super().check_consistent_attribute(*args, **kwargs)

aff1 = np.eye(4)
aff1[:3, 3] = -182.76725746688743, -168.4749083657494, 0.9884718678333329
aff2 = np.eye(4)
aff2[:3, 3] = -182.7672584785447, -168.4749085656193, 0.9884697081477576

tensor = torch.rand(1, 2, 3, 4)
t1 = tio.ScalarImage(tensor=tensor, affine=aff1)
mask = tio.LabelMap(tensor=tensor, affine=aff2)
subject = MySubject(t1=t1, mask=mask)
transform = tio.CropOrPad(5, copy=False)
transform(subject)
```

Note the `copy=False` in `CropOrPad`. This is necessary due to #694.

**Comment by justusschock** [comment]
@fepegar it might still make sense to add them as static class attributes. That way you could do something like this at the import and everything else would work the same:

```python
import torchio as tio
tio.Subject.relative_attribute_tolerance = 1e-5 # applies to all instances since it is a static attribute
tio.Subject.absolute_attribute_tolerance = 1e-5
```

That way the function could default to None and use the class attributes if no other value was passed. It would also work with every instance, so you could do that once to change it globally.

**Comment by nengwp** [comment]
> @fepegar添加它们作为静态类属性可能仍然有意义。这样，您可以在导入处做类似的事情，其他一切都会同样有效：
> 
> ```python
> import torchio as tio
> tio.Subject.relative_attribute_tolerance = 1e-5 # applies to all instances since it is a static attribute
> tio.Subject.absolute_attribute_tolerance = 1e-5
> ```
> 
> 这样，该函数可以默认为"无"，如果没有其他值通过，则使用类属性。它还会适用于每一个实例，因此您可以一次这样做来在全球更改它。

It does not seem to support such direct changes at this time. Need to add class attributes in the source code.

**Comment by ZDYsszz** [comment]
the results are different,but why?
![image](https://user-images.githubusercontent.com/73088524/145988373-fd1a7a61-5b52-4d88-af1a-7868cb5819c2.png)
![image](https://user-images.githubusercontent.com/73088524/145988405-11db9f56-9969-4ac5-bdf0-75de98fe6fbc.png)

**Comment by ZDYsszz** [comment]
> the results are different,but why? ![image](https://user-images.githubusercontent.com/73088524/145988373-fd1a7a61-5b52-4d88-af1a-7868cb5819c2.png) ![image](https://user-images.githubusercontent.com/73088524/145988405-11db9f56-9969-4ac5-bdf0-75de98fe6fbc.png)

and when i use resample and ToCanonical, it raise an exception,
![image](https://user-images.githubusercontent.com/73088524/145988742-cc3bb0fc-edf2-4d0c-b181-bd19fe37285e.png)
![image](https://user-images.githubusercontent.com/73088524/145988765-638c1d3e-5951-427e-802d-fafe96216ec2.png)
