### ISSUE TITLE
Transform-CropToMask: crops image to the extremes of a bounding box about a given mask

### ISSUE THREAD

**Issue by ashkanpakzad** [fepegar/torchio#675]
**🚀 Feature**

Transform that crops given image to the extremes of a bounding box about a given mask.

**Motivation**

Such a transform is really useful in lung imaging for example, where we cut out the rest of the chest CT (which can include the unwanted abdomen) to crop to a lung segmentation that is fairly easy to acquire.

**Pitch**

A transform ```CropToMask``` that takes ```mask_name``` and a ```padding``` variable and crops an input ScalarImage to the bounding box about  ```mask_name``` with padding to the crop bounding box.

If the padding value exceeds the limits of the ScalarImage then pad the output as provided by ```padding_mode```.

**Alternatives**

As suggested by @fepegar could also make this an implementation of ```CropOrPad``` that takes ```target_shape=None``` and ```mask_name```.

**Additional context**

Currently, I implement this by preprocessing my data separately. Example for lung mask in chest CT.

![Screenshot](https://user-images.githubusercontent.com/20229564/135259661-8a7675bc-3650-4e24-a7d0-b237e585a421.png)
 
![Screenshot_3](https://user-images.githubusercontent.com/20229564/135259681-3d655ecd-64bf-4992-87be-fea97f1b13d1.png)

The CT images provided from QIN LUNG CT (https://wiki.cancerimagingarchive.net/display/Public/QIN+LUNG+CT#b8d88cce4fd14620bef4e5e35ec3d589) under Creative Commons Attribution 3.0 Unported License (https://creativecommons.org/licenses/by/3.0/). The citations are:

* Goldgof, Dmitry, Hall, Lawrence, Hawkins, Samuel, Schabath, Matthew, Stringfield, Olya, Garcia, Alberto, … Gillies, Robert. (2015). Data From QIN_LUNG_CT. The Cancer Imaging Archive. http://doi.org/10.7937/K9/TCIA.2015.NPGZYZBZ
* Jayashree Kalpathy-Cramer, Sandy Napel, Dmitry Goldgof, Binsheng Zhao. QIN multi-site collection of Lung CT data with Nodule Segmentations.  http://dx.doi.org/10.7937/K9/TCIA.2015.1BUVFJR7
* Clark K, Vendt B, Smith K, Freymann J, Kirby J, Koppel P, Moore S, Phillips S, Maffitt D, Pringle M, Tarbox L, Prior F. The Cancer Imaging Archive (TCIA): Maintaining and Operating a Public Information Repository, Journal of Digital Imaging, Volume 26, Number 6, December, 2013, pp 1045-1057. (https://doi.org/10.1007/s10278-013-9622-7)

**Comment by fepegar** [comment]
Thanks, @ashkanpakzad. If different volumes in the dataset end up having different shapes, it won't be possible to use a batch size > 1. Are you planning to train with patches?

**Comment by ashkanpakzad** [comment]
Perhaps I've not thought this through for my current project where I'm using whole 3D images. ```CropOrPad``` should already do the job with```target_shape``` necessary to achieve batch size>1. 

Though in a general preprocessing strategy, it would be useful for patches as you suggest.

**Comment by fepegar** [comment]
> Perhaps I've not thought this through for my current project where I'm using whole 3D images. CropOrPad should already do the job withtarget_shape necessary to achieve batch size>1.

My suspicions are confirmed, then :)

Assuming your spacings are all the same, you could use as `target_shape` the largest size across all masks in your dataset and then use `mask_name` so the FOV is always centered on each mask.

**Comment by ashkanpakzad** [comment]
Yes, very good point, thank you. I'll park it here for the future maybe :)

**Comment by fepegar** [comment]
Thanks anyways, for being happy to contribute!

**Comment by fepegar** [comment]
Reopening after more interest has been shown on #677.
