### ISSUE TITLE
Issues with loading a 4D nifti starting in torchio v0.18.49

### ISSUE THREAD

**Issue by efirdc** [fepegar/torchio#684]
**🐛Bug**
Hi,

I am running into an issue loading a 4D fMRI nifti. Here's a sample file:

https://openneuro.org/crn/datasets/ds001506/snapshots/1.3.1/files/sub-01:ses-perceptionNaturalImageTraining01:func:sub-01_ses-perceptionNaturalImageTraining01_task-perception_run-01_bold.nii.gz

These ones require `channels_last=True`

In torchio 0.18.48 it correctly loads with a shape of (239, 96, 96, 76), but starting in 0.18.49 I get `(1, 96, 96, 76, 239)`

All I am doing is loading the image and checking the shape. Please let me know if there are issues reproducing.

**Comment by fepegar** [comment]
Hi, @efirdc. This happens because SimpleITK gets confused and reads an image with 4 spatial dimensions.

I have removed the `channels_last` kwarg and add code to auto-detect this issue, so images are reformatted at loading time. I'll open a PR soon. Feedback is welcome!
