### ISSUE TITLE
Bug of Transforms in torchio tutorials

### ISSUE THREAD

**Issue by cheonglok** [fepegar/torchio#720]
**🐛Bug**

Wrong url to download the torchio sample data for t1 image

**To reproduce**

```python
https://github.com/fepegar/torchio-data/data/master/data/fernando/t1.nii.gz 
```

**Expected behavior**
Downloading https://github.com/fepegar/torchio-data/data/master/data/fernando/t1.nii.gz to /root/.cache/torchio/fpg/t1.nii.gz

**Actual behavior**

```python-traceback
Downloading https://github.com/fepegar/torchio-data/raw/master/data/fernando/t1.nii.gz to /root/.cache/torchio/fpg/t1.nii.gz
0/? [00:00<?, ?it/s]
Failed download. Trying https -> http instead. Downloading http://github.com/fepegar/torchio-data/raw/master/data/fernando/t1.nii.gz to /root/.cache/torchio/fpg/t1.nii.gz
0/? [00:00<?, ?it/s]
```

**System info**

Output of `/usr/local/lib/python3.7/dist-packages/torchio/download.py in download_url(url, root, filename, md5)`:

```
Downloading https://github.com/fepegar/torchio-data/data/master/data/fernando/t1.nii.gz to /root/.cache/torchio/fpg/t1.nii.gz
```

**Comment by fepegar** [comment]
I'll close this for now. Feel free to reopen is you're still having this issue.
