### ISSUE TITLE
Support bio-data in TorchIO lazy loading

### ISSUE THREAD

**Issue by jxchen01** [fepegar/torchio#738]
**🚀 Feature**

Currently torchio.Image (https://torchio.readthedocs.io/data/image.html#torchio.Image) can be created with paths to files that can be read by SimpleITK or nibabel, or to a directory containing DICOM files. For bio-data, different readers are needed. We could use `aicsimageio` (https://github.com/AllenCellModeling/aicsimageio).

**Motivation**

It would be great to support bio-data in TorchIO so that the large bio-image community can be engaged. 

**Pitch**

`torchio.Image` can be created with paths to files that can be read by SimpleITK or nibabel, or to a directory containing DICOM files, or any file format supported by bioformats in `aicsimageio`.

**Comment by fepegar** [comment]
Hi, @jxchen01. You can just pass a callable object to the image. For example,

```python
import numpy as np
import torchio as tio
import biolib  # hypothetical library

def read_bio(path):
    data_4d = biolib.read(path)
    affine = np.eye(4)
    return data_4d, affine

image = tio.ScalarImage(path, reader=read_bio)
```

or 

```python
class BioImage(tio.ScalarImage):
    def __init__(self, *args, **kwargs):
        kwargs['reader'] = read_bio
        super().__init__(*ars, **kwargs)

image = BioImage(path)
```

Would this work for you?
I think it makes more sense than adding more and more dependencies to TorchIO.

**Comment by jxchen01** [comment]
Thanks for the suggestion. I will give a try and update here if it works out well

**Comment by fepegar** [comment]
I will close this and the corresponding PR (#741) for now, as a custom reader should suffice. Feel free to reopen them if necessary.
