### ISSUE TITLE
Colab notebook contains incorrect link to data

### ISSUE THREAD

**Issue by vasl12** [fepegar/torchio#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

In notebook [Data preprocessing and augmentation using TorchIO - a tutorial.ipynb](https://colab.research.google.com/github/fepegar/torchio-notebooks/blob/main/notebooks/Data_preprocessing_and_augmentation_using_TorchIO_a_tutorial.ipynb) the link to download the fpg data is not specified correctly. It is ([https://github.com/fepegar/torchio-data/raw/master/data/fernando/t1.nii.gz](https://github.com/fepegar/torchio-data/raw/master/data/fernando/t1.nii.gz)) when it should be [https://github.com/TorchIO-project/torchio-data/tree/main/data/fernando/t1.nii.gz](https://github.com/TorchIO-project/torchio-data/tree/main/data/fernando/t1.nii.gz).

Thank you very much for the nice work!

### Code for reproduction

```python
None
```

### Actual outcome

404 not found

### Expected outcome

download successful

**Comment by fepegar** [comment]
Hi, @vasl12. Thanks for reporting and for your kind words. I haven't been able to find that link in the [notebook source](https://raw.githubusercontent.com/fepegar/torchio-notebooks/main/notebooks/Data_preprocessing_and_augmentation_using_TorchIO_a_tutorial.ipynb) (I searched for `fepegar/torchio-data`). Which section are you referring to?

**Comment by vasl12** [comment]
Hi @fepegar. Well, the tutorial I am referring to is the _Transforms_ tutorial. You can find it in README.md in this link [https://github.com/fepegar/torchio/tree/main/tutorials](https://github.com/fepegar/torchio/tree/main/tutorials).

**Comment by fepegar** [comment]
I have updated the TorchIO version in the tutorial. That seems to have solved the issue. Thanks for reporting!

@all-contributors please add @vasl12 for bug
