### ISSUE TITLE
Queue is unable to create mixed batches from subject with different shape that are fetched from disk

### ISSUE THREAD

**Issue by snipdome** [fepegar/torchio#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

When populating a SubjectsDataset with subjects that have a different dimensional shape and when sampling fixed-shape patches from them, the Queue class is unable to give batches of sampled patches
[More in 'Actual outcome' section]

### Code for reproduction

```python
""
```

### Actual outcome

It happens only when it also happens that:

- one batch have patches sampled from different subjects (e.g. when shuffling is activated or when a batch contains the last samples of one subject and the initial samples of the following subject)
- subjects are fetched from directly disk

What is creating troubles is the checking system, which compares each field of the subjects that are going to populate a batch and fails when checking fields that are related to the paths information

### Expected outcome

When populating a SubjectsDataset with subjects that have a different dimensional shape and when sampling fixed-shape patches from them, the Queue class should be able to give batches  with mixed patches sampled from several subjects.

**Comment by fepegar** [comment]
Hi, @snipdome. Could you please share a minimal working example to reproduce this?
