### ISSUE TITLE
Classification with torchio SubjectsDataset

### ISSUE THREAD

**Issue by gkrisp98** [fepegar/torchio#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

Hi, I am working on a project where I have to classify Knee MRIs to 5 grades. I converted the DICOM files to nifti and tried to create a subject dataset function to use it for classification. 
I am not quite sure how to "insert" the label in the subject object as all the tutorials deal with segmentation labels. Is there a way to create this dataset and train my model ?

### Code for reproduction

```python
def load_mri(mri_path):
  full_path = glob.glob(f"/content/drive/MyDrive/images-nifti/{mri_path}")
  subject = tio.Subject(t1 = tio.ScalarImage(full_path))
  return subject

def makeSubjectsPlease(root_dir = "/content/drive/MyDrive/images_nifti"):
  dataframe = pd.read_csv("/content/drive/MyDrive/nifti-grades.csv", sep = ';')
  labels = {}
  id = list(dataframe["id"])
  grades = list(dataframe["grade"])
  for i,g in zip(id, grades):
    labels[str(i).zfill(5)] = g
  ids = [a.split("/")[-1] for a in sorted(glob.glob(f"/content/drive/MyDrive/images_nifti/" + "/*"))]

  subjects_list = []

  for i, idx in enumerate(ids):
    sub = tio.Subject(
        load_mri(ids[i]),
        #label = tio.LabelMap(labels[ids[i]])
        label = labels[ids[i]],
    )
    subjects_list.append(sub)

  return subjects_list
```

### Actual outcome

I get the Dataset but when I try to access an instance of it I get an error. For example when I run: 

> subjects_dataset[1]

 I get the error:list index out of range

### Error messages

```python-traceback
IndexError                                Traceback (most recent call last)
<ipython-input-196-026e8ddbe5a0> in <module>()
----> 1 subjects_dataset[10]

2 frames
/usr/local/lib/python3.7/dist-packages/torchio/data/dataset.py in __getitem__(self, index)
     79         subject = copy.deepcopy(subject)  # cheap since images not loaded yet
     80         if self.load_getitem:
---> 81             subject.load()
     82 
     83         # Apply transform (this is usually the bottleneck)

/usr/local/lib/python3.7/dist-packages/torchio/data/subject.py in load(self)
    355         """Load images in subject on RAM."""
    356         for image in self.get_images(intensity_only=False):
--> 357             image.load()
    358 
    359     def update_attributes(self) -> None:

/usr/local/lib/python3.7/dist-packages/torchio/data/image.py in load(self)
    448             return
    449         paths = self.path if isinstance(self.path, list) else [self.path]
--> 450         tensor, affine = self.read_and_check(paths[0])
    451         tensors = [tensor]
    452         for path in paths[1:]:

IndexError: list index out of range
```

### Expected outcome

I want to get the dataset instance with its label.

**Comment by Sejal-Ghate** [comment]
Hi, Were you able to identify the solution to this problem? I've had a similar kind of issue where im trying to use torchio for a classification problem but get stuck on assigning the labels.

Thank you for your help on this!

**Comment by gkrisp98** [comment]
> Hi, Were you able to identify the solution to this problem? I've had a similar kind of issue where im trying to use torchio for a classification problem but get stuck on assigning the labels.
> 
> 
> 
> Thank you for your help on this!

Hi, yes I was able to work it out. I am not quite sure what I did wrong in the code of the post. I guess it was something with the load_mri(). Here is the code that works: 

```

def load_mri(mri_path):
  root = "/content/drive/MyDrive/images_nifti"
  full_path = os.path.join(root, mri_path)
  subject = tio.Subject(t1 = tio.ScalarImage(full_path))
  return subject

def makeSubjectsPlease():
  dataframe = pd.read_csv("/content/drive/MyDrive/nifti-grades.csv", sep = ';')
  labels = {}
  id = list(dataframe["id"])
  grades = list(dataframe["grade"])
  for i,g in zip(id, grades):
    labels[str(i).zfill(5)] = g

  ids = [a.split("/")[-1] for a in sorted(glob.glob(f"/content/drive/MyDrive/images_nifti/" + "/*"))]
  subjects_list = []

  for i, idx in enumerate(ids):
    sub = tio.Subject(
        load_mri(ids[i]),
        label = labels[ids[i]],
    )
    subjects_list.append(sub)
  return subjects_list

```

Generally, you define a too.Subject with the nifti (or with dicom file) and the label as a simple variable.
I hope it helps!

**Comment by fepegar** [comment]
I think the code in https://github.com/fepegar/torchio/issues/799#issuecomment-1038753241 is not correct, as it passes an instance of `Subject` (`load_mri(ids[i])`) to a new `Subject` (`sub`). This is what I mean in https://github.com/fepegar/torchio/discussions/819#discussioncomment-2175823.

**Comment by gkrisp98** [comment]
Code without passing a Subject instance: 
```

def makeSubjects():
  dataframe = pd.read_csv("/content/drive/MyDrive/nifti-grades.csv", sep = ';')
  labels = {}
  id = list(dataframe["id"])
  grades = list(dataframe["grade"])
  for i,g in zip(id, grades):
    labels[str(i).zfill(5)] = g

  ids = [a.split("/")[-1] for a in sorted(glob.glob(f"/content/drive/MyDrive/images_nifti/" + "/*"))]
  root = "/content/drive/MyDrive/images_nifti"
  subjects_list = []

  for i, idx in enumerate(ids):
    sub = tio.Subject(
        t1 = tio.ScalarImage(os.path.join(root, ids[i])),
        label = labels[ids[i]],
    )
    subjects_list.append(sub)
  return subjects_list

```

**Comment by Sejal-Ghate** [comment]
Hi @gkrisp98 ,

Thank you for sharing your code. I did something similar with the labels where I referenced it to the list of the different classes I had (10-class classification).
