### ISSUE TITLE
Generalize io module

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#82]
Code to write NRRD files is missing:
https://github.com/fepegar/torchio/blob/128895a88cdb1165f8b8533e11835a6b1db12b8c/torchio/data/io.py#L83-L88

**Comment by bcdarwin** [comment]
Wouldn't it be easier to use Nibabel (and/or SITK) to do file writes and avoid writing Nifti-specific header information, which would also give support for DICOM, MINC, etc.?  Any conversion issues could be pushed upstream to Nibabel.

**Comment by bcdarwin** [comment]
(To answer my own question: [Nibabel doesn't yet support NRRD](https://github.com/nipy/nibabel/issues/356))

**Comment by fepegar** [comment]
NiBabel doesn't support NRRD. But you're right, It would be simpler to use SITK in general.

**Comment by bcdarwin** [comment]
At least, `write_nifti` could be generalized to `write_nibabel`.

**Comment by fepegar** [comment]
Exactly. DICOM support will be trickier, especially for writing. But maybe SITK can try to handle it.

**Comment by fepegar** [comment]
We're crossing messages, sorry. Maybe a good approach is trying to write the image with nibabel and falling back to SITK if it fails.

**Comment by bcdarwin** [comment]
Sounds reasonable, especially with an option to override.

**Comment by fepegar** [comment]
> an option to override.

I'm not sure what you mean with this.

**Comment by bcdarwin** [comment]
> > an option to override.
> 
> I'm not sure what you mean with this.

You might prefer SITK even if Nibabel can technically read your file, e.g. due to some bug/edge case in format support, or you might care about IO performance and find SITK is faster, etc.

**Comment by fepegar** [comment]
@bcdarwin, can you take a look at #92 and let me know what you think?

**Comment by bcdarwin** [comment]
Sure, I'll look into this in a bit.
