### ISSUE TITLE
Incompatibility with Image and ImageDraw from PIL

### ISSUE THREAD

**Issue by csudre** [fepegar/torchio#84]
**Describe the bug**
As Image is a module of PIL, loading Image from PIL leads to unexpected behaviours when defining objects of class Image (as defined in torchio)

**Expected behavior**
Modify the name of the class and or write a warning relative to the simultaneous use of PIL

**Comment by fepegar** [comment]
In that case, I suggest using `import torchio` and `torchio.Image` instead of `from torchio import Image`.

**Comment by fepegar** [comment]
Another option is to import the PIL Image as `import PIL.Image`, as DeepMind folks do [here](https://github.com/deepmind/multidim-image-augmentation/blob/master/doc/elastic_deformation_colab.md#imports).
