### ISSUE TITLE
Converting RDS to LDS?

### ISSUE THREAD

**Issue by Jeffotter** [fepegar/torchio#860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

I am attempting to follow the workflow you used for https://github.com/fepegar/torchio/issues/647 , but I am still getting issues. I am loading from two different data sources for semantic segmentation one .nii and one .npy. When I run it through the transformation below and call the first time of the training set I get an error. Thank you in advance.

### Code for reproduction

```python
def numpy_reader(path):
    return np.load(path), np.eye(4)

subjects=[]
for subject_path in merged_list:
    subject = tio.Subject({"MRI":tio.ScalarImage(subject_path[0]), "Label":tio.LabelMap(subject_path[1],reader=numpy_reader)})
    subjects.append(subject)

process = tio.Compose([
            tio.ToCanonical(),
            tio.CropOrPad((192, 192, 192)), #This crops it to the desired metirc
            tio.RescaleIntensity((-1, 1)) # This normalizes the data
            ])
augmentation = tio.RandomAffine(scales=(0.9, 1.1), degrees=(-10, 10))
val_transform = process
train_transform = tio.Compose([process, augmentation])

train_dataset = tio.SubjectsDataset(subjects, transform=train_transform)
val_dataset = tio.SubjectsDataset(subjects, transform=val_transform)

train_dataset[0] #error
```

### Actual outcome

I get an error that says my two images are in different space which is true from my run-through.
<img width="894" alt="image" src="https://user-images.githubusercontent.com/60712345/163893875-a4ca8084-cfed-4dfc-93ee-2072d02df377.png">

When I check to see how different they look very similar
![image](https://user-images.githubusercontent.com/60712345/163893953-65304fed-8135-46ae-b294-6c8dda2e8025.png)

### Error messages

```python-traceback
RuntimeError: More than one value for "direction" found in subject images:
{'Label': (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0),
 'MRI': (-1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)}
....
RuntimeError: As described above, some images in the subject are not in the same space. You probably can use the transforms ToCanonical and Resample to fix this, as explained at https://github.com/fepegar/torchio/issues/647#issuecomment-913025695
```

### Expected outcome

Subject(Keys: ('MRI', 'Label'); images: 2)

### System info

```shell
# flake8: noqa

import re
import sys
import platform
import torchio
import torch
import numpy
import SimpleITK as sitk


sitk_version = re.findall('SimpleITK Version: (.*?)\n', str(sitk.Version()))[0]

print('Platform:  ', platform.platform())
print('TorchIO:   ', torchio.__version__)
print('PyTorch:   ', torch.__version__)
print('SimpleITK: ', sitk_version)
print('NumPy:     ', numpy.__version__)
print('Python:    ', sys.version)
```

**Comment by fepegar** [comment]
Hi, @Jeffotter. Can you please share some data for reproduction?

**Comment by Jeffotter** [comment]
absolutely! Thank you!
The nifiti files are the 'MRI' in the section and the npy files are Label. Let me know if you need more data or in a different format. 
[Data.zip](https://github.com/fepegar/torchio/files/8508966/Data.zip)

**Comment by fepegar** [comment]
I forgot to ask: can you please share the full error traceback, not only the last lines?

**Comment by Jeffotter** [comment]
RuntimeError                              Traceback (most recent call last)
~/anaconda3/lib/python3.9/site-packages/torchio/data/subject.py in check_consistent_space(self)
    307             self.check_consistent_attribute('direction')
--> 308             self.check_consistent_attribute('origin')
    309             self.check_consistent_spatial_shape()

~/anaconda3/lib/python3.9/site-packages/torchio/data/subject.py in check_consistent_attribute(self, attribute, relative_tolerance, absolute_tolerance, message)
    283                     )
--> 284                     raise RuntimeError(message)
    285         except TypeError:

RuntimeError: More than one value for "origin" found in subject images:
{'Label': (0.0, 0.0, 0.0), 'MRI': (-91.0, -126.0, -72.0)}

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_2162828/2217239065.py in <module>
----> 1 train_dataset[0]['MRI']

~/anaconda3/lib/python3.9/site-packages/torchio/data/dataset.py in __getitem__(self, index)
     91         # Apply transform (this is usually the bottleneck)
     92         if self._transform is not None:
---> 93             subject = self._transform(subject)
     94         return subject
     95 

~/anaconda3/lib/python3.9/site-packages/torchio/transforms/transform.py in __call__(self, data)
    138             subject = copy.copy(subject)
    139         with np.errstate(all='raise', under='ignore'):
--> 140             transformed = self.apply_transform(subject)
    141         if self.keep is not None:
    142             for name, image in images_to_keep.items():

~/anaconda3/lib/python3.9/site-packages/torchio/transforms/augmentation/composition.py in apply_transform(self, subject)
     45     def apply_transform(self, subject: Subject) -> Subject:
     46         for transform in self.transforms:
---> 47             subject = transform(subject)
     48         return subject
     49 

~/anaconda3/lib/python3.9/site-packages/torchio/transforms/transform.py in __call__(self, data)
    138             subject = copy.copy(subject)
    139         with np.errstate(all='raise', under='ignore'):
--> 140             transformed = self.apply_transform(subject)
    141         if self.keep is not None:
    142             for name, image in images_to_keep.items():

~/anaconda3/lib/python3.9/site-packages/torchio/transforms/augmentation/composition.py in apply_transform(self, subject)
     45     def apply_transform(self, subject: Subject) -> Subject:
     46         for transform in self.transforms:
---> 47             subject = transform(subject)
     48         return subject
     49 

~/anaconda3/lib/python3.9/site-packages/torchio/transforms/transform.py in __call__(self, data)
    138             subject = copy.copy(subject)
    139         with np.errstate(all='raise', under='ignore'):
--> 140             transformed = self.apply_transform(subject)
    141         if self.keep is not None:
    142             for name, image in images_to_keep.items():

~/anaconda3/lib/python3.9/site-packages/torchio/transforms/preprocessing/spatial/crop_or_pad.py in apply_transform(self, subject)
    265 
    266     def apply_transform(self, subject: Subject) -> Subject:
--> 267         subject.check_consistent_space()
    268         padding_params, cropping_params = self.compute_crop_or_pad(subject)
    269         padding_kwargs = {'padding_mode': self.padding_mode}

~/anaconda3/lib/python3.9/site-packages/torchio/data/subject.py in check_consistent_space(self)
    315                 ' https://github.com/fepegar/torchio/issues/647#issuecomment-913025695'  # noqa: E501
    316             )
--> 317             raise RuntimeError(message) from e
    318 
    319     def get_images_names(self) -> List[str]:

RuntimeError: As described above, some images in the subject are not in the same space. You probably can use the transforms ToCanonical and Resample to fix this, as explained at https://github.com/fepegar/torchio/issues/647#issuecomment-913025695

**Comment by Jeffotter** [comment]
I believe my error may have shifted to something I believe I can fix, It seems when I converted my .nii files to .npy files I erased the metadata (lesson learned) and changed my coordinate origins, but if you are aware of a way I can easily align them in Torchio I would take that advice, but I am also happy to close the issue

**Comment by fepegar** [comment]
Thanks for the info. In that case, that's definitely the issue. I would stick to a format more suitable for medical images such as NIfTI or NRRD.
