### ISSUE TITLE
add 'return fig' to plot functions

### ISSUE THREAD

**Issue by guigautier** [fepegar/torchio#865]
**🚀 Feature**
In visualization.py plot_subject and plot_volume is it possible de return the matplotlib fig ? 

```
    'if output_path is not None:
        fig.savefig(output_path)
    if show:
        plt.show()
    return fig
```

**Motivation**
To send the figure to an experiment tracker. 

thank you

**Comment by dmus** [comment]
I also use something like this in my code to send images to an experiment tracker (ClearML for example)

**Comment by dmus** [comment]
I opened a pull request: https://github.com/fepegar/torchio/pull/872
