### ISSUE TITLE
torchio.Affine not working while model training 

### ISSUE THREAD

**Issue by jeremysong1106** [fepegar/torchio#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

Hi ,I occur a problem of torchio.Affine while training my model.

I try to apply the affine transformation to the 3d image as output, and calculate the similarity between the input and output 3d image(**which mean gradient are required here**).

But it seems like the **torch.Affine not supporting** when the situation that the degrees and translation have gradient ?

### Code for reproduction

```python
translation, rotation = parameters
        rotation = rotation * 180 / pi
        batch_img_new = torch.zeros_like(moving_image)
        for i, img in enumerate(moving_image):

            transform = tio.Affine(
                scales=(1, 1, 1),
                degrees=rotation[i],
                translation=translation[i],

            )
            transformed = transform(img)
            batch_img_new[i] = transformed
```

### Actual outcome

  
  File ".local/lib/python3.8/site-packages/torchio/transforms/augmentation/spatial/random_affine.py", line 300, in get_affine_transform
    rotation = np.asarray(self.degrees).copy()
  File "local/lib/python3.8/site-packages/torch/_tensor.py", line 643, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### Expected outcome

the function torchio.Affine can support the cuda environment while training

**Comment by fepegar** [comment]
Hi, @jeremysong1106. The transform is applied using SimpleITK, which does not support GPU operations yet, so this error is expected.
