### ISSUE TITLE
Cannot install newest version of torchio in conda venv 

### ISSUE THREAD

**Issue by poulinn** [fepegar/torchio#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

I am working in a conda venv and need to install a specific version of torchio. Using "conda install -c conda-forge torchio=0.18.76" results in: PackagesNotFoundError: The following packages are not available from current channels: python=3.1" My Python version is 3.10.4. The same thing happens if install 0.18.77. If I use the same command but do not specify a version of torchio, then an earlier torchio release installs (0.18.30). I then cannot import the "Mask" function in my python script and get  "AttributeError: module 'torchio' has no attribute 'Mask'" 
![image](https://user-images.githubusercontent.com/106405566/170777952-78eef3ee-b4f3-4b33-9310-9655ea004fa0.png)
I would appreciate some guidance on this issue! Thanks. 

### Code for reproduction

```python
conda install -c conda-forge torchio=0.18.76
```

### Actual outcome

Package does not install. 

### Error messages

```python-traceback
PackagesNotFoundError: The following packages are not available from current channels: python=3.1
```

### Expected outcome

It should just install and I should be able to run my python script and import all of the torchio functionality. 

### System info

```shell
Platform:   Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.17
TorchIO:    0.18.30
PyTorch:    1.10.2
SimpleITK:  2.0.2 (ITK 5.1)
NumPy:      1.22.3
Python:     3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
```

**Comment by fepegar** [comment]
Thanks for reporting, @poulinn. [This might be a bug in Conda](https://stackoverflow.com/a/70239240/3956024). Which version are you using?

```console
$ conda --version
```

**Comment by fepegar** [comment]
Pinging @sarthakpati.

**Comment by fepegar** [comment]
It looks like this is out of our hands, so I'm closing the issue. @poulinn, feel free to reopen if upgrading `conda` didn't help.

**Comment by poulinn** [comment]
@fepegar My conda version is 4.5.4. conda update conda or conda update anaconda do not work for me. I get "PackageNotInstalledError: Package is not installed in prefix." But if I do conda update --name base conda, then it starts thinking and installs the newer version packages, but then I get :
"Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::conda-4.5.4-py36_0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Permission denied') "

**Comment by poulinn** [comment]
@sarthakpati I just conda installed python= 3.9.12, and then ran conda update --name base conda, but got the same errors above.

**Comment by poulinn** [comment]
@sarthakpati Wait why did it install the older version -0.18.30 and not the newer version = 0.18.77?

**Comment by fepegar** [comment]
Thanks, @sarthakpati!

I just tried a fresh install with the Python version above and things seem to work, so I'm going to close this for now.

```console
$ conda create -n ct python=3.9.12 -y && conda activate ct && conda install -c conda-forge torchio -y
[...]
$ python -c "import torchio; print(torchio.__version__)"
0.18.77
```
