### ISSUE TITLE
add RandomSpike

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#89]
Hi there

I saw you recently add RandomGhosting
An other artefact (although less frequent) is RandomSpike, which should be easy to implement (it is just random additive signal in a few points of the kspace)

Many thanks for this good work: !

**Comment by fepegar** [comment]
Thanks, Roman. How would you implement this? I.e. how do you need to modify e.g. a 2D spectrum of complex values `spectrum`? How do you choose the points and what should you add to them?

**Comment by fepegar** [comment]
Would it be enough to choose a random point in the spectrum and set it to `spectrum.max()`?

**Comment by romainVala** [comment]
yes I think we can start with that,
a parameter number of point  (to be choosen randomly in the kspace) 
and an amplitude, which is express as a pourcentage of the max (10 % of the max is begining to be very hard)

Ideally this is a gaussian around the chosen points

I would go with a 3D fft

**Comment by fepegar** [comment]
I see. I'll think about how to implement that. For now, trying the approach I just proposed, I got images like this:
![Screenshot](https://user-images.githubusercontent.com/12688084/75154724-478c0380-5706-11ea-8596-ae536e5ba8c7.png)

**Comment by fepegar** [comment]
That's the previous approach with `0.1 * spectrum.max()`. I'm a bit confused about the Gaussian method. I generated the smoothed spikes, but I'm not sure about how to add them to the (complex) spectrum. Maybe adding them to the magnitude and leave the phase as it was?

![Screenshot_0 1](https://user-images.githubusercontent.com/12688084/75155553-3d6b0480-5708-11ea-83ea-3837699aeefc.png)

**Comment by fepegar** [comment]
For now, I'll just implement it the simple way. It can always be modified later on.

**Comment by romainVala** [comment]
cool, sounds good

I would say just add some real number to the complex spectrum (do not bother with the phase)

**Comment by romainVala** [comment]
So quick !

felicitation
