### ISSUE TITLE
Window functions for patch aggregation

### ISSUE THREAD

**Issue by LucaLumetti** [fepegar/torchio#894]
**🚀 Feature**

Add the support to window functions as overlap_mode when aggregating patches with GridAggregator

**Motivation**

Windows functions, widely used in audio encoding, are good at reducing edge effects when aggregating a batch of overlapping patches. A the moment GridAggregator only support 'crop' and 'average' as overlap mode.

**Pitch**
Have the possibility to choose as an overlapping mode a window function. I expect to write something like: `tio.GridAggregator(sampler, overlap_mode='hann')`
Different types of window function can be implemented:
- Hann window
- Triangular window
- Pyramidal window
- Kaiser-Bessel window

**Additional context**
Different window functions have been proven to be more effective than other modes to overlap patches: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0229839

**Comment by fepegar** [comment]
Hi, @LucaLumetti. Cool idea. I've never seen these windows in >1D. Would you be interested in implementing any of this?

**Comment by fepegar** [comment]
Awesome! Looking forward. Feel free to open a draft pull request.

**Comment by fepegar** [comment]
Apologies, I'll review tomorrow!
