### ISSUE TITLE
The fourier_transform is not shifted when torch.fft is available

### ISSUE THREAD

**Issue by iimog** [fepegar/torchio#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

The behavior of `torchio` when applying a spike artifact in specific `spikes_positions` depends on whether `torch.fft` is available.  This is done extensively in [misas](https://chfc-cmi.github.io/misas/mr_artifacts.html#get_spike_series). 

This issue was introduced in https://github.com/fepegar/torchio/pull/389.
The reason is that, in when `torch.fft` is available, `fftshift` is not applied (compared to the case when numpy was/is used).
https://github.com/fepegar/torchio/blob/624ed396a6da85f50b8b67cbb5582c4eccc74bb9/src/torchio/transforms/fourier.py#L8-L16  Results are still consistent as in that case in the inverse transformation `ifftshift` is also not applied https://github.com/fepegar/torchio/blob/624ed396a6da85f50b8b67cbb5582c4eccc74bb9/src/torchio/transforms/fourier.py#L19-L27

I realize, that the functionality of `RandomSpike` is not affected by this difference. I still think it is a bug, as the result of `Spike` now depends on the `torch` version.

### Code for reproduction

```python
from torchio.transforms import Spike
from PIL import Image
import numpy as np
import torch

# download image from https://github.com/chfc-cmi/misas/raw/master/example/kaggle/images/1-frame014-slice005.png
image = Image.open("1-frame014-slice005.png").convert("I")

def spikeTransform(image, intensityFactor=1, spikePosition=[.1,.1]):
    image = np.expand_dims(np.array(image), 0)
    image = image/255
    image = torch.Tensor(image)
    spikePosition = [[.0] + spikePosition]
    spike = Spike(spikePosition, intensityFactor)
    image = spike.add_artifact(image, spikePosition, intensityFactor)[0]
    image = np.array((torch.clamp(image,0,1)))
    image = image*255
    image = image.astype(np.uint8)
    image = np.moveaxis(image, 0, 1)
    image = Image.fromarray(image)
    return image

spikeTransform(image)
```

### Actual outcome

The code above (executed in a jupyter notebook) produces this image:
![actual](https://user-images.githubusercontent.com/7403236/175547382-c85045ee-637d-4430-8d79-c9698632ce81.png)

### Expected outcome

Previously, or when `torch.fft` is not available, the code above produces this image:
![expected](https://user-images.githubusercontent.com/7403236/175547597-eae06ee7-0116-40e3-ad6f-ac509c8cd333.png)

### System info

```shell
Platform:   Linux-5.15.0-39-generic-x86_64-with-glibc2.35
TorchIO:    0.18.79
PyTorch:    1.11.0+cu102
SimpleITK:  2.1.1.2 (ITK 5.2)
NumPy:      1.23.0
Python:     3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0]
```

**Comment by fepegar** [comment]
Awesome catch. Thanks a lot, @iimog. I should've added a regression test before making the change in #389!

**Comment by fepegar** [comment]
Also, thanks a lot for the very clear bug report!

**Comment by iimog** [comment]
My pleasure. Thanks for merging this so quickly. Also, thanks for creating such a nice and welcoming environment for contributors.
