### ISSUE TITLE
When I tried to use 'torch.nn.MaxUnpool3d', the following error occurred

### ISSUE THREAD

**Issue by cheyennee** [fepegar/torchio#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

The bug occurred when using the API 'torch.nn.MaxUnpool3d' which caused the program to no longer respond.

### Code for reproduction

```python
import torch
arg_1 = 49
arg_2 = 2
arg_class = torch.nn.MaxUnpool3d(arg_1,stride=arg_2,)
arg_3_0_tensor = torch.rand([20, 16, 25, 16, 7], dtype=torch.float32)
arg_3_0 = arg_3_0_tensor.clone()
arg_3_1_tensor = torch.randint(-16384,16,[20, 16, 25, 16, 7], dtype=torch.int64)
arg_3_1 = arg_3_1_tensor.clone()
arg_3 = [arg_3_0,arg_3_1,]
res = arg_class(*arg_3)
```

### Actual outcome

Actually there is no any error messages, the program is not responding. I have to forcibly close this program.

### Expected outcome

The result should be a pytorch tensor.

### System info

```shell
python version: 3.8.3
torch version: 1.8.1
```

**Comment by fepegar** [comment]
Hi, @cheyennee. I think you meant to post this in https://github.com/pytorch/pytorch/issues.

**Comment by cheyennee** [comment]
> Hi, @cheyennee. I think you meant to post this in https://github.com/pytorch/pytorch/issues.

Oh, my fault😫Thank you for reminding me😂
