### ISSUE TITLE
Allow `masking_method` to accept a key of an input `Dict`

### ISSUE THREAD

**Issue by YerePhy** [fepegar/torchio#928]
Allow `masking_method` to accept a string that is a key of an input `Dict`, not a key of `torchio.Subject` which value must be a `tochio.LabelMap`. It's very helpful for MONAI compatibility.

**Comment by YerePhy** [comment]
It works with: 

<pre>
include: [IMAGE, MASK]
label_keys: MASK
masking_method: MASK
</pre>

**Comment by fepegar** [comment]
Thanks for sharing your solution, @YerePhy!
