### ISSUE TITLE
Repr should not load the image

### ISSUE THREAD

**Issue by justusschock** [fepegar/torchio#930]
**🚀 Feature**

Changing the way `__repr__` gives an representation of the image.

**Motivation**

Debuggers call `__repr__` to  give a preview of the python object.

**Pitch**
When having torchio Images that have not been loaded and the debugger calls `__repr__` to give a preview of the python object, due to the attributes embedded in the returned string, `__repr__` will always load the image.

That can, however, alter the program flow in ways that make it difficult to debug as the usual python program would not load the image at that point and it wouldn't be necessary to do so, if it weren't for the debugger.

The proposed change therefore is to have a `__repr__` like this:

```python

def __repr__(self) -> str:
    if self._loaded:
        ... # current repr logic since we can safely access all attributes of the image if it was loaded.
    else:
        return f"{self.__class__.__name__}(path: {self.path})"
```

I think in such cases it is better to have the image path instead of just loading the image just for this preview

**Alternatives**
We could keep it as is and just state this somewhere in the docs. I am afraid, however, that this won't be helpful for most people since it's quite involved with debugger internals (I had to dig a bit through debugger sources on my own).

**Additional context**

cc @fepegar

**Comment by fepegar** [comment]
Hi, @justusschock. I'm not sure what you mean. Calling `repr` shouldn't load the image data.

```python
In [1]: import torchio as tio

In [2]: image = tio.datasets.Colin27().t1

In [3]: image  # __repr__ is called internally here
Out[3]: ScalarImage(shape: (1, 181, 217, 181); spacing: (1.00, 1.00, 1.00); orientation: RAS+; path: "/Users/fernando/.cache/torchio/mni_colin27_1998_nifti/colin27_t1_tal_lin.nii.gz")

In [4]: image._loaded
Out[4]: False

In [5]: image.load()

In [6]: image
Out[6]: ScalarImage(shape: (1, 181, 217, 181); spacing: (1.00, 1.00, 1.00); orientation: RAS+; dtype: torch.FloatTensor; memory: 27.1 MiB)

In [7]: image._loaded
Out[7]: True
```

**Comment by justusschock** [comment]
But how would it know attributes like `shape` and `spacing` without actually loading the image? It may not store the information, but it definitely has to load at least parts of the image.

If you call it explicitly, I get the following:

```python
In [1]: import torchio as tio

In [2]: image = tio.datasets.Colin27().t1
Downloading http://packages.bic.mni.mcgill.ca/mni-models/colin27/mni_colin27_1998_nifti.zip to /Users/justusschock/.cache/torchio/mni_colin27_1998_nifti/mni_colin27_1998_nifti.zip
24256512it [01:04, 379003.05it/s]

In [3]: image._loaded
Out[3]: False

In [4]: repr(image)
Out[4]: 'ScalarImage(shape: (1, 181, 217, 181); spacing: (1.00, 1.00, 1.00); orientation: RAS+; path: "/Users/justusschock/.cache/torchio/mni_colin27_1998_nifti/colin27_t1_tal_lin.nii.gz")'

In [5]: image._loaded
Out[5]: True
```

However, this only seems to be the case, when the file is actually downloaded to the cache as with subsequent runs, I cannot reproduce this anymore.

**Comment by fepegar** [comment]
> But how would it know attributes like shape and spacing without actually loading the image? It may not store the information, but it definitely has to load at least parts of the image.

You can read metadata from the NIfTI header very quickly without loading the _image data_.

https://github.com/fepegar/torchio/blob/8eb2f44649974c2b9c8b83082f221a18bf36496e/src/torchio/data/io.py#L118-L129

I can't reproduce your behavior, it's very strange:

```python
In [1]: import torchio as tio

In [2]: image = tio.datasets.Colin27().t1
Downloading http://packages.bic.mni.mcgill.ca/mni-models/colin27/mni_colin27_1998_nifti.zip to /Users/fernando/.cache/torchio/mni_colin27_1998_nifti/mni_colin27_1998_nifti.zip
24256512it [00:13, 1779937.55it/s]

In [3]: image._loaded
Out[3]: False

In [4]: repr(image)
Out[4]: 'ScalarImage(shape: (1, 181, 217, 181); spacing: (1.00, 1.00, 1.00); orientation: RAS+; path: "/Users/fernando/.cache/torchio/mni_colin27_1998_nifti/colin27_t1_tal_lin.nii.gz")'

In [5]: repr(image)
Out[5]: 'ScalarImage(shape: (1, 181, 217, 181); spacing: (1.00, 1.00, 1.00); orientation: RAS+; path: "/Users/fernando/.cache/torchio/mni_colin27_1998_nifti/colin27_t1_tal_lin.nii.gz")'

In [6]: image._loaded
Out[6]: False
```

**Comment by justusschock** [comment]
> You can read metadata from the NIfTI header very quickly without loading the image data.

Yes but you cannot do that for DICOM data. So it is kind of inconsistent :)

**Comment by fepegar** [comment]
> Yes but you cannot do that for DICOM data. So it is kind of inconsistent :)

Or rather "this functionality is not supported for DICOM files". I think it should work for things like NRRD too. Why in the world would someone use DICOM in a research setting anyway? :D
