### ISSUE TITLE
Histogram standardization changes image shape after transformation

### ISSUE THREAD

**Issue by kondratevakate** [fepegar/torchio#933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

So I am learning landmarks and applyiong for the dataset TCIA GBM (102 subjects, T1, T2,FLAIR and CT1)

And on the one subject TCGA-06-0142 for all images after transformation I will get different image shape. Which was not planned :)

Original:
```ANTsImage (RPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (240, 240, 168)
	 Spacing    : (1.0, 1.0, 1.0)
	 Origin     : (-121.5, 109.6625, -92.1)
	 Direction  : [ 1.  0.  0.  0. -1.  0.  0.  0.  1.]```

After Histogram standartization:
```ANTsImage (RPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (200, 200, 150)
	 Spacing    : (1.0, 1.0, 1.0)
	 Origin     : (-100.0, 102.3187, -53.5)
	 Direction  : [ 1.  0.  0.  0. -1.  0.  0.  0.  1.]```


Original image has artefact - ghosting, so I suppose, histogram standartisation will crop it out, am I correct? 

![image](https://user-images.githubusercontent.com/34157226/179226219-c24f5836-02c2-42de-a849-c013a4f8c436.png)


### Code for reproduction

```python
t1_landmarks = HistogramStandardization.train(temp_t1_list)
hist_standardize = tio.HistogramStandardization(landmarks_dict)
hist_standard = hist_standardize(subjects_list[i])
hist_standard['t1'].save('/T1.nii.gz')
```

### Actual outcome

Outputs image with cropped size

### Error messages

```python-traceback
No
```

### Expected outcome

Will output the image of original space

**Comment by fepegar** [comment]
Thanks, @kondratevakate. This is very strange. Could you please share some data and code to reproduce?

**Comment by kondratevakate** [comment]
Original image:
![image](https://user-images.githubusercontent.com/34157226/180773516-71a8675c-049f-42cc-8755-7a0800eea2ea.png)

Image after histogram standartization:
![image](https://user-images.githubusercontent.com/34157226/180773672-68b96c02-6a97-4e4b-9fec-2934cbb9fe9c.png)

Attaching [files and landmarks](https://drive.google.com/drive/folders/1nr3yUyIKCV-xQuFJBGiAP6XCqd-FvVBn?usp=sharing)

**Comment by kondratevakate** [comment]
Any updates on that? I am getting the same problem in other datasets - it change the shape after the transformation.

**Comment by fepegar** [comment]
Can you please share a code snippet I can run to reproduce the issue? I can't reproduce with what you've shared:

```python
In [1]: import torch

In [2]: landmarks = torch.load('gbm_dict.pth')

In [4]: import torchio as tio

In [5]: subject = tio.Subject(ct1=tio.ScalarImage('CT1_orig.nii.gz'))

In [6]: transform = tio.HistogramStandardization(landmarks)

In [7]: subject.shape
Out[7]: (1, 240, 240, 168)

In [8]: transform(subject).shape
Out[8]: (1, 240, 240, 168)
```
