### ISSUE TITLE
Maybe add FastMRI support

### ISSUE THREAD

**Issue by YuyangXueEd** [fepegar/torchio#936]
**🚀 Feature**

Petition: add fastMRI support

**Motivation**

Combine TorchIO datasets and augmentation with fastMRI reconstruction

**Pitch**

Hi! I am new to MRI reconstruction and I found TouchIO is a great library to dealing with MRI data. I am now working with fastMRI and it seems that TorchIO does not support raw h5 files with `ImageScalar`. Would you mind adding fastMRI dataset support? 

Looking forward to your reply. Thank you very much!

**Comment by fepegar** [comment]
Hi, @YuyangXueEd. h5 is not a standard format for medical images, so we're not planning to support it for now.
