### ISSUE TITLE
Unload image

### ISSUE THREAD

**Issue by justusschock** [fepegar/torchio#940]
**🚀 Feature**

Possibility to "unload" an image to save memory

**Motivation**

When working with huge datasets, it can easily happen that one runs out of memory. To avoid this, it would be nice to have the ability to "unload" an image if it is done with processing and may only be needed a lot later again to free up the storage

**Pitch**

It would look something like this:
```python
def unload(self):
    if not self.path:
        raise Warning("Cannot unload as not path is available from where the image could be loaded again")
        return
    self[DATA] = None
    self[AFFINE] = None
    self._loaded = False
```

**Alternatives**
The current workaround is to create new images with only the path that have not yet been loaded

**Additional context**

**Comment by fepegar** [comment]
Hey, @justusschock. Can you provide a more concrete use case? When you iterate over a dataset, images are loaded in the copied subject, so the subjects in the dataset shouldn't take any memory.

**Comment by justusschock** [comment]
In my case, It's more like: I have a dataset, process the images in the dataset sequentially and save the final images to disk. Since the dataset is so huge, I need to make sure to not keep all the images in memory all the time but just load them again when I need them.

For this I currently do something like:

```python
for img in images:
    # some processing
    result = ...
    result.save(...)
    del result
    result = None
    gc.collect()
   # further processing, can't store all images in memory here because this step is too memory-demanding

# here they are loaded again sequentially for further processing that is less computational intensive and requires all images

**Comment by fepegar** [comment]
Is `images` a `SubjectsDataset`?

**Comment by justusschock** [comment]
Not necessarily, could be a arbitrary iterable because it also just returns images and not full subjects
