### ISSUE TITLE
SimpleITK calls hangs when using num_workers > 0

### ISSUE THREAD

**Issue by snipdome** [fepegar/torchio#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

Every time the torchio calls a SimpleITK "execute" function with a worker, the thread hangs on that call.
It can happen, for example, when you have a dataset with num_workers > 0 and (spatial) transformations as data augmentation

@fepegar should be familiar with the issue that has been submitted at the SimpleITK team some time ago: https://github.com/SimpleITK/SimpleITK/issues/1239#issue-725954359

The same code used in that context can let me reproduce the bug. How should we consider it? To bring back to Sitk?

### Code for reproduction

```python
import torch
import numpy as np
import SimpleITK as sitk


num_images = 10


class MyDataset:
    def __init__(self, paths):
        self.paths = paths

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, index):
        image = sitk.ReadImage(self.paths[index])
        resampler = sitk.ResampleImageFilter()
        resampler.SetInterpolator(sitk.sitkNearestNeighbor)
        resampler.SetReferenceImage(image)
        resampler.SetDefaultPixelValue(0.0)
        resampler.SetOutputPixelType(sitk.sitkFloat32)
        print('Resampling...')
        resampled = resampler.Execute(image)
        print('Resampled!')
        array = sitk.GetArrayFromImage(resampled)
        return array


paths = []
for i in range(num_images):
    image = sitk.GetImageFromArray(np.random.rand(10, 20, 30))
    path = f'/tmp/image_{i}.nii'
    sitk.WriteImage(image, path)
    paths.append(path)

my_dataset = MyDataset(paths)

loader_sp = torch.utils.data.DataLoader(my_dataset, batch_size=4, num_workers=0)
loader_mp = torch.utils.data.DataLoader(my_dataset, batch_size=4, num_workers=2)

print('Extracting batch using one worker...')
batch_sp = next(iter(loader_sp))
print(batch_sp.shape)

print('Extracting batch using two workers...')
batch_mp = next(iter(loader_mp))
print(batch_mp.shape)
```

### Actual outcome

SimpleITK calls hangs in every worker's thread

### Expected outcome

SimpleITK calls should succeed in every worker's thread

### System info

```shell
simpleitk                 2.1.0
torchio                   0.18.83
pytorch                   1.13.0
python                    3.9.12

tested on Ubuntu 20.04 and Fedora 31
```

**Comment by fepegar** [comment]
Hi, @snipdome. Thanks for reporting. Could you please upgrade SimpleITK and try again?

**Comment by snipdome** [comment]
Hi @fepegar, that indeed solves the problem when going to 2.1.0 to 2.1.1.1. Thanks!
Should it be considered to raise the requirement for the sitk minimum version for torchio?

**Comment by fepegar** [comment]
This code actually crashed for me on 2.1.0 and 2.1.1.2. I couldn't find a 2.1.1.1 version. Anyway, it's a SimpleITK problem, so I'm closing this for now.
