### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by LucaLumetti** [fepegar/torchio#955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

The composability description (https://torchio.readthedocs.io/transforms/transforms.html#composability) states:
`Images can be composed to create directed acyclic graphs defining the probability that each transform will be applied.`
Instead of **Images**, **Transformation** is the component that can be composed. Thus the previously cited line should be:
`Transformations can be composed to create directed acyclic graphs defining the probability that each transform will be applied.`

### Code for reproduction

```python
No code can be provided
```

### Actual outcome

`Images can be composed to create directed acyclic graphs defining the probability that each transform will be applied.`

### Expected outcome

`Transformations can be composed to create directed acyclic graphs defining the probability that each transform will be applied.`

### System info

```shell
Platform:   Linux-5.15.63-1-lts-x86_64-with-glibc2.10
TorchIO:    0.18.84
PyTorch:    1.12.1+cu102
SimpleITK:  2.2.0 (ITK 5.3)
NumPy:      1.23.2
Python:     3.8.8 (default, Apr 13 2021, 19:58:26)
[GCC 7.3.0]
```

**Comment by fepegar** [comment]
Thanks, @LucaLumetti. I think "transforms" is most appropriate. Would you like to submit a pull request?

**Comment by LucaLumetti** [comment]
Sure @fepegar, I'll do it tomorrow!
