### ISSUE TITLE
padding_mode does not support functions 

### ISSUE THREAD

**Issue by mueller-franzes** [fepegar/torchio#957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

The [Pad](https://torchio.readthedocs.io/transforms/preprocessing.html#pad ) function should support numpy's [pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html) modes according to the documentation. However, passing a function throws an error. 

It could be fixed by adding `is_function = callable(padding_mode)` to  `check_padding_mode` in the Pad class, eg.:
def check_padding_mode(cls, padding_mode):
    is_number = isinstance(padding_mode, Number)
    is_function = callable(padding_mode)
    if not (padding_mode in cls.PADDING_MODES or is_number or is_function):
        message = (
            f'Padding mode "{padding_mode}" not valid. Valid options are'
            f' {list(cls.PADDING_MODES)} or a number'
        )
        raise KeyError(message)

### Code for reproduction

```python
import torchio as tio
import numpy as np 

def padding_func(vector, iaxis_pad_width, iaxis, kwargs):
        if (iaxis_pad_width[0] ==0) and (iaxis_pad_width[1] ==0):
            return 
        vector[:iaxis_pad_width[0]] = np.random.randint(0, 50, size=iaxis_pad_width[0])
        vector[-iaxis_pad_width[1]:] = np.random.randint(0, 50, size=iaxis_pad_width[1])

source = np.zeros((1,2,2,2))

trans = tio.Pad(padding=(0,1,1), padding_mode=padding_func)
out = trans(source)

print(out)
```

### Actual outcome

NA

### Error messages

```python-traceback
KeyError: 'Padding mode "<function padding_func at 0x7ff8fdb5f0d0>" not valid. Valid options are [\'empty\', \'edge\', \'wrap\', \'constant\', \'linear_ramp\', \'maximum\', \'mean\', \'median\', \'minimum\', \'reflect\', \'symmetric\'] or a number'
```

### Expected outcome

Similar to this:

[[[[25.  4. 44. 20.]
   [42.  0.  0. 36.]
   [15.  0.  0. 17.]
   [27. 35. 27. 17.]]

  [[ 1. 31.  7. 23.]
   [40.  0.  0. 10.]
   [26.  0.  0. 48.]
   [42. 35. 32. 13.]]]]

### System info

```shell
Platform:   Linux-5.15.0-41-generic-x86_64-with-glibc2.29
TorchIO:    0.18.79
PyTorch:    1.11.0+cu113
SimpleITK:  2.1.1.2 (ITK 5.2)
NumPy:      1.22.4
Python:     3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
```

**Comment by fepegar** [comment]
Hi, @mueller-franzes. Thanks for reporting. You're right, the logic is inconsistent with the documentation. Would you like to submit a fix? I don't think it's completely trivial.

**Comment by mueller-franzes** [comment]
Hi @fepegar, thank you for this great project! Yes, I will try to submit a fix.

**Comment by fepegar** [comment]
Awesome. Feel free to discuss the approach here first. I will push soon the branch I was using for experimenting.
