### ISSUE TITLE
FileNotFoundError: File not found: "affine"

### ISSUE THREAD

**Issue by shathaa1983** [fepegar/torchio#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem summary

Hi,

I am trying to apply the Torchio tutorial on a different dataset (Promise12 data set), first I converted the data into NiFti
 (.mhd)--->(.nii), then I followed the steps found on the google colab  but after I applied the # Visualize axial slices of one batch step I got this error "FileNotFoundError: File not found: "affine""

### Code for reproduction

```python
images_dir = Path("TargetImage")
labels_dir = Path("Targetlabel")
image_paths = sorted(images_dir.glob('*.nii'))
label_paths = sorted(labels_dir.glob('*.nii'))
assert len(image_paths) == len(label_paths)

subjects = []
for (image_path, label_path) in zip(image_paths, label_paths):
    subject = tio.Subject(
        prostate=tio.ScalarImage(image_path),
        mask=tio.LabelMap(label_path),
    )
    subjects.append(subject)
dataset = tio.SubjectsDataset(subjects)
print('Dataset size:', len(dataset), 'subjects')

#Patch-based:
training_batch_size = 32
validation_batch_size = 2 * training_batch_size

patch_size = 24
samples_per_volume = 5
max_queue_length = 300
sampler = tio.data.UniformSampler(patch_size)

patches_training_set = tio.Queue(
    subjects_dataset=training_set,
    max_length=max_queue_length,
    samples_per_volume=samples_per_volume,
    sampler=sampler,
    num_workers=num_workers,
    shuffle_subjects=True,
    shuffle_patches=True,
)
print (patches_training_set)

patches_validation_set = tio.Queue(
    subjects_dataset=validation_set,
    max_length=max_queue_length,
    samples_per_volume=samples_per_volume,
    sampler=sampler,
    num_workers=num_workers,
    shuffle_subjects=False,
    shuffle_patches=False,
)
training_loader_patches = torch.utils.data.DataLoader(patches_training_set, batch_size=training_batch_size)

validation_loader_patches = torch.utils.data.DataLoader(patches_validation_set, batch_size=validation_batch_size)
# Visualize axial slices of one batch
one_batch = next(iter(training_loader_patches))
k = int(patch_size // 4)
batch_mri = one_batch['prostate'][tio.DATA][..., k]
batch_label = one_batch['mask'][tio.DATA][:, 1:, ..., k]
slices = torch.cat((batch_mri, batch_label))
image_path = 'batch_patches.png'
torchvision.utils.save_image(
    slices,
    image_path,
    nrow=training_batch_size,
    normalize=True,
    scale_each=True,
)
display.Image(image_path)
```

### Actual outcome

It should appear the training result

### Error messages

```python-traceback
FileNotFoundError: File not found: "affine"
```

### Expected outcome

It should appear the training result

**Comment by fepegar** [comment]
Hi again, @shathaa1983. Please paste the full error traceback, as requested in the issue template:

> Paste the full error traceback, not just the last error.

**Comment by shathaa1983** [comment]
Hi,
@fepegar, this is the full error message
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_3093511/250958524.py in <module>
----> 1 one_batch = next(iter(training_loader_patches))
      2 k = int(patch_size // 4)
      3 batch_mri = one_batch['prostate'][tio.DATA][..., k]
      4 batch_label = one_batch['mask'][tio.DATA][:, 1:, ..., k]
      5 slices = torch.cat((batch_mri, batch_label))

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    679                 # TODO(https://github.com/pytorch/pytorch/issues/76750)
    680                 self._reset()  # type: ignore[call-arg]
--> 681             data = self._next_data()
    682             self._num_yielded += 1
    683             if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    719     def _next_data(self):
    720         index = self._next_index()  # may raise StopIteration
--> 721         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    722         if self._pin_memory:
    723             data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     50         else:
     51             data = self.dataset[possibly_batched_index]
---> 52         return self.collate_fn(data)

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
    158     elif isinstance(elem, collections.abc.Mapping):
    159         try:
--> 160             return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
    161         except TypeError:
    162             # The mapping type may not support `__init__(iterable)`.

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in <dictcomp>(.0)
    158     elif isinstance(elem, collections.abc.Mapping):
    159         try:
--> 160             return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
    161         except TypeError:
    162             # The mapping type may not support `__init__(iterable)`.

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
    158     elif isinstance(elem, collections.abc.Mapping):
    159         try:
--> 160             return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
    161         except TypeError:
    162             # The mapping type may not support `__init__(iterable)`.

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torchio/data/image.py in __init__(self, *args, **kwargs)
    639             raise ValueError('Type of ScalarImage is always torchio.INTENSITY')
    640         kwargs.update({'type': INTENSITY})
--> 641         super().__init__(*args, **kwargs)
    642 
    643 

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torchio/data/image.py in __init__(self, path, type, tensor, affine, check_nans, channels_last, reader, **kwargs)
    154 
    155         super().__init__(**kwargs)
--> 156         self.path = self._parse_path(path)
    157 
    158         self[PATH] = '' if self.path is None else str(self.path)

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torchio/data/image.py in _parse_path(self, path)
    417             return None
    418         if isinstance(path, Iterable) and not isinstance(path, str):
--> 419             return [self._parse_single_path(p) for p in path]
    420         else:
    421             return self._parse_single_path(path)

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torchio/data/image.py in <listcomp>(.0)
    417             return None
    418         if isinstance(path, Iterable) and not isinstance(path, str):
--> 419             return [self._parse_single_path(p) for p in path]
    420         else:
    421             return self._parse_single_path(path)

~/anaconda3/envs/pytorchenv/lib/python3.7/site-packages/torchio/data/image.py in _parse_single_path(path)
    407 
    408         if not (path.is_file() or path.is_dir()):   # might be a dir with DICOM
--> 409             raise FileNotFoundError(f'File not found: "{path}"')
    410         return path
    411 

FileNotFoundError: File not found: "affine"

**Comment by fepegar** [comment]
Thanks for sharing the error. Can you please provide a minimal reproducible example that I can run on my computer?

**Comment by shathaa1983** [comment]
Try this please:
import torch
import torchio

h,w,d = 10,10,10
image = torch.rand([1,h,w,d])
# assume 3 classes here
label = torch.randint(3,[1,h,w,d])

data_dict = {"image":image,"label":label}

random_affine = torchio.transforms.RandomAffine(
        include=["image","label"],p=1)

output = random_affine(data_dict)

print(data_dict["label"].dtype,len(torch.unique(data_dict["label"])))
print(output["label"].dtype,len(torch.unique(output["label"])))

**Comment by fepegar** [comment]
That code works fine on my machine. Are you using a recent version of TorchIO? You also didn't provide the system information as requested in the issue template.

**Comment by shathaa1983** [comment]
Also, on my machine
The Torchio version I use: 0.18.57
And this is my system information:
posix.uname_result(sysname='Linux', nodename='pdgx0002', release='5.4.0-91-generic', version='#102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021', machine='x86_64')

**Comment by fepegar** [comment]
Sorry, I don't understand. Does the snippet you share run fine on your machine?

**Comment by fepegar** [comment]
Also, can you please upgrade TorchIO and see if that solves your issue?

**Comment by shathaa1983** [comment]
Hi,
Thank you, the code is working fine after I update the Torchio version.
